### PR TITLE
builder/digitalocean: Use correct image type for Droplet creates.

### PR DESCRIPTION
**Pull request by andrewsomething**
The main purpose of this PR is to correct the type used when building a new DigitalOcean snapshot when the base image is specified as an integer ID rather than a string. It also adds a new acceptance test for this case. In order to do so, I had to first fix the existing acceptance test which was failing for multiple reasons.

It also adds debug logging for the attributes used to create the Droplet in order to help better understand reported issues. See: https://github.com/hashicorp/packer/issues/8141

### CODE REVIEW

**Comment by andrewsomething** [comment]
The new test failure seems to be due to the DigitalOcean API token used in the testing not being valid:

```
--- FAIL: TestBuilderAcc_imageId (0.31s)
    builder_acc_test.go:43: failed to retrieve image ID: GET https://api.digitalocean.com/v2/images/ubuntu-20-04-x64: 401 Unable to authenticate you.
```

Are the acceptance tests normally run for PRs? I don't see how the test I fixed would have ever passed.

**Comment by SwampDragons** [comment]
> Are the acceptance tests normally run for PRs?
There was a long period where none were run at all, and we're in the process of rebuilding the infrastructure for running these tests; we've begun that process with our explicitly supported builders. For community builders like digital ocean, we still haven't fixed them up.  The above test probably hasn't been run in a very long time. 

We have our builds set up not to run acceptance tests as part of branch builds. (Complex acceptance testing is generally a more manual pre-release process rather than an every build thing), so I'm not sure at a glance why this test is even being run.

**Comment by andrewsomething** [comment]
Thanks!

> For community builders like digital ocean, we still haven't fixed them up.

HashiCorp does have a subsidized DO account for running Terraform acceptance tests. Let me know if there's anything I can do to help on the DO side. I'm a single channel guest in the HashiCorp Slack (I'm asb there).

**Comment by andrewsomething** [comment]
> I left a comment inline showing why the acceptance tests is failing for the branch build.

I don't see this comment. I did find the `PACKER_ACC` environment variable which gave me an approach to forcing it to be skipped. Let me know if you had something else in mind.

**Comment by SwampDragons** [comment]
Weird. Either GitHub ate it or I did it in the wrong window. 

Your solution was pretty close to what I was gonna suggest; I was gonna say only do the API call inside of makeTemplateWithImageId() if the var you found was set; the builderT.Test infrastructure already handles skipping the test if that env var isn't set, but it wasn't being instantiated until after you try to generate the template, which has its own API call, so it was failing before the skip. 

Also, that var is a constant so you can use `os.Getenv(builderT.TestEnvVar) == ""` instead of hardcoding it if you want to be a bit more idiomatic.

**Comment by SwampDragons** [comment]
> HashiCorp does have a subsidized DO account for running Terraform acceptance tests. Let me know if there's anything I can do to help on the DO side. I'm a single channel guest in the HashiCorp Slack (I'm asb there).

I will definitely take you up on that. Thanks!!

**Comment by andrewsomething** [comment]
@SwampDragons Updated to use your proposed solution. I also broke out the logic around image types into a separate function in order to provide a unit test as well which makes Codecov happy.

**Pull request merged**
