### PR TITLE
Remove the vendor dir

### PR DESCRIPTION
**Pull request by azr**
A good first argument is that the `hashicorp/packer-plugin-sdk` repo does not have one.

Other than that it feels like `go mod` is the new widespread standard, and it looks like it is going to stick.

Another argument is that I just had many conflicts in there during a plugin breakout and to avoid that for everyone, I wanted to remove it.

### CODE REVIEW

**Comment by azr** [comment]
(will rebase if we all agree this is a good idea)

**Comment by azr** [comment]
Removing it after some internal conversation.

**Review by sylviamoss — APPROVED** [review]
LGTM! I like the 2 million code being removed 😆

**Comment by azr** [comment]
💥

**Pull request merged**
