### PR TITLE
[WIP] remove "Replace" calls to make go get work on Packer

### LINKED ISSUE #8846: packer 1.5.4 build error
#### Overview of the Issue

When trying to build packer 1.5.4 from source (**go get**) I'm experiencing the following errors:
```
# github.com/hashicorp/packer/hcl2template
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:37:22: undefined: stdlib.CeilFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:38:22: undefined: stdlib.ChompFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:39:22: undefined: stdlib.ChunklistFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:45:22: undefined: stdlib.CoalesceListFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:46:22: undefined: stdlib.CompactFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:48:22: undefined: stdlib.ContainsFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:52:22: undefined: stdlib.DistinctFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:53:22: undefined: stdlib.ElementFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:57:22: undefined: stdlib.FlattenFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:58:22: undefined: stdlib.FloorFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:58:22: too many errors
```

#### Reproduction Steps

```
$ go version
go version go1.13.8 linux/amd64

export CGO_ENABLED=0
export GO111MODULE=on
go get -v -a -ldflags '-extldflags "-static"' github.com/hashicorp/packer@v1.5.4
```

### Packer version

1.5.4

### Operating system and Environment details

Linux amd64
Go version 1.13.8

### PR DESCRIPTION
**Pull request by SwampDragons**
Still needs work to fix the flock library

helps with #8846

### CODE REVIEW

**Comment by jhawk28** [comment]
looks like @azr just needs to update some errors to get his patch merged...

**Comment by azr** [comment]
Heh I hadn't realized the reviewed mesages on my PR, 🤦‍♂ I blame lack of sleep. I updated it now.

**Comment by SwampDragons** [comment]
Waiting on merge of https://github.com/gofrs/flock/pull/43

**Comment by jhawk28** [comment]
The flock library doesn't have a go.mod file so I think you can just switch to the azr/flock repo. You can just update the package from the gofrs/flock to azr/flock here: https://github.com/hashicorp/packer/blob/master/common/filelock/filelock.go
and then update the go.mod from: 

```github.com/gofrs/flock v0.7.1```

to

```github.com/azr/flock v0.0.0-20190823144736-958d66434653```

**Comment by azr** [comment]
Howdy ! I just bumped my flock PR ( link: gofrs/flock#43), there's also a WIP to make flock support public at the go level, I just bumped it too ( link: https://github.com/golang/go/issues/33974) , but right now this PR will be blocked on those forever. I already think that removing that apache thrift replace call is nice so I think we should merge this until one of the aforementioned issues gets bumped 🙂 . ( I edited the 'close #8846' to not close the issue ).

**Pull request merged**
