### PR TITLE
Add menu key

### PR DESCRIPTION
**Pull request by mcandre**
The menu key is the only way to navigate to the Terminal from the keyboard in Haiku guests, or any other application for that matter. So it is helpful for packer to be able to signal this key in `boot_command`s, in order to provision Haiku boxes.

### CODE REVIEW

**Comment by SwampDragons** [comment]
Note to self: this includes the changes from #5987 as well. Review that one first.

**Comment by SwampDragons** [comment]
Can you rebase on master and add a test with this special code to the test I wrote [here](https://github.com/hashicorp/packer/blob/master/builder/virtualbox/common/step_type_boot_command_test.go)?

**Comment by mwhooker** [comment]
We can get this merged for the next release if you're able to get to @SwampDragons's comments

**Comment by mwhooker** [comment]
doing in #6129

**Pull request closed without merging**
