### PR TITLE
Added support for the FTP protocol.

### PR DESCRIPTION
**Pull request by arizvisa**
This was based on PR #2906, and so was delayed until that got merged upstream.

This is using the ftp client from https://github.com/jlaffaye/ftp as it was the only one I saw at the time that allowed support for resuming and thus could use a goroutine in order to allow interruption/resuming.

Closes issue hashicorp/packer#478.

### CODE REVIEW

**Comment by arizvisa** [comment]
Ok, I removed the Go 1.8-only usage of .Hostname and .Port and replaced it with an explicit modification to the .Host variable. So it should be fixed and ready for review.

**Comment by arizvisa** [comment]
However, it seems that race issue in packer/rpc has triggered in both appveyor and travis-ci's Go 1.8x test?

**Comment by arizvisa** [comment]
Re-based.

**Comment by arizvisa** [comment]
Created issue #5902 for this PR.

**Comment by SwampDragons** [comment]
@arizvisa we're looking at moving to using https://github.com/hashicorp/go-getter for our downloader rather than doing everything in-house.  I will probably hold of on reviewing this PR as well as your progress bar one until after that's all figured out (it's in our roadmap for this quarter, so I should be getting to it fairly soon).  Just thought I'd let you know I haven't forgotten you, but I'm a little worried this work may be obsolete pretty soon.

**Comment by arizvisa** [comment]
ok. it's a pretty minimal change. but whatever you guys feel like doing. i've washed my hands of this pr already.

**Comment by SwampDragons** [comment]
Okay, fair.

**Comment by SwampDragons** [comment]
Closing this for now; I don't want to add FTP support and then remove it again once we move to the go-getter library.  Sorry.

**Pull request closed without merging**
