### PR TITLE
Update external plugins to latest available release

### PR DESCRIPTION
**Pull request by nywilken**
This change is to pull in the latest version of all bundled plugins that have been patched with the SSH legacy key algorithm fix. 

- [x] Pull updated plugin for Amazon
- [x] Pull updated plugin for Azure
- [x] Pull updated plugin for GCP
- [ ] Possibly all plugins to bring them all up to date. 

Related to #8609 
Related to #10074
Related to #11656

### CODE REVIEW

**Comment by jpbuecken** [comment]
Not sure if this is the correct place, but to the context:
-> Possibly all plugins to bring them all up to date.
I need it for the vmware-iso builder 
(Use-Case: I build CentOS 9 stream with kickstart, and add a ssh public key via kickstart file, that packer uses to connect later)

**Comment by sylviamoss** [comment]
@nywilken @jpbuecken I released vpshere v1.0.4 and bumped the plugin in this PR.

**Review by JenGoldstrich — APPROVED** [review]
lgtm!

**Comment by sbraz** [comment]
Hi @nywilken, this seems to be missing the changes made in https://github.com/hashicorp/packer-plugin-openstack/pull/60. Would it please be possible to include the fix for the OpenStack plugin too?

**Comment by nywilken** [comment]
> Hi @nywilken, this seems to be missing the changes made in [hashicorp/packer-plugin-openstack#60](https://github.com/hashicorp/packer-plugin-openstack/pull/60). Would it please be possible to include the fix for the OpenStack plugin too?

Hi @sbraz  I made the call to merge in the changes we had so that the released plugins could be part of the nightly. We released all other plugins today; including openstack. I'll get all the plugins updated and trigger a nightly. I anticipate making a Packer release this week. But until then you can you try out the nightly . Thanks for pinging the thread.

**Pull request merged**
