### PR TITLE
Allow to upload files created on-the-fly

### LINKED ISSUE #2479: File provisioner fails Packer build immediately if file to be uploaded is missing
This behavior is logical in most cases and should certainly be the default. However, we have a use case in which a shell provisioner generates a file which we then want to upload using a file provisioner. In order to get around the error, we use zero-byte placeholder files to fool Packer into thinking all the files to be uploaded are already there when the build starts. Then we generate the real files and upload them. Yes, it feels quite icky to do this.

I propose an optional configuration option to indicate that the file will be generated and the Packer build command should not fail because it's missing...

```
{
  "type": "file",
  "source": "generated.tar.gz",
  "destination": "/tmp/generated.tar.gz",
  "generated": "true"
}
```

Using "generated" as the option name is just a suggestion. There are other choices that may be clearer.

### PR DESCRIPTION
**Pull request by nouney**
Add the key "generated" to the file provisioner that allows to upload files created on-the-fly.

Example:

```
{
    "builders": [{
        "type": "docker",
        "image": "ubuntu",
        "commit": true
    }],
    "provisioners": [{
        "type": "shell-local",
        "command": "touch on-the-fly.txt"
    },{
        "type": "file",
        "generated": true,
        "source": "on-the-fly.txt",
        "destination": "/tmp"
    }]
}
```

Closes #2479

I used "generated" as the option name like suggested in #2479.

### CODE REVIEW

**Comment by RajatGoyal** [comment]
Can we please merge this, seems like a good approach and many people have faced this issue here https://github.com/mitchellh/packer/issues/2479

**Comment by mwhooker** [comment]
@rickard-von-essen untargeting this from 1.0. I think we're going to go a different way with this. We can already upload generated files by uploading a directory, and I think we want to get away from workflows that involve shell-local. See some additional comments here: https://github.com/mitchellh/packer/issues/4587#issuecomment-282916068

**Comment by rickard-von-essen** [comment]
@mwhooker Sure :+:

**Comment by yonni12** [comment]
I've read most of the arguments against using this, but can you please reconsider and merge it.

It's a very simple piece of functionality that would be very useful. You can document it as "not recommended" (or similar), but given how many people have found needs and uses for this in their workflows, it seems rather unfortunate to just refuse to include it.

**Comment by SwampDragons** [comment]
We discussed this and had a change of heart. I'll be adding documentations saying that we don't recommend this, but enough people want/need this feature that it's not worth fighting out of a misguided sense of purity.

**Pull request merged**
