### PR TITLE
website: Add community maintained Unikraft Packer plugin

### PR DESCRIPTION
**Pull request by craciunoiuc**
This PR follows the model from the latest added community plugin: #12541 
Let me know if it needs something else.

I included a video from March on it's usage for the curious. Updates are coming to it soon:

https://github.com/hashicorp/packer/assets/46280801/56904f3f-193c-421c-a545-132749355ab0

cc: @glasner @lbajolet-hashicorp

### CODE REVIEW

**Comment by nywilken** [comment]
Hi @craciunoiuc thanks for opening up this PR and for your work in extending the Packer ecosystem. We have an open issue with our plugin integration docs not being discoverable once merged. So I am going to hold off on approving and merging this PR for now. Once the pipeline is squared away you can resubmit the PR as it will involve a different process. 

You can keep this PR open if you would like to keep an eye on upcoming doc changes or we can ping you once we have the integrations issue resolved.

**Comment by craciunoiuc** [comment]
Thanks a lot 🙏 

I'll keep it open so we don't forget about it

**Comment by nywilken** [comment]
@craciunoiuc we've published the updated documentation for registering a plugin as an integration to our dev-portal at https://developer.hashicorp.com/packer/docs/plugins/creation#registering-plugins

At your convenience, could you follow the guide to register the Unikraft plugin as an integration. We can help resolve any issues or update the docs if something is unclear or missing. Thanks!

**Comment by craciunoiuc** [comment]
Thanks for the link and the thorough documentation! Will go through it and make the necessary adjustments.

Will ping you when all is done.

**Pull request closed without merging**
