### PR TITLE
Make azurerm "temp key vault name" specifiable.

### PR DESCRIPTION
**Pull request by atrull**
Due to a peculiar infosec policy at my client, where packer connects through a proxy that is not permitted to contain wildcards on the host paths, we need to provide a temp_key_vault_name attribute for windows/arm builds. As such we need a way to define a ahead of the run, the keyvault name.

by specifying temp_key_vault_name xxx we then get connections to:

https://xxx.vault.azure.net

when unspecified we still get the usual pkrkv$RANDOM behaviour.

### CODE REVIEW

**Comment by atrull** [comment]
I've added some concise documentation.

**Comment by boumenot** [comment]
This is a bit of a weird change.  This is the first time I have seen such a request for it.  I am willing to accept it because the builder already allows you to tweak every other temp setting, so why not allow KeyVault too.

Before I can accept you will need to implement the necessary unit tests.  Please see config_test.go for existing examples.

**Comment by boumenot** [comment]
Please re-open if you are able to make the requested changes.

**Comment by atrull** [comment]
I've been looking through config_test.go and I'm still not sure where to put the tests. I'd actually like some guidance on what tests to write, too.

**Comment by atrull** [comment]
Also I don't appear to be able to reopen this PR myself :(

**Comment by boumenot** [comment]
Apologies, I thought I had a working example that you could follow, but I was wrong.  I fixed that by opening a PR. Once the PR is merged, you have an easy to get started with.

**Comment by SwampDragons** [comment]
Hi @atrull @boumenot  -- What's the status on this PR? Do you need anything from me to get it across the finish line? Is this something y'all still want to work on?

**Comment by boumenot** [comment]
I think the only thing necessary are unit tests.  I believe @atrull is unblocked now.

**Comment by SwampDragons** [comment]
I'm going to close this due to inactivity. @atrull if you want to get it across the finish line, please feel free to open a new PR with the requisite unit tests.

**Pull request closed without merging**
