### PR TITLE
Add template_dir() and pwd() functions to HCL

### PR DESCRIPTION
**Pull request by jeremiahsnapp**
Adding `template_dir()` and `pwd()` functions to HCL.

Let me know if the docs typo fix for `regex_replace()` should go in its own PR.

### CODE REVIEW

**Comment by jeremiahsnapp** [comment]
Thanks a lot for merging this @SwampDragons. You may want to update the HCL2 implementation list too.

https://github.com/hashicorp/packer/issues/9176

**Comment by SwampDragons** [comment]
Done. Thanks for the contribution :)

**Comment by azr** [comment]
Howdy, I'm sorry I think this needs a more time thinking, I think it would be wiser to revert this for now and think a little bit more about it.

@jeremiahsnapp could you explain a little bit more how/where you need this ? Thanks.

**Comment by jeremiahsnapp** [comment]
@azr i followed up in https://github.com/hashicorp/packer/pull/9374

**Pull request merged**
