### PR TITLE
Extract Azure plugin components from Packer

### PR DESCRIPTION
**Pull request by nywilken**
- [x] Remove Azure components and docs
- [x] Vendor remote plugin
- [x] Add remote docs
- [x] Migrate issues to new repo
- [ ] Cherry pick onto stable website

### CODE REVIEW

**Comment by SwampDragons** [comment]
Can you prioritize this? It makes me nervous having the plugin in two places, especially now that we've cut a release on the external azure plugin.

**Review by sylviamoss — APPROVED** [review]
> Hmmm...looks like my last build ended in a panic. Adding to the top of my list

Couldn't find which build panicked 🤔   This LGTM 👍🏼

**Review by azr — APPROVED** [review]
nice one, LGTM

**Comment by nywilken** [comment]
Confirmed to be executing as expected using the vendored plugin

```

~>  PACKER_ACC=1 AZURE_CLI_AUTH=1 go test -count 1 -v ./builder/azure/arm/... -run='TestBuilderAcc_.*_Linux' --timeout=120m
=== RUN   TestBuilderAcc_ManagedDisk_Linux
--- PASS: TestBuilderAcc_ManagedDisk_Linux (437.47s)
=== RUN   TestBuilderAcc_ManagedDisk_Linux_DeviceLogin
    builder_acc_test.go:128: Device Login Acceptance tests skipped unless env 'DEVICELOGIN_TEST' set, as its requires manual step during execution
--- SKIP: TestBuilderAcc_ManagedDisk_Linux_DeviceLogin (0.00s)
=== RUN   TestBuilderAcc_ManagedDisk_Linux_AzureCLI
--- PASS: TestBuilderAcc_ManagedDisk_Linux_AzureCLI (430.41s)
=== RUN   TestBuilderAcc_Blob_Linux
--- PASS: TestBuilderAcc_Blob_Linux (298.26s)
PASS
ok      github.com/hashicorp/packer-plugin-azure/builder/azure/arm      1166.514s

~>  PACKER_ACC=1 AZURE_CLI_AUTH=1 go test -count 1 -v ./builder/azure/arm/... -run='TestBuilderAcc_.*_Windows' --timeout=120m
=== RUN   TestBuilderAcc_ManagedDisk_Windows
--- PASS: TestBuilderAcc_ManagedDisk_Windows (457.46s)
=== RUN   TestBuilderAcc_ManagedDisk_Windows_Build_Resource_Group
--- PASS: TestBuilderAcc_ManagedDisk_Windows_Build_Resource_Group (517.58s)
=== RUN   TestBuilderAcc_ManagedDisk_Windows_Build_Resource_Group_Additional_Disk
--- PASS: TestBuilderAcc_ManagedDisk_Windows_Build_Resource_Group_Additional_Disk (470.55s)
=== RUN   TestBuilderAcc_ManagedDisk_Windows_DeviceLogin
    builder_acc_test.go:90: Device Login Acceptance tests skipped unless env 'DEVICELOGIN_TEST' set, as its requires manual step during execution
--- SKIP: TestBuilderAcc_ManagedDisk_Windows_DeviceLogin (0.00s)
=== RUN   TestBuilderAcc_Blob_Windows
--- PASS: TestBuilderAcc_Blob_Windows (603.61s)
PASS
ok      github.com/hashicorp/packer-plugin-azure/builder/azure/arm      2050.231s
```

**Comment by SwampDragons** [comment]
🎉

**Pull request merged**
