### PR TITLE
Remove "exoscale-import" post-processor

### PR DESCRIPTION
**Pull request by falzm**
This change removes the `exoscale-import` post-processor from the
upstream Packer repository, following extraction as a standalone plugin
in a dedicated repository (https://github.com/exoscale/packer-post-processor-exoscale-import)

### CODE REVIEW

**Comment by SwampDragons** [comment]
Cool! Can you add a link to our community page on our website so people can still find it?

https://github.com/hashicorp/packer/blob/master/website/pages/partials/provisioners/community_provisioners.mdx

**Comment by falzm** [comment]
Thank you for pointing this out @SwampDragons :)

I don't see the equivalent partial page for post-processors to the one you've shown for provisioners, however: should I create one?

**Comment by SwampDragons** [comment]
That would be great. I'm happy to do that, too, if you want to give me the text to add to it.

**Comment by SwampDragons** [comment]
looks like you may also need to call `go mod vendor` to get our vendored directory back up to date with the modules.

**Comment by falzm** [comment]
@SwampDragons I've updated the PR to remove traces of our vendored modules.

For the website community plugin listing, it'd be great if you could add the following entry:

> ## Community Post-Processors
>
> * [Exoscale Import](https://github.com/exoscale/packer-post-processor-exoscale-import/): Import a builder artifact as a new Exoscale Compute instance template.

Thanks!

**Comment by SwampDragons** [comment]
Since this is going to be a backwards-incompatible change, I have targeted it for the v1.7.0 release.

**Comment by falzm** [comment]
> Since this is going to be a backwards-incompatible change, I have targeted it for the v1.7.0 release.

Works for us, thank you 👍

**Comment by SwampDragons** [comment]
@falzm We're currently working on creating tooling that will make it easier for users to download and install plugins that are maintained by third parties; since you were already going that route with this PR, would you be interested in working with us in the new year to help us hammer out the process from an external maintainer perspective? 

We're building release workflows you can integrate with your repo so that we can register the plugin with HashiCorp and have Packer automatically retrieve it, instead of just having it documented in that page on the website.

**Comment by falzm** [comment]
Hi @SwampDragons, yes very interested, thank you for offering! Will it be similar to the Terraform registry?

Let me know how I can help :)

**Comment by SwampDragons** [comment]
Definitely similar in spirit to the third party providers part of the Terraform registry, if not exactly the same in execution. Once we've hammered out a few more with how Packer's initialization will work, I'll reach out in January with some steps to implement and we can work through them on this repo to make sure everything works how we expect.

**Comment by falzm** [comment]
Sounds good! We (Exoscale) are a HashiCorp Partner for the Terraform providers, you can reach out to us via designated contacts provided to your organization, if you prefer to discuss this matter internally.

**Review by azr — APPROVED** [review]

**Comment by nywilken** [comment]
Hi @falzm we have hammered out a lot of the details for the packer init work. I would like to pick up this PR and work with you in getting the Exoscale importer plugin ready for v1.7.0. The plugin as it stands will continue to work, but by getting ready for v1.7.0 you will be able to take advantage of the `packer init` command for installing the plugin when released. 

We've prepared an initial guide for getting an existing plugin to v1.7.0, which we are calling the multi-plugin type. Documentation for the upgrade path is https://packer-git-master.hashicorp.vercel.app/guides/1.7-plugin-upgrade. Could you take a look at the docs and let me know if you have any questions to start. 

In the meantime, I will take a look at your repository and work on drafting up a checklist for the existing plugin. We can keep this PR open until we are in a good place with the v1.7.0 upgrade. I'm going to ping you on Slack so that you can reach me directly, as well.

**Comment by SwampDragons** [comment]
Another note, if you haven't already started on the upgrade: I just finished a cli migration tool that _should_ help you upgrade all your import paths to use the new SDK, after you've got the plugin all split out: 

https://github.com/hashicorp/packer-sdk-migrator

**Comment by falzm** [comment]
Thank you @SwampDragons, I managed to migrate our plugin to the new Packer SDK using the upgrade documentation provided by @nywilken :)

**Comment by SwampDragons** [comment]
Perfect!

**Comment by nywilken** [comment]
@falzm I re-targeted this PR to release/1.8.0 which is where will completely remove this plugin. I will merge today so that it is squared away. For the next Packer release v1.7.1 we will shim the post-processor so that it is being pulled from your new release repo. I will add a note to the changelog for 1.7.1 indicating that the plugin has been vendered and for the latest release folks should move to the required_plugins block for exoscale.

**Comment by falzm** [comment]
All right, thanks @nywilken 👍

**Comment by nywilken** [comment]
This PR was rebased against and merged into the 1.8.0 release branch via the CLI. Closing this PR as it is all good to go.

**Pull request closed without merging**
