### PR TITLE
register ksyun plugin document

### PR DESCRIPTION
**Pull request by notone0010**
Registered ksyun packer plugin documentation to packer website. Ksyun is a `PaaS` platform from China. Additionally, the plugin is able to ceate Ksyun Images. For the documentation, we've done a simple local test.

### CODE REVIEW

**Comment by notone0010** [comment]
Hi @nywilken, I'm sorry to bother you. But I am in trouble. I want to register Ksyun plugin documentation to Packer website. We don't have permission to run the Vercel plugin so the workflows are not approved, could you help us run it?
Any comments on our code submissions are appreciated.

Thank you so much!

**Comment by notone0010** [comment]
Hi, @nywilken. I'm sorry to bother you agine. 3 weeks ago, I have submitted this PR for registering KingsoftCloud documentation to Packer website, but it has been hanging. Could you help me when you not busy? Thank you very much.

In addition, I have tried running in local and make it, followed by the steps to [run the website with node](https://github.com/hashicorp/packer/tree/main/website#with-node). And I figure out the screenshot of local testing result in below. 

I'm looking forward to receive your reply.

image

**Comment by nywilken** [comment]
Hi @notone0010 its not a bother. I apologize for not communicating sooner. We are in the process of deploying a new documentation process that will allow you and other plugin developers deploy directly to the Packer integrations portal. Please give me a few days to get the new documentation process squared away. Here's an example of what the integration portal will look like https://developer.hashicorp.com/waypoint/integrations

In the meantime, I approved the preview deploy so you can see how the page renders. Preview URL https://packer-b4fxm4stb-hashicorp.vercel.app/packer/plugins/builders/ksyun/epc

**Comment by notone0010** [comment]
> Hi @notone0010 its not a bother. I apologize for not communicating sooner. We are in the process of deploying a new documentation process that will allow you and other plugin developers deploy directly to the Packer integrations portal. Please give me a few days to get the new documentation process squared away. Here's an example of what the integration portal will look like https://developer.hashicorp.com/waypoint/integrations
> 
> In the meantime, I approved the preview deploy so you can see how the page renders. Preview URL https://packer-b4fxm4stb-hashicorp.vercel.app/packer/plugins/builders/ksyun/epc

Thanks for your reply, this new feature sounds very convenient. Looking forward to get the new documentation process squared away.

**Comment by notone0010** [comment]
> Hi @notone0010 its not a bother. I apologize for not communicating sooner. We are in the process of deploying a new documentation process that will allow you and other plugin developers deploy directly to the Packer integrations portal. Please give me a few days to get the new documentation process squared away. Here's an example of what the integration portal will look like https://developer.hashicorp.com/waypoint/integrations
> 
> In the meantime, I approved the preview deploy so you can see how the page renders. Preview URL https://packer-b4fxm4stb-hashicorp.vercel.app/packer/plugins/builders/ksyun/epc

Hi @nywilken , 
What's the progress of the new feature that registers plugin's documentation?​

**Review by nywilken — APPROVED** [review]
Hi @notone0010 apologies here. I have not gotten to the documentation work yet given other priorities. I've merged these changes so that the plugin is registered as a Packer plugin. Once we have the documentation ready I will follow up with you on next steps. 

In the meantime, you will be able to deploy changes to your documentation by updating the docs.zip file associated with your plugin release binaries.

**Comment by nywilken** [comment]
@notone0010 the documentation is live at https://developer.hashicorp.com/packer/plugins/builders/ksyun/epc. I have an open PR to add it to the integrations page https://developer.hashicorp.com/packer/integrations?filter=ksyun

Apologies again for the delay we are working through the migration process.

**Comment by notone0010** [comment]
> @notone0010 the documentation is live at https://developer.hashicorp.com/packer/plugins/builders/ksyun/epc. I have an open PR to add it to the integrations page https://developer.hashicorp.com/packer/integrations?filter=ksyun
> 
> Apologies again for the delay we are working through the migration process.

Never mind, my friend, and thank you for your merging. 
Meanwhile, I'm looking forward to our plugin's documentation, Ksyun, being displayed on the integrations page.

**Pull request merged**
