### PR TITLE
[WIP] up aws sdk go

### LINKED ISSUE #7053: packer validate hungs when using amazon resources and no creds are set
Hi Packer team

packer validate hungs when using amazon resources and no creds are set

Can we add a note to the documentation, or see if packer should exit as won't be able to validate?

repro
```
{ 
  "variables": {
       "aws_access_key": "",
       "aws_secret_access_key": ""
   },

  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_access_key`}}",
      "region": "us-west-2",
      "source_ami": "ami-0e32ec5bc225539f5",
      "instance_type": "t2.micro",
      "ssh_username": "ubuntu",
      "ami_name": "ec2_xenial_packer_{{timestamp}}"
    }
  ]
}
```

<3

Thanks!

### PR DESCRIPTION
**Pull request by azr**
https://github.com/aws/aws-sdk-go/pull/2298 ~fixes~ help a bit with #7053, only for mac, so we can update that vendor.

Related: #7133 #6919 #6931 #6888 #7032

### CODE REVIEW

**Comment by azr** [comment]
Oh, no, wait, it fails on windows, debug time now !

**Comment by SwampDragons** [comment]
I'd rather have all the vendor updates that aren't related to aws-sdk-go to be saved for a different PR.

**Comment by azr** [comment]
I agree ! 🙂 it seems like there is unrelated changes but :

1. `github.com/jmespath/go-jmespath` is a dependency of aws-sdk go, so it is related. :

```
GO111MODULE=on go mod why github.com/jmespath/go-jmespath
# github.com/jmespath/go-jmespath
github.com/hashicorp/packer/builder/amazon/chroot
github.com/aws/aws-sdk-go/service/ec2
github.com/aws/aws-sdk-go/aws/awsutil
github.com/jmespath/go-jmespath
```
2. some reference to weird versions of `github.com/hetznercloud/hcloud-go` were removed from go.sum by a `go mod tidy`, but they were not use and the 'real' dependency is still there, and the same: 
```
github.com/hetznercloud/hcloud-go v1.12.0 h1:ugZO8a8ADekqSWi7xWlcs6pxr4QE0tw5VnyjXcL5n28=
github.com/hetznercloud/hcloud-go v1.12.0/go.mod h1:g5pff0YNAZywQaivY/CmhUYFVp7oP0nu3MiODC2W4Hw=
```
___

I am still working on this though and checking out what's wrong on windows. I hope we can resolve this soon.

**Comment by azr** [comment]
To recap, I added a test to make sure that when no credential are set, packer won't hang forever.
After debugging, there are some cases: ( everything is go 1.11 )

1. It passes on my mac: 
```bash
$ go test -v -count=1 -timeout 30s github.com/hashicorp/packer/builder/amazon/common -run "^(TestAccessConfig_NoCredentialsFailsQuickly)$"
...
2019/01/24 16:04:36 shouldRetry returned false with &net.OpError{Op:"dial", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc0002566c0), Err:(*os.SyscallError)(0xc0002860e0)}
2019/01/24 16:04:36 shouldRetry returned false with &url.Error{Op:"Get", URL:"http://169.254.169.254/latest/meta-data/iam/security-credentials/", Err:(*net.OpError)(0xc00001eeb0)}
2019/01/24 16:04:36 shouldRetry returned false with &awserr.baseError{code:"RequestError", message:"send request failed", errs:[]error{(*url.Error)(0xc0002566f0)}}
--- PASS: TestAccessConfig_NoCredentialsFailsQuickly (5.06s)
PASS
ok      github.com/hashicorp/packer/builder/amazon/common       5.697s
```
2. Travis-ci passes. But that's because something is replying a 404 to the metada request, so false pass :
```bash
2019/01/24 13:17:58 shouldRetry returned true with &errors.errorString{s:"<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL <code>/latest/meta-data/iam/security-credentials/</code> was not found on this server.  <ins>That’s all we know.</ins>\n"}
2019/01/24 13:17:58 shouldRetry returned true with &awserr.baseError{code:"EC2MetadataError", message:"failed to make EC2Metadata request", errs:[]error{(*errors.errorString)(0xc0002425c0)}}
```
One can guess this is because it is running in GCP.

3. for circle-ci, appveyor and my windows, it fails and retries until max retries or timeout
Here's some error unwrapping :
```bash
2019/01/24 13:10:34 shouldRetry returned true with &http.httpError{err:"net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", timeout:true}
2019/01/24 13:10:34 shouldRetry returned true with &url.Error{Op:"Get", URL:"http://169.254.169.254/latest/meta-data/iam/security-credentials/", Err:(*http.httpError)(0xc00000c080)}
2019/01/24 13:10:34 shouldRetry returned true with &awserr.baseError{code:"RequestError", message:"send request failed", errs:[]error{(*url.Error)(0xc0002d20f0)}}
```
___

I initially thought that aws/aws-sdk-go#2298 would fix #7053 by making sure fatal errors are not retried but it won't be the case, as this also depends on how networking works and to quote @/jasdel :
> the SDK needs to try multiple times in case the metadata instance is not available at startup. The SDK doesn't have a reliable way to know if it is on an ec2 instance or not. So, the SDK has to always return the endpoint, unless disabled by application
> https://github.com/aws/aws-sdk-go/pull/2298#issuecomment-456147651

So this PR wont be a fix for #7053, this PR will just be an aws-sdk-go update.

**Comment by azr** [comment]
I will try to simplify the auth code for authentication as it seems it's doing weird things and could be simplified to something that will work the same without the hang.

**Comment by azr** [comment]
I'll reopen a PR when I'm done !

**Pull request closed without merging**
