### PR TITLE
Extract jdcloud

### PR DESCRIPTION
**Pull request by SwampDragons**
Extract jdcloud plugin to https://github.com/hashicorp/packer-plugin-jdcloud

### CODE REVIEW

**Comment by SwampDragons** [comment]
👋  @XiaohanLiang @remrain We should coordinate on transferring ownership and maintenance of the jdcloud plugin from HashiCorp to JDCloud

**Comment by sylviamoss** [comment]
The Vercel deplyment error is probably because the tabs in the docs of Linode is missing a space between element and content. I opened a PR in the plugin to fix it https://github.com/hashicorp/packer-plugin-linode/pull/3.

**Review by sylviamoss — APPROVED** [review]
LGTM! 👍🏼  
On the linode plugin side, just need to update the release with the fixed docs of the Linode to fix the Vercel deployment.

**Comment by sylviamoss** [comment]
I just updated the linode docs as I said above.

**Comment by azr** [comment]
(rebased on master)

**Pull request merged**
