### PR TITLE
fix issue #8534

### LINKED ISSUE #8534: When specifying a security group in Packer, if there are more than 10 security groups in the region and the specified security group comes after the 10th in DescribeSecurityGroups, Packer says the SG does not exist
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

From `packer version`

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

### PR DESCRIPTION
**Pull request by alexyueer**
closes #8534

### CODE REVIEW

**Comment by alexyueer** [comment]
@sylviamoss @SwampDragons could someone or anyone help this issue please

**Comment by azr** [comment]
Hey @alexyueer thanks for opening. @chhaj5236, as the code owner for the alicloud builder what do you think of this ?

**Comment by SwampDragons** [comment]
@chhaj5236 -- I got an email from @alexyueer that he's the new maintainer of the alicloud builder. Will you still be maintaining the builder at all or is alexy the new owner?

**Comment by chhaj5236** [comment]
Hi @azr @SwampDragons, alexyueer is the new owner of the alicloud builder. Please add him to the maintainer. Thanks : )

**Pull request merged**
