### PR TITLE
Added change support to docker-import post processor.

### LINKED ISSUE #7113: Add support for '--change' args to docker-import post-processor
I've started building docker images from scratch, by extracting a file system tar ball from a provisioned virtual machine. I then use the [compress -> docker-import -> docker-tag -> docker-push](https://github.com/lavabit/robox/blob/master/generic-docker.json) post processors to import and publish the base image.

Because these are base (aka scratch) images, without a Dockerfile, they lack a default ENTRYPOINT, CMD. This isn't a problem when the image is used directly, via `docker run -ti roboxes/centos6 bash`, as the user can provide the command to `docker run`. 

This problem is these images don't work correctly when exported as vagrant boxes. See below, but the image fails because there is default entrypoint or command:

```bash
#$ vagrant init roboxes/centos6 && vagrant up --provider docker
Bringing machine 'default' up with 'docker' provider...
==> default: Fixed port collision for 22 => 2222. Now on port 2203.
==> default: Creating the container...
    default:   Name: test_default_1544773061
    default:  Image: roboxes/centos6:1.8.52
    default: Volume: /home/user/Data/vagrant/roboxes-centos6:/vagrant
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "run", "--name", "test_default_1544773061", "-d", "-v", "/home/user/Data/vagrant/roboxes-centos6:/vagrant", "roboxes/centos6:1.8.52", {:notify=>[:stdout, :stderr]}]

Stderr: Unable to find image 'roboxes/centos6:1.8.52' locally
Trying to pull repository docker.io/roboxes/centos6 ... 
1.8.52: Pulling from docker.io/roboxes/centos6
9bd54e562ff7: Already exists
Digest: sha256:d864946446fcfedde0befca6f1bfdea0a5566f6bb6af8de5872cf39676c19e52
Status: Downloaded newer image for docker.io/roboxes/centos6:1.8.52
/usr/bin/docker-latest: Error response from daemon: No command specified.
See '/usr/bin/docker-latest run --help'.


Stdout: 
```

There are a bunch of ways to kung-fu around this, but the easiest, and by far, best option would be to add support for passing a '--change' argument when calling the `docker-import` post-processor.

### PR DESCRIPTION
**Pull request by ladar**
Initial implementation of change support to the docker post processor. Closes #7113.

Based on the change support available using docker commit build step.

@SwampDragons lacks any new unit tests. Not sure if you want to add new, test cases, specific to this functionality.

### CODE REVIEW

**Comment by ladar** [comment]
@SwampDragons I noticed you merged my other pull request... thank you. Does this pull request need any additional work? I can dig out the JSON files I used for testing the change, if necessary... as I've held off publishing any templates which rely on this feature to my repo, as I prefer not push JSON files which won't work on the currently released version of packer - if I can help it.

**Comment by SwampDragons** [comment]
Sorry, I just haven't made the time for this one's review yet. I'd love your test file, since that makes my sanity checks much lower effort 😄

**Comment by ladar** [comment]
I had to recreate my tests, and ran into trouble. When I ran scripts/build.sh the binary didn't recognize the schema change. I take it there is another step required for it to work? I was able to build/test using the Vagrant box and the following command:

```bash
vagrant destroy -f ; vagrant up && vagrant ssh -c 'sudo apt-get install -y docker* && sudo systemctl start docker && sudo usermod vagrant -a -G docker' && vagrant ssh -c 'make generate && make fmt && make test && make dev && touch test-centos6-docker.tar && gzip --force test-centos6-docker.tar && bin/packer validate generic-test1.json && bin/packer validate generic-test2.json && PACKER_LOG=1 bin/packer build -debug generic-test1.json && docker inspect test1/centos6 && PACKER_LOG=1 bin/packer build -debug generic-test2.json && docker inspect test2/centos6 && PACKER_LOG=1 bin/packer build -debug generic-test3.json && docker inspect test3/centos6'
```

To confirm the change worked, look in the debug output. Packer will output the parameters it passes to the `docker import` command. You can also run `docker inspect` against the resulting container image, and look for the new parameters. 

The test cases use a dummy, empty tarball for testing... `generic-test1.json` does not include any change variables. The `generic-test2.json` file includes a single command variable, and `generic-test3.json` includes an array of three variables. 

If you want to run a "real world" test you can grab the [robox](https://github.com/lavabit/robox/) repo, and modify the `generic-docker.json` file. Remove the `docker-push` post processor and add a `changes` parameter to the `docker-import` post processor. Then run:

```bash
./robox.sh box generic-centos6-docker
```

Which will build a CentOS 6 container. The `generic-docker.json` file also contains a CentOS 7 container configuration. To run both `./robox.sh generic-docker` instead.

P.S. You'll need an empty tarball to run the test cases manually. The commands are included in the first code snippet, but if you need to do it manually... `touch test-centos6-docker.tar && gzip `test-centos6-docker.tar` should do the trick.

[generic-test1.json.txt](https://github.com/hashicorp/packer/files/2697457/generic-test1.json.txt)
[generic-test2.json.txt](https://github.com/hashicorp/packer/files/2697458/generic-test2.json.txt)
[generic-test3.json.txt](https://github.com/hashicorp/packer/files/2697459/generic-test3.json.txt)

**Comment by ladar** [comment]
If your feeling particularly ambitious those three `docker-import` snippets could be added to a unit test.

**Comment by SwampDragons** [comment]
Gorgeous! Thanks for the repro cases, and the detailed docs.

This looks good on my end; I had no issues building the PR, and "changes" works as advertised.

**Pull request merged**
