### PR TITLE
[WIP] don't use a tty in the background

### LINKED ISSUE #7677: Packer freezes with SIGTTOU when run as bash background job (1.4.0 and later)
* Packer version: 1.4.0 or later
* Host: Linux, Ubuntu 19.04

Run literally any packer command as a bash job, without providing the `-machine-readable` flag. No need to provide a file, or actually even a command:

```
# packer &                                                                                                                     
[2] 13025
[2]  + 13025 suspended (tty output)  packer                                                                                                          
#
```

Using the `-machine-readable` flag fixes the issue; but I don't have a system to process that output, it's much more useful to me to have the original output. This issue is only encountered with packer 1.4.0 or later.

I use please.build as my build system: and this broke my builds when trying to upgrade packer. I'm not certain if please is using bash job control specifically, but SIGTTOU is still what's locking things up.

debug output for completeness:
```
2019/05/22 11:05:40 [INFO] Packer version: 1.4.1                                                                                                     
2019/05/22 11:05:40 Packer Target OS/Arch: linux amd64
2019/05/22 11:05:40 Built with Go Version: go1.12.5
2019/05/22 11:05:40 Detected home directory from env var: /home/thisguy
2019/05/22 11:05:40 Using internal plugin for digitalocean
2019/05/22 11:05:40 Using internal plugin for scaleway
2019/05/22 11:05:40 Using internal plugin for amazon-ebsvolume
2019/05/22 11:05:40 Using internal plugin for azure-arm
2019/05/22 11:05:40 Using internal plugin for parallels-iso
2019/05/22 11:05:40 Using internal plugin for proxmox
2019/05/22 11:05:40 Using internal plugin for qemu
2019/05/22 11:05:40 Using internal plugin for triton
2019/05/22 11:05:40 Using internal plugin for vagrant
2019/05/22 11:05:40 Using internal plugin for yandex
2019/05/22 11:05:40 Using internal plugin for amazon-ebs
2019/05/22 11:05:40 Using internal plugin for hyperv-vmcx
2019/05/22 11:05:40 Using internal plugin for oracle-classic
2019/05/22 11:05:40 Using internal plugin for oracle-oci
2019/05/22 11:05:40 Using internal plugin for parallels-pvm
2019/05/22 11:05:40 Using internal plugin for linode
2019/05/22 11:05:40 Using internal plugin for ncloud
2019/05/22 11:05:40 Using internal plugin for hyperv-iso
2019/05/22 11:05:40 Using internal plugin for lxd
2019/05/22 11:05:40 Using internal plugin for vmware-iso
2019/05/22 11:05:40 Using internal plugin for googlecompute
2019/05/22 11:05:40 Using internal plugin for hyperone
2019/05/22 11:05:40 Using internal plugin for docker
2019/05/22 11:05:40 Using internal plugin for lxc
2019/05/22 11:05:40 Using internal plugin for null
2019/05/22 11:05:40 Using internal plugin for profitbricks
2019/05/22 11:05:40 Using internal plugin for virtualbox-ovf
2019/05/22 11:05:40 Using internal plugin for vmware-vmx
2019/05/22 11:05:40 Using internal plugin for alicloud-ecs
2019/05/22 11:05:40 Using internal plugin for amazon-ebssurrogate
2019/05/22 11:05:40 Using internal plugin for openstack
2019/05/22 11:05:40 Using internal plugin for tencentcloud-cvm
2019/05/22 11:05:40 Using internal plugin for amazon-instance
2019/05/22 11:05:40 Using internal plugin for hcloud
2019/05/22 11:05:40 Using internal plugin for file
2019/05/22 11:05:40 Using internal plugin for oneandone
2019/05/22 11:05:40 Using internal plugin for virtualbox-iso
2019/05/22 11:05:40 Using internal plugin for amazon-chroot
2019/05/22 11:05:40 Using internal plugin for cloudstack
2019/05/22 11:05:40 Using internal plugin for puppet-server
2019/05/22 11:05:40 Using internal plugin for salt-masterless
2019/05/22 11:05:40 Using internal plugin for shell-local
2019/05/22 11:05:40 Using internal plugin for windows-shell
2019/05/22 11:05:40 Using internal plugin for ansible
2019/05/22 11:05:40 Using internal plugin for converge
2019/05/22 11:05:40 Using internal plugin for file
2019/05/22 11:05:40 Using internal plugin for sleep
2019/05/22 11:05:40 Using internal plugin for windows-restart
2019/05/22 11:05:40 Using internal plugin for breakpoint
2019/05/22 11:05:40 Using internal plugin for chef-solo
2019/05/22 11:05:40 Using internal plugin for puppet-masterless
2019/05/22 11:05:40 Using internal plugin for powershell
2019/05/22 11:05:40 Using internal plugin for shell
2019/05/22 11:05:40 Using internal plugin for ansible-local
2019/05/22 11:05:40 Using internal plugin for chef-client
2019/05/22 11:05:40 Using internal plugin for inspec
2019/05/22 11:05:40 Using internal plugin for vagrant
2019/05/22 11:05:40 Using internal plugin for vsphere-template
2019/05/22 11:05:40 Using internal plugin for alicloud-import
2019/05/22 11:05:40 Using internal plugin for digitalocean-import
2019/05/22 11:05:40 Using internal plugin for docker-tag
2019/05/22 11:05:40 Using internal plugin for manifest
2019/05/22 11:05:40 Using internal plugin for shell-local
2019/05/22 11:05:40 Using internal plugin for vsphere
2019/05/22 11:05:40 Using internal plugin for amazon-import
2019/05/22 11:05:40 Using internal plugin for compress
2019/05/22 11:05:40 Using internal plugin for docker-import
2019/05/22 11:05:40 Using internal plugin for docker-push
```

### PR DESCRIPTION
**Pull request by ThisGuyCodes**
As of packer 1.4.0 (where it starts using a TTY), packer will freeze with `SIGTTOU` if it's run as a background process (this can happen for many reasons, bash job control, or I think any time it's run non-iteractively/). See #7677 .

There are two avenues I see to resolving this: don't use a TTY if we're in the background, *or* blatantly ignore the `SIGTTOU` signal. I think both options make sense; though I'm in favor of the former. This is such an implimentation.

Closes #7677

### CODE REVIEW

**Comment by ThisGuyCodes** [comment]
Separately: I have no idea what to do with / how packer handles the go.mod file? Contribution guidelines led me down a path where the go commands intentionally ignore it.

**Comment by ThisGuyCodes** [comment]
oof, right, not everyone runs linux... I'll address this later, but I think I'll make a platform-specific function (similar to `openTTY()`).

Or maybe, since I already had to fork the package, I'll put the platform specific-ness in there.

**Comment by azr** [comment]
Hey @ThisGuyCodes, thanks for opening. Yeah, these platform specificities make things complicated here 🙂; we've had trouble with them. One super easy thing we could do would be to create & pass a `--no-tty` option to packer.

**Comment by SwampDragons** [comment]
the https://github.com/shirou/gopsutil may have what we need -- I see that it has a [background](https://godoc.org/github.com/shirou/gopsutil/process#Process.Background) check though I haven't made sure it works on windows.

**Comment by SwampDragons** [comment]
Verified that the above library seems to work on OSX and windows: https://github.com/hashicorp/packer/compare/fix_7677?expand=1

**Comment by azr** [comment]
Oh, I like that idea a lot @SwampDragons !! I committed the go modules & vendors in your branch so that we can see wether this builds.
You can see it there: https://github.com/hashicorp/packer/commits/fix_7677

Only the OpenBSD build fails ( solaris passes, which is a good news ! ).

But this is weird because the https://github.com/shirou/gopsutil#available-architectures states :

> # Available Architectures
> FreeBSD i386/amd64/arm
> Linux i386/amd64/arm(raspberry pi)
> Windows/amd64
> Darwin i386/amd64
> OpenBSD amd64 (Thank you @mpfz0r!)
> Solaris amd64 (developed and tested on SmartOS/Illumos, Thank you @jen20!)
> All works are implemented without cgo by porting c struct to golang struct.

**Comment by SwampDragons** [comment]
This issue may be relevant: https://github.com/shirou/gopsutil/issues/604

**Comment by Lomanic** [comment]
> the https://github.com/shirou/gopsutil may have what we need -- I see that it has a background check though I haven't made sure it works on windows.

FYI the process.Foreground() and process.Background() functions [are not implemented on Windows](https://github.com/shirou/gopsutil/blob/a83baef6e49bf57acfbcd987181f4f9bcde22c11/process/process_windows.go#L329) ([and everything but Darwin, Linux, FreeBSD, OpenBSD](https://github.com/shirou/gopsutil/blob/a83baef6e49bf57acfbcd987181f4f9bcde22c11/process/process_fallback.go#L122)). Defining what process is considered as "in background" is harder on Windows as this notion comes from Unix. It may be implemented in the future on Windows as "a process not being a child of a window" if we can get this info on Windows.

**Comment by SwampDragons** [comment]
@Lomanic Thanks for the clarification. I believe the false/not implemented error will be sufficient for our needs based on Packers own logic around the background check and how it uses the information to determine whether we have a TTY to use.

**Comment by SwampDragons** [comment]
@ThisGuyCodes would you like to continue working on a broader solution, or do you want me to take it over?

**Comment by SwampDragons** [comment]
I've closed because I never got a response, and opened a new PR to address this using a broader library.

**Pull request closed without merging**
