### PR TITLE
Fixes checksum for dependencies for Go 1.11.4+

### LINKED ISSUE #7242: New setup checksum mismatch
I just cloned this repo. I'm on master branch.

I'm pretty new to Go and packer.

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ go version
go version go1.11.5 darwin/amd64
```

When I try to run `make test` I get some checksum mismatch messages.
Is this an issue? If so, can I fix it?

```
$ make test
==> Checking that code complies with gofmt requirements...
Check passed.
find: -executable: unknown primary or operator
find: -executable: unknown primary or operator
==> Checking that only certain files are executable...
Check passed.
go: verifying github.com/hashicorp/go-rootcerts@v0.0.0-20160503143440-6bb64b370b90: checksum mismatch
	downloaded: h1:VBj0QYQ0u2MCJzBfeYXGexnAl17GsH1yidnoxCqqD9E=
	go.sum:     h1:9HVkPxOpo+yO93Ah4yrO67d/qh0fbLLWbKqhYjyHq9A=
go: verifying github.com/hashicorp/go-rootcerts@v0.0.0-20160503143440-6bb64b370b90: checksum mismatch
	downloaded: h1:VBj0QYQ0u2MCJzBfeYXGexnAl17GsH1yidnoxCqqD9E=
	go.sum:     h1:9HVkPxOpo+yO93Ah4yrO67d/qh0fbLLWbKqhYjyHq9A=
make: *** [test] Error 1
```

I'm doing this because I want to submit a (non-related) PR. But I'm unable to run tests on my PR without fixing these checksum messages. If I fix these, some tests are failing, and I don't know if the tests are failing because of my changes.

Any ideas?

### PR DESCRIPTION
**Pull request by davividal**
Closes #7242 

Quoting https://github.com/golang/go/issues/29278#issuecomment-447537558:
> Yes, pre-1.11.4, modules containing symlinks were constructed erroneously. 1.11.4 correctly omits those symlinks, which may change the sums for a few (hopefully isolated) modules.

### CODE REVIEW

**Comment by davividal** [comment]
I tested this PR agains Go 1.11.5.

**Comment by azr** [comment]
Hey there @davividal, thanks for taking the time to do this. I need to double check but still something looks odd.

```bash
❯ go version
go version go1.11.5 darwin/amd64
❯ rm -rf ~/go/pkg/mod/cache
❯ GO111MODULE=on go mod download
...
go: finding github.com/oklog/run v1.0.0
go: verifying github.com/gotestyourself/gotestyourself@v2.2.0+incompatible: checksum mismatch
        downloaded: h1:AQwinXlbQR2HvPjQZOmDhRqsv5mZf+Jb1RnSLxcqZcI=
        go.sum:     h1:1yOKgt0XYKUg1HOKunGOSt2ocU4bxLCjmIHt0vRtVHM=
```

**Comment by azr** [comment]
All good,  thanks !!!! 🙂

**Comment by chhaj5236** [comment]
@davividal @azr I encounter same issue here with current master branch.

➜  packer git:(master) ✗ go version
go version go1.11.5 darwin/amd64

➜  packer git:(master) ✗ uname -a
...Darwin Kernel Version 17.7.0...

And it prints following errors:
```
go: verifying github.com/docker/docker@v0.0.0-20170406124027-fa3e2d5ab9b5: checksum mismatch
        downloaded: h1:V/WghsgVPZl+92drOvPEwuZdHskJmrnD83V1msaV/Jc=
        go.sum:     h1:DwY2bFs8p+xf2WaQewx2hnGdjYR5K4UAaxcNPyKkTek=
```

It seems caused by change in https://github.com/hashicorp/packer/pull/7261
image

**Comment by azr** [comment]
Yes, currently go modules and go vendors have a bit diverged. #7270 should sort this out.

**Comment by chhaj5236** [comment]
@azr I'm little confused here. Since I ran `make dev` in two different computers. One said checksum mismatch where I posted above. But another one which I tried tonight seemed working properly with the updated checksum `h1:DwY2bFs8p+xf2WaQewx2hnGdjYR5K4UAaxcNPyKkTek=`.  Why the same code behaved differently in two environments.

**Comment by azr** [comment]
go modules are still considered experimental, it could be that checksums are different between GOOSes https://github.com/kubernetes/kubernetes/issues/69040, more: https://github.com/golang/go/issues/27925

**Comment by chhaj5236** [comment]
@azr Thanks for the info. That is helpful.

**Pull request merged**
