### PR TITLE
Fix Powershell Progress stream leak to stderr for normal and elevated commands

### LINKED ISSUE #4322: Suppressing powershell output streams in packer output
Packer version: 0.12.0
PSVersion: 5.0
OS: Windows 10

Currently when using the "powershell" provisioner i keep getting a bunch of clixml output from packer. it looks to be describing all the output streams powershell has (i.e. verbose, information, progress, etc). is there a way to suppress this?  I have added for instance $ProgressPreferance = 'SilentlyContinue' to some of my scripts but it only removes that stream information. 

Here is an example of such output - this example is really small but when i do something that takes a long time with lots of progress like windows updates i seem endless clixml streaming to my console.

```
> virtualbox-iso: Restarting Machine
==> virtualbox-iso: Waiting for machine to restart...
    virtualbox-iso: A system shutdown is in progress.(1115)
    virtualbox-iso: #< CLIXML
    virtualbox-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
    virtualbox-iso: WIN-8F5U52D6M2U restarted.
==> virtualbox-iso: Machine successfully restarted, moving on
==> virtualbox-iso: Provisioning with Powershell...
==> virtualbox-iso: Provisioning with shell script: scripts/provisioning/InstallPSModules.ps1
    virtualbox-iso: Installing PackageProvider: Nuget
    virtualbox-iso:
```

example of windows update packer output of clicml (scroll right)
```
    virtualbox-iso: 4 Installed  KB3095701 102 KB Update for Windows Server 2012 R2 (KB3095701)
    virtualbox-iso: 4 Installed  KB3094486  71 KB Update for Windows Server 2012 R2 (KB3094486)
    virtualbox-iso: 4 Installed  KB3091297 192 KB Update for Windows Server 2012 R2 (KB3091297)
    virtualbox-iso: 4 Installed  KB3078405 102 KB Update for Windows Server 2012 R2 (KB3078405)
    virtualbox-iso: 4 Installed  KB3081320   4 MB Security Update for Windows Server 2012 R2 (KB...
    virtualbox-iso: 4 Installed  KB3102939   2 MB Security Update for Windows Server 2012 R2 (KB...
    virtualbox-iso: for Windows Server 2012 R2 (KB3086255)</SD></PR></MS></Obj><S S="debug">Show update to install: Security Update for Windows Server 2012 R2 (KB3086255)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="650"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>45</PC><T>Processing</T><SR>-1</SR><SD>[84/185] Update for Windows Server 2012 R2 (KB3084905)</SD></PR></MS></Obj><S S="debug">Show update to install: Update for Windows Server 2012 R2 (KB3084905)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="651"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>46</PC><T>Processing</T><SR>-1</SR><SD>[85/185] Update for Windows Server 2012 R2 (KB3087390)</SD></PR></MS></Obj><S S="debug">Show update to install: Update for Windows Server 2012 R2 (KB3087390)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="652"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>46</PC><T>Processing</T><SR>-1</SR><SD>[86/185] Update for Windows Server 2012 R2 (KB3087041)</SD></PR></MS></Obj><S S="debug">Show update to install: Update for Windows Server 2012 R2 (KB3087041)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="653"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>47</PC><T>Processing</T><SR>-1</SR><SD>[87/185] Update for Windows Server 2012 R2 (KB3087137)</SD></PR></MS></Obj><S S="debug">Show update to install: Update for Windows Server 2012 R2 (KB3087137)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="654"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>48</PC><T>Processing</T><SR>-1</SR><SD>[88/185] Update for Windows Server 2012 R2 (KB3080042)</SD></PR></MS></Obj><S S="debug">Show update to install: Update for Windows Server 2012 R2 (KB3080042)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="655"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>48</PC><T>Processing</T><SR>-1</SR><SD>[89/185] Update for Windows Server 2012 R2 (KB3096433)</SD></PR></MS></Obj><S S="debug">Show update to install: Update for Windows Server 2012 R2 (KB3096433)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="656"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>49</PC><T>Processing</T><SR>-1</SR><SD>[90/185] Update for Windows Server 2012 R2 (KB3095701)</SD></PR></MS></Obj><S S="debug">Show update to install: Update for Windows Server 2012 R2 (KB3095701)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="657"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>49</PC><T>Processing</T><SR>-1</SR><SD>[91/185] Update for Windows Server 2012 R2 (KB3094486)</SD></PR></MS></Obj><S S="debug">Show update to install: Update for Windows Server 2012 R2 (KB3094486)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="658"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>50</PC><T>Processing</T><SR>-1</SR><SD>[92/185] Update for Windows Server 2012 R2 (KB3091297)</SD></PR></MS></Obj><S S="debug">Show update to install: Update for Windows Server 2012 R2 (KB3091297)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="659"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>50</PC><T>Processing</T><SR>-1</SR><SD>[93/185] Update for Windows Server 2012 R2 (KB3078405)</SD></PR></MS></Obj><S S="debug">Show update to install: Update for Windows Server 2012 R2 (KB3078405)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="660"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>51</PC><T>Processing</T><SR>-1</SR><SD>[94/185] Security Update for Windows Server 2012 R2 (KB3081320)</SD></PR></MS></Obj><S S="debug">Show update to install: Security Update for Windows Server 2012 R2 (KB3081320)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="661"><TNRef RefId="3" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>[4/4] Installing updates</AV><AI>0</AI><Nil /><PI>-1</PI><PC>51</PC><T>Processing</T><SR>-1</SR><SD>[95/185] Security Update for Windows Server 2012 R2 (KB3102939)</SD></PR></MS></Obj><S S="debug">Show update to install: Security Update for Windows Server 2012 R2 (KB3102939)</S><S S="debug">Send update to install collection</S><S S="debug">Try install update</S><S S="debug">Add to log collection</S><Obj S="progress" RefId="662"><TNRef RefId="3" /><MS><I64
    virtualbox-iso: 4 Installed  KB3034348   3 MB Update for Windows Server 2012 R2 (KB3034348)
    virtualbox-iso: 4 Installed  KB3098779   7 MB Security Update for Microsoft .NET Framework 4...
    virtualbox-iso: 4 Installed  KB3097997   1 MB Security Update for Microsoft .NET Framework 4...
    virtualbox-iso: 4 Installed  KB3108381   7 MB Security Update for Windows Server 2012 R2 (KB...
```

Hopefully someone has run into this before but im happy to provide anything else needed to answer this.

### LINKED ISSUE #4331: XML output on screen
Hi there, I use
- Packer version: 0.12.1
- Host platform: macOS 10.12.2
- Debug log output: https://gist.github.com/kagarlickijd/de98460697bb4ffd7bcd0f92fc4cc812
- The simplest example template and scripts needed to reproduce the bug: https://github.com/kagarlickijd/packer-demo/tree/win-shutdown

During Windows template build XML output on screen appears - http://prntscr.com/dou48b

### PR DESCRIPTION
**Pull request by DanHam**
Powershell leaks any output sent to its Progress stream to stderr when using the`-EncodedCommand` option. Note that the leak to stderr still occurs despite setting `$ProgressPreference` to `SilentlyContinue`.

Observations:

* v0.12.0 did not suffer with this issue for normal commands but did for elevated commands
* By default with v0.12.0 `ProgressPreference` was `Continue` for normal commands and `SilentlyContinue` for elevated commands 

I've tested the changes with a Windows 2012r2 build and a Windows 2016 build and this has solved the issue. Clearly more testing with other Windows/Powershell variants would be welcome...

Please note that I'm rather new to Go so any pointers on how to improve are welcome! I'm also aware that other with more experience in this area may have a better way to do this!

Closes #4322 
Closes #4331

### CODE REVIEW

**Comment by DanHam** [comment]
@rickard-von-essen communicator/winrm -> provisioner/powershell ?

**Comment by rickard-von-essen** [comment]
Update the labels.

**Comment by mwhooker** [comment]
seems fine to me, but not familiar enough to say. Maybe @taliesins can weigh in

**Comment by mwhooker** [comment]
Will this resolve #4271 ?

**Comment by mwhooker** [comment]
hmm, getting this output with these files

```
amazon-ebs output will be in this color.

==> amazon-ebs: Force Deregister flag found, skipping prevalidating AMI Name
    amazon-ebs: Found Image ID: ami-b06249a7
==> amazon-ebs: Creating temporary keypair: packer_5887c466-1b2f-fd37-5423-074224dbe179
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 5985 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-011e40762d100f8c1
==> amazon-ebs: Waiting for instance (i-011e40762d100f8c1) to become ready...
==> amazon-ebs: Adding tags to source instance
==> amazon-ebs: Waiting for auto-generated password for instance...
    amazon-ebs: It is normal for this process to take up to 15 minutes,
    amazon-ebs: but it usually takes around 5. Please wait.
    amazon-ebs:
    amazon-ebs: Password retrieved!
==> amazon-ebs: Waiting for WinRM to become available...
==> amazon-ebs: Connected to WinRM!
==> amazon-ebs: Provisioning with Powershell...
==> amazon-ebs: Provisioning with shell script: /var/folders/yy/ff0tkhr141xdxvxf5fz43kmw0000gn/T/packer-powershell-provisioner578371790
    amazon-ebs: The command completed successfully.
    amazon-ebs:
    amazon-ebs: The command completed successfully.
    amazon-ebs:
    amazon-ebs: #< CLIXML
    amazon-ebs: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> amazon-ebs: Provisioning with Powershell...
==> amazon-ebs: Provisioning with shell script: /var/folders/yy/ff0tkhr141xdxvxf5fz43kmw0000gn/T/packer-powershell-provisioner071601300
==> amazon-ebs: Stopping the source instance...
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Deregistered AMI Win2016-PackerElevatedOutputBug, id: ami-fa788eec
==> amazon-ebs: Creating the AMI: Win2016-PackerElevatedOutputBug
    amazon-ebs: AMI: ami-4f629459
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

us-east-1: ami-4f629459
```

**Comment by DanHam** [comment]
> Will this resolve #4271 ?

I didn't look too closely into that issue - when testing with the VMware and Virtualbox builders the elevated output appears as expected. I haven't yet tried to reproduce that problem with the Amazon builder...

I'll do my best to get those conflicts sorted tomorrow morning and then try and take a look at that issue with Amazon...

**Comment by taliesins** [comment]
Hi guys

I think the things we need to keep in mind are:
* powershell execution on host
* powershell execution on host via scheduled task (xml encoding required)
* powershell execution on guest
* powershell execution on guest via scheduled task (xml encoding required)

Progress may have been leaked if "-noprofile" was not specified while calling powershell.

Progress may have been leaked if "ProgressPreference" is not the first thing specified. We can't help the progress leak of loading modules.

The whole point of base64 encoding is so that we could ignore:
* xml escaping
* command line argument escaping
* powershell escaping of variables (this one was often a source of frustration by other people)

**Comment by taliesins** [comment]
Progress preference also seemed dodgy for windows 10 in the earlier releases

**Comment by DanHam** [comment]
@mwhooker Rebased/sorted conflicts.

@taliesins 

> Progress may have been leaked if "-noprofile" was not specified while calling powershell.

OK, so I remember seeing about that issue in #4317. Hopefully no more problems there.

>  Progress may have been leaked if "ProgressPreference" is not the first thing specified. We can't help the progress leak of loading modules.

In my testing the value of ProgressPreference made no difference.

* v0.12.0 did not suffer with this issue for normal commands but did for elevated commands
* By default with v0.12.0 ProgressPreference was Continue for normal commands and SilentlyContinue for elevated commands

> The whole point of base64 encoding is so that we could ignore:
> * xml escaping
> * command line argument escaping
> * powershell escaping of variables (this one was often a source of frustration by other people)


Ultimately I am in full agreement with your comments regarding the merits of base64 encoding. It *should* be the best option for all the reasons you mention and I would be 100% behind base64 encoding if it didn't appear to be causing the leak of the Progress stream to stderr. Hopefully the issues with xml escaping for the elevated command are addressed by the lines of code [here](https://github.com/DanHam/packer/blob/ae3908b635f76bf328dca0dd4187da866de21483/provisioner/powershell/provisioner.go#L428-L435). With regard to the other two points, I've tried to test as best I could. However, more testing would clearly be very welcome. 

All that said...

> I'm also aware that others with more experience in this area may have a better way to do this!

When I wrote that I actually had you in mind! 😃

**Comment by taliesins** [comment]
Can I ask that you rebase this pull request and squash any commits that are not required.

**Comment by DanHam** [comment]
@taliesins Sorry for the mess! Rebased and squashed noisy commits.

**Comment by DanHam** [comment]
@mwhooker @taliesins Is there anything further I need to do to this?

**Comment by mwhooker** [comment]
bit of a large change for 1.0 so I'm bumping to next release

**Comment by mwhooker** [comment]
If @taliesins is able to sign off on this this week, we'll get this into 1.0.1, otherwise it'll go in the next. I'm afraid I don't have enough time to really understand this PR just yet. sorry!

**Comment by mwhooker** [comment]
looks like there's still work to be done here. bumping to next release

**Comment by SwampDragons** [comment]
@taliesins how are you feeling about this PR? Wondering if we should bump to the next release to give more time fore review and rebasing.

**Comment by DanHam** [comment]
@SwampDragons @taliesins @mwhooker Apologies for the late reply. If I'm honest I thought interest in merging this PR was dead as there was no response or further comment after I rebased and cleaned things up back in late Jan...

I've replied to @taliesins comments on the PR in-line so please take a look and reply. 

I'm happy to try and improve things if it's deemed necessary. However, in my humble opinion the PR is OK to merge as is.

**Comment by DanHam** [comment]
@SwampDragons @taliesins @mwhooker OK, so I've incorporated some of the changes suggested by @taliesins - namely using a more descriptive variable name than ```command``` and also moving out the command to redirect PS output to file from elevatedTemplate. This was a good suggestion that has made things clearer and ultimately a little more robust.

I've rebased and squashed again as appropriate. I've also tested with a Windows 2012 R2 and 2016 builds which behave as expected.

Please let me know if there is anything further to do here.

**Comment by taliesins** [comment]
I have been looking at this again. Would like to know what you think on this:

I think we should never run Powershell commands via command line. We should be writing the whole command verbatim to a file. Then run Powershell against the file. Maybe we could dot include the file, but otherwise just launch Powershell via command line from Powershell.

The only thing we would ever need to worry about is escaping the here string.

This is what I have been thinking about doing for Terraform. I think we should do the same for Packer. I like the capturing of the 2 streams for stderr and stdout when running elevated commands, it should hopefully bubble up as expected now.

For normal commands
```
$ErrorActionPreference='Stop'
$command = @'
{{.Vars}}
{{.Command}}
'@
function GetTempFile($file_name) {
  $path = $env:TEMP
  if (!$path){
    $path = 'c:\windows\Temp\''
  }
  return Join-Path -Path $path -ChildPath $file_name
}

function RunAsDotInclude($scriptFile) 
{
  &$scriptFile

  return $LastExitCode
}

$script_file = GetTempFile('WinRM_Shell_Packer.ps1')
if (Test-Path $script_file) {
  Remove-Item $script_file | Out-Null
}
Set-Content -Path $script_file -Value $command | Out-Null
try{
  $username = '{{.User}}'.Replace('.#{'\\'}', $env:computername+'#{'\\'}')
  $password = '{{.Password}}'
  $exitCode = RunAsDotInclude -script_path $script_file
  exit $exitCode
} finally {
  if (Test-Path $script_file) {
      Remove-Item $script_file | Out-Null
  }
}
```

For elevated commands.
```
$ErrorActionPreference='Stop'
$command = @'
{{.Vars}}
{{.Command}}
'@
function GetTempFile($file_name) {
  $path = $env:TEMP
  if (!$path){
    $path = 'c:\windows\Temp\''
  }
  return Join-Path -Path $path -ChildPath $file_name
}
function SlurpStdout($out_file, $cur_line) {
  if (Test-Path $out_file) {
    get-content $out_file | select -skip $cur_line | ForEach {
      $cur_line += 1
      Write-Host "$_" 
    }
  }
  return $cur_line
}
function SlurpStderr($error_out_file, $cur_line) {
  if (Test-Path $error_out_file) {
    get-content $error_out_file | select -skip $cur_line | ForEach {
      $cur_line += 1
      Write-Error "$_" 
    }
  }
  return $cur_line
}
function RunAsScheduledTask($username, $password, $scriptFile) 
{
  $task_name = "WinRM_Elevated_Shell_Packer"
  $stdout_file = GetTempFile('WinRM_Elevated_Shell_Packer_stdout.log')
  $stderr_file = GetTempFile('WinRM_Elevated_Shell_Packer_stderr.log')
  if (Test-Path $stdout_file) {
    Remove-Item $stdout_file | Out-Null
  }
  if (Test-Path $stderr_file) {
    Remove-Item $stderr_file | Out-Null
  }  
  $task_xml = @'
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
    <Principals>
        <Principal id="Author">
        <UserId>{username}</UserId>
        <LogonType>Password</LogonType>
        <RunLevel>HighestAvailable</RunLevel>
        </Principal>
    </Principals>
    <Settings>
        <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
        <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
        <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
        <AllowHardTerminate>true</AllowHardTerminate>
        <StartWhenAvailable>false</StartWhenAvailable>
        <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
        <IdleSettings>
        <StopOnIdleEnd>false</StopOnIdleEnd>
        <RestartOnIdle>false</RestartOnIdle>
        </IdleSettings>
        <AllowStartOnDemand>true</AllowStartOnDemand>
        <Enabled>true</Enabled>
        <Hidden>false</Hidden>
        <RunOnlyIfIdle>false</RunOnlyIfIdle>
        <WakeToRun>false</WakeToRun>
        <ExecutionTimeLimit>PT2H</ExecutionTimeLimit>
        <Priority>4</Priority>
    </Settings>
    <Actions Context="Author">
        <Exec>
        <Command>cmd</Command>
        <Arguments>{arguments}</Arguments>
        </Exec>
    </Actions>
</Task>
'@
  $arguments = "/c powershell.exe -NonInteractive -File $script_file >$stdout_file 2>$stderr_file"
  $task_xml = $task_xml.Replace("{arguments}", $arguments.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;').Replace('"', '&quot;').Replace('''', '&apos;'))
  $task_xml = $task_xml.Replace("{username}", $username.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;').Replace('"', '&quot;').Replace('''', '&apos;'))
  
  $schedule = New-Object -ComObject "Schedule.Service"
  $schedule.Connect()
  $task = $schedule.NewTask($null)
  $task.XmlText = $task_xml
  
  $folder = $schedule.GetFolder('\')
  $folder.RegisterTaskDefinition($task_name, $task, 6, $username, $password, 1, $null) | Out-Null
  $registered_task = $folder.GetTask("\$task_name")
  $registered_task.Run($null) | Out-Null
  $timeout = 10
  $sec = 0
  while ( (!($registered_task.state -eq 4)) -and ($sec -lt $timeout) ) {
    Start-Sleep -s 1
    $sec++
  }
  $stdout_cur_line = 0
  $stderr_cur_line = 0
  do {
    Start-Sleep -m 100
    $stdout_cur_line = SlurpStdout $stdout_file $stdout_cur_line
  } while (!($registered_task.state -eq 3))
  Start-Sleep -m 100
  $exit_code = $registered_task.LastTaskResult
  $stdout_cur_line = SlurpStdout $stdout_file $stdout_cur_line
  try{
    $stderr_cur_line = SlurpStderr $stderr_file $stderr_cur_line
  } finally {
    if (Test-Path $stdout_file) {
      Remove-Item $stdout_file | Out-Null
    }
    if (Test-Path $stderr_file) {
      Remove-Item $stderr_file | Out-Null
    } 
    
    $folder.DeleteTask($task_name, 0)
    [System.Runtime.Interopservices.Marshal]::ReleaseComObject($schedule) | Out-Null
  }
  return $exit_code
}
$script_file = GetTempFile('WinRM_Elevated_Shell_Packer.ps1')
if (Test-Path $script_file) {
  Remove-Item $script_file | Out-Null
}
Set-Content -Path $script_file -Value $command | Out-Null
try{
  $username = '{{.User}}'.Replace('.#{'\\'}', $env:computername+'#{'\\'}')
  $password = '{{.Password}}'
  $exitCode = RunAsScheduledTask -username $username -password $password -script_path $script_file
  exit $exitCode
} finally {
  if (Test-Path $script_file) {
      Remove-Item $script_file | Out-Null
  }
}
```

**Comment by DanHam** [comment]
@taliesins @mwhooker @SwampDragons I've now used single quotes to surround the env vars as per @taliesins suggestion - again, thanks to @taliesins for the patient explanation. Although the issue caused by the use of double quotes is a separate and (apparently) long standing problem with the PS provisioner, this does seem like a good place to fix it and the changes required were minimal. As such I've made the changes, rebased and squashed again as appropriate...

@taliesins The changes you are suggesting above are obviously outside of the scope of the issues this PR was trying to solve. Perhaps we could merge this PR first and think about the changes and improvements you are proposing later?

That said, I can see the logic in the path you are thinking of taking. However, I do have some concerns about the additional complexity that the changes you are suggesting would introduce. If I understand correctly, to execute a standard user script we would have powershell (packer) invoking powershell (the command written to file) invoking powershell (the uploaded user script)? This would be rather hard to debug if things go awry. When it comes to executing an elevated command/script the current complexity is bad enough - at least for my brain capacity! Adding yet more layers to the current way of doing things may be asking for trouble...

In principle, the idea of splitting output from the stdout and stderr streams into separate files is a good one and perhaps could be extended to allow us to map other PS streams to Packer output. Ultimately this could allow us to natively 'understand' and reproduce output from PS's multiple streams within Packer. Following your lead, I was easily able to extend the code in this PR to split stdout and stderr as you have above.
While I was able to do this fairly easily, I am concerned about being able to preserve the order of messages produced by PS. Since we must read each outputs streams file in turn, it's possible that the order in which messages appear on the Packer console would not be the order in which the PS command/script produced them. This could potentially lead to confusion and difficulty in debugging.

I'd be glad to hear your comments back on the above.

**Comment by SwampDragons** [comment]
Removing this milestone because of the renewed discussion; 1.0.3 is already overdue.

**Comment by DanHam** [comment]
@SwampDragons @taliesins @mwhooker Hmmm... So, having taken the time to attend to the suggestions made, fix new issues, test, rebase and squash, another bump was not really what I was hoping for...

As stated above, the discussion started by @taliesins above regarding the future way the PS provisioner could work is way outside of the scope of this PR. While there is obviously much that could be discussed perhaps this PR is not the place to do it...

This PR does fix the issue it set out to address and (post suggestions from @taliesins) is more robust and actually fixes another issue into the bargain. I'm sure you appreciate that _a lot_ of time goes in to first diagnosing issues, fixing them, and then testing... 

It would be good to know if this PR is being considered for merging or if we are instead looking to make much more significant changes to the provisioner and should instead close this PR.

**Comment by SwampDragons** [comment]
@DanHam I completely understand your frustration; sorry for the runaround. I know you've sunk a ton of time into this and jumped through several hoops for us -- and I appreciate it. I'm partial to the merge-now-scope-change-later approach. However, since @taliesins is really our subject matter expert for all things windows, and has had a lot more involvement with this PR, I was waiting for his response before merging. The bump was more of a "oh dang I missed the 1.0.3 release date" rather than an judgment of whether this is ready for merge or not.

**Comment by DanHam** [comment]
@SwampDragons Ooops... Sorry if I sounded like I was having a moan there. I've read my comment back and, although it reads that way, that wasn't actually my intention!

I'm not so much frustrated. I'm just keen to avoid spending time on something when a more major change is planned instead. I was also keen to avoid the possibility of delaying the merge of this PR while a wider discussion takes place...

Hope that explains things a bit better.

Dan

**Comment by DanHam** [comment]
Blank and close PR

**Pull request closed without merging**
