### PR TITLE
support token authentication in openstack

### LINKED ISSUE #4415: Allow authentication with OS_AUTH_TOKEN env variable
In Terraform I can use the environment variable OS_AUTH_TOKEN for authentication (at least on Openstack). It would make sense if packer recognizes the same environment, so a single set of environment variables is usable for both

### PR DESCRIPTION
**Pull request by mwhooker**
resolves #4415 

todo:
- [ ] document
- [ ] get other options from env

Also noticed that if you're using a token and not username/password, the gophercloud auth from env function https://github.com/gophercloud/gophercloud/blob/50cdddf51c54e8df178af065055cbc5b3cf442e1/openstack/auth_env.go#L30 will bail out. Naturally, if you're using a token you won't be using a username/pass, so the function won't get any info from env

### CODE REVIEW

**Comment by mwhooker** [comment]
for some reason our auth method doesn't look for the token https://github.com/gophercloud/gophercloud/blob/50cdddf51c54e8df178af065055cbc5b3cf442e1/openstack/auth_env.go#L15

**Comment by abooitt** [comment]
Any plans to get this fixed? Would be very nice to have support for `OS_TOKEN` and `OS_AUTH_TYPE=token`.

**Comment by rickard-von-essen** [comment]
It's very valuable if you can verify that this works.

**Comment by abooitt** [comment]
I verified the changes made in here. It does not change anything in behavior. As mentioned by @mwhooker  earlier this must be fixed in https://github.com/gophercloud/gophercloud/blob/master/openstack/auth_env.go

**Comment by rickard-von-essen** [comment]
I'm looking into getting this in.

**Comment by rickard-von-essen** [comment]
I think we should change the whole OS auth to use `clientconfig/AuthOptions` according to https://github.com/gophercloud/gophercloud/issues/1005#issuecomment-392337764.

**Comment by SwampDragons** [comment]
I'm fine with that.

**Comment by rickard-von-essen** [comment]
Closing this in favour of #6362.

**Pull request closed without merging**
