### PR TITLE
Adds packer plugin for Mondoo

### PR DESCRIPTION
**Pull request by scottford-io**
This pull request adds documentation for [packer-plugin-mondoo](https://github.com/mondoohq/packer-plugin-mondoo). 

Closes mondoohq/packer-plugin-mondoo/issues/19

Signed-off-by: Scott Ford <scott@scottford.io>

### CODE REVIEW

**Review by nywilken — COMMENTED** [review]
@scottford-io apologies for the delay. There was an issue with the format of the docs directory which is causing the build failure. I opened a PR on the Mondoo repo to help get this squared away https://github.com/mondoohq/packer-plugin-mondoo/pull/24

Code wise this looks good. Once the docs have been updated on your end we will get this in. 
Thanks for working on the change so quickly and pushing this forward.

**Comment by scottford-io** [comment]
Thanks @nywilken. I will review shortly. 🙌

**Comment by chris-rock** [comment]
@nywilken all release for the packer plugin. Can we rerun the job here or do we need to open a new PR?

**Comment by nywilken** [comment]
@chris-rock @scottford-io the preview is here https://packer-c059yu6wp-hashicorp.vercel.app/plugins/provisioners/mondoo

But it looks like for single component plugins the url generation is not quite right https://packer-c059yu6wp-hashicorp.vercel.app/plugins/provisioners/provisioners/mondoo

I tested the docs using the docs url path to validate rendering and linking but that works different. 

Mi culpa -  it looks like the single document is the right way to go here. 

To fix could you merge the contents of the index.mdx with the contents of mondoo.mdx so that it looks similar to the following https://gist.github.com/nywilken/0c374c07c4f763a4c511b091071445a2, and re-release the docs.zip please.  You can adjust the headers as you see fit but we generally have a basic example with  the configuration reference towards the top and all other sections after. 

I apologize for the inconvenience.

**Comment by scottford-io** [comment]
@nywilken Should the end result be just the `index.mdx` or the `mondoo.mdx`? 🤔

**Comment by nywilken** [comment]
> @nywilken Should the end result be just the `index.mdx` or the `mondoo.mdx`? 🤔

A single mondoo.mdx. The Ansible plugin is actually a good example to base the docs off of https://github.com/hashicorp/packer-plugin-ansible/blob/main/docs/provisioners/ansible.mdx

**Comment by nywilken** [comment]
Thanks for the help here @scottford-io and @chris-rock

**Comment by scottford-io** [comment]
@nywilken We have released a new version with the single `mondoo.mdx`. [0.5.1](https://github.com/mondoohq/packer-plugin-mondoo/releases/tag/v0.5.1) should be good to go. Please let me know if you find any other issues that we need to address.

**Comment by nywilken** [comment]
> @nywilken We have released a new version with the single `mondoo.mdx`. [0.5.1](https://github.com/mondoohq/packer-plugin-mondoo/releases/tag/v0.5.1) should be good to go. Please let me know if you find any other issues that we need to address.

Thanks @scottford-io the changes look good go to me. Here's a preview of the docs https://packer-dg5eql7i0-hashicorp.vercel.app/plugins/provisioners/mondoo. For your final ok!

**Review by nywilken — APPROVED** [review]
Changes look good to me!

**Comment by scottford-io** [comment]
@nywilken Good to go on our end!

**Pull request merged**
