### PR TITLE
Rename and change `temporary_security_group_source_cidr`  to accept a list of strings (for Amazon builders).

### PR DESCRIPTION
**Pull request by AkshatM**
Per this change, `temporary_security_group_source_cidr` in the configuration:

1. Will be renamed to `temporary_security_group_source_cidrs`.
2. Will accept a list of CIDRs.
3. Will have its documentation updated to reflect this change.
4. Will have a fixer (with fixer tests!) attached for newer templates to avail of.

I'm unable to grep for existing tests against the original feature. That being said, all tests appear to pass locally and they do seem to touch the files I changed. :man_shrugging: Since it's just a type change which the compiler should catch and we have fixers, I'm not too fussed about it.

Addresses issues #5384, #5494

### CODE REVIEW

**Comment by AkshatM** [comment]
@SwampDragons - can you point me to the line per chance? I'm not seeing the typo unfortunately.

**Comment by AkshatM** [comment]
@SwampDragons never mind, I see the issue *sigh* will fix tonight.

**Comment by AkshatM** [comment]
@SwampDragons this should now be fixed!

**Comment by SwampDragons** [comment]
Awesome, thanks!!

**Pull request merged**
