### PR TITLE
Fix ssh host

### LINKED ISSUE #7195: openstack: ssh_host priority is lower than floating_ip
Hi!
We are using Packer v1.3.3 to build our images for openstack. In one case the available floating_ips are not directly accessible from our network but via a NAT routing.  So we tried to set the ssh host manually as in the following template: 

```json
"builders": [
    {
      "type": "openstack",
      "communicator": "ssh",
      "ssh_keypair_name": "{{user `ssh_keypair_name`}}",
      "ssh_username": "{{user `ssh_username`}}",
      "ssh_private_key_file": "{{user `ssh_key_file`}}",
      "ssh_host": "{{user `provisioning_ip`}}",
      "ssh_port": "22",
      "floating_ip": "{{user `floating_ip`}}",
      "reuse_ips": "true",
    }
```

Regardless of the ssh host the builder always uses the floating IP to connect to the instance which is not working. 
In this discussion https://groups.google.com/forum/#!topic/packer-tool/ljBAR_RTlFY it was hinted that the priority of `ssh_host` should override the default of using the floating_ip, i.e. it's a bug? 

Best regards
Eike

### LINKED ISSUE #7823: googlecompute: doesn't respect ssh_host
```json
{
  "variables": {
    "gce_project": null,
    "account_file": null
  },
  "builders": [
    {
      "type": "googlecompute",
      "account_file": "{{ user `account_file` }}",
      "project_id": "{{ user `gce_project` }}",
      "source_image": "centos-7-v20190619",
      "ssh_host": "home.desdichado.se",
      "ssh_username": "packer",
      "zone": "europe-north1-a"
    }
  ]
}
```

```
# home.desdichado.se has address 158.174.202.115

==> googlecompute: Waiting for SSH to become available...
2019/07/01 09:36:49 packer: 2019/07/01 09:36:49 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 35.228.24.246:22: i/o timeout
```

I think the same problem is in all/most cloud builders.

### PR DESCRIPTION
**Pull request by SwampDragons**
This PR makes sure that the ssh_host template option always overrides all builders' host IP discovery.

Room for improvement: many cloud builders' commHost functions are nearly identical, apart from a different named variable being pulled from the statebag. Now that the commHost function is more than two lines long, it may be time to refactor and create a helper/communicator/cloudHost function to pull this information for the builders whose commHost funcs are the same.

Closes #7823
Closes #7195

### CODE REVIEW

**Comment by JasperWoo** [comment]
Thanks for the fix! Can I start testing this? @SwampDragons

**Comment by SwampDragons** [comment]
@JasperWoo sure; builds of this branch can be found here: https://circleci.com/gh/hashicorp/packer/6745#artifacts/containers/0

**Comment by JasperWoo** [comment]
@SwampDragons The SSH works now! Thanks for the quick turnaround.

**Comment by azr** [comment]
nice change ! 👍

**Pull request merged**
