### PR TITLE
docs salt-masterless provisioner - move required element out of optional elements section

### PR DESCRIPTION
**Pull request by mayn**
## Before
screen shot 2017-07-16 at 9 22 57 am

## After
screen shot 2017-07-16 at 9 23 20 am

### CODE REVIEW

**Comment by SwampDragons** [comment]
Hey there, thanks for updating this doc!  

The reason it's listed as optional is because you might have defined the state tree in other ways (see https://github.com/hashicorp/packer/pull/269 for context) . I agree that the docs are confusing -- perhaps a clarification that you need to set local_state_tree if you haven't set the states folder using the shell provisioner?

**Comment by mayn** [comment]
thanks @SwampDragons , good catch. I'll see if i can rework it.

**Comment by mayn** [comment]
@SwampDragons it looks like the functionality you referenced was removed from master via https://github.com/hashicorp/packer/pull/2660 ... and made required.

Can you confirm, maybe i missed something

**Comment by mwhooker** [comment]
You're right, looks like it's required. Thanks!

**Pull request merged**
