### PR TITLE
Add support to vmware-vmx for linked clones

### PR DESCRIPTION
**Pull request by conradjones**
Add support to vmware-vmx for linked clones

This is useful when using multiple json templates chained via a shell script to build in steps.

00.json -> build using vmware-iso
01.json -> build using vmware-vmx -> to create a linked clone of the vmx created in the previous step.

### CODE REVIEW

**Comment by SwampDragons** [comment]
Does https://github.com/conradjones/packer/blob/abfb9f24d6cccb62087b4fe5dd9d9f61284fdbd4/builder/vmware/common/driver_fusion6.go#L25 not also need to be changed to be either "full" or "linked"?

**Comment by SwampDragons** [comment]
I have access to fusion; I can test it for you :) . That's how I caught it; I saw it running the command with "full" instead of "linked" in my logs.

**Comment by SwampDragons** [comment]
It's probably worth searching through all of the different drivers for "full" and making sure all of them have the necessary switch.

**Comment by conradjones** [comment]
I've added it.

**Pull request merged**
