### PR TITLE
Make the googlecompute builder label the resulting image.

### PR DESCRIPTION
**Pull request by petemounce**
**This PR is incomplete; I'm keeping the boilerplate for the time being.**

... so that it's possible to find images matching particular characteristics more easily.

Original discussion from https://github.com/hashicorp/packer/pull/5308#issuecomment-330236440

Please include tests. Check out these examples:

- https://github.com/hashicorp/packer/blob/master/builder/virtualbox/common/ssh_config_test.go#L19-L37
- https://github.com/hashicorp/packer/blob/master/post-processor/compress/post-processor_test.go#L153-L182

### CODE REVIEW

**Comment by petemounce** [comment]
cc @rickard-von-essen

**Comment by rickard-von-essen** [comment]
This looks fine, but I'd like to have a separate option, say `image_labels`.

**Comment by petemounce** [comment]
If you can steer me towards a decent site for tests, I'll write them?

I'm on Windows, and the steps in the CONTRIBUTING.md for that platform eluded me a bit, however.

**Comment by rickard-von-essen** [comment]
You can just add an assert [here](https://github.com/hashicorp/packer/blob/master/builder/googlecompute/step_create_image_test.go#L48) to verify that the driver is passed the value that `StepCreateImage` is called with (not a very exciting test).

**Comment by petemounce** [comment]
@rickard-von-essen thanks - added. Would you like me to add a changelog entry as well?

**Comment by rickard-von-essen** [comment]
No, don't add any change log entries.

**Comment by petemounce** [comment]
Cool. That was a really pleasant oss experience, thanks :)

**Pull request merged**
