### PR TITLE
add show expired arg when describe image

### PR DESCRIPTION
**Pull request by haoshuwei**
fix issue [#8242](https://github.com/hashicorp/packer/issues/8424)
Signed-off-by: haoshuwei <haoshuwei24@gmail.com>

### CODE REVIEW

**Comment by azr** [comment]
Hey @haoshuwei thanks for opening; please don't forget to sign the SLA; we cannot merge this PR otherwise.
Out of curiosity what `ShowExpired` does ? Make a build Error when the source image is expired ?

**Comment by sylviamoss** [comment]
Hi @haoshuwei! I was reading the DescribeImages API doc and realised that the ShowExpired paramentes will be deprecated. Are you aware of that? Could we use another solution? 
Thanks!

**Comment by chhaj5236** [comment]
Hi @haoshuwei, since ```ShowExpired ``` may be deprecated in the future, I would recommend provided a ```skip_image_validation``` option for 'expired' images. 

If this option is set to ```true```, Packer skips checking the source image and the user should make sure they provide a valid image for creating VM. And the default value could be set to ```false```.

@azr Do you think it's a better solution that makes sense?

**Comment by azr** [comment]
Sounds good to me 🙂

**Comment by sylviamoss** [comment]
Sounds good to me as well! :)

**Comment by SwampDragons** [comment]
@haoshuwei Are you able to sign the CLA, or should I close this PR?

**Comment by haoshuwei** [comment]
I am so sorry for the late reply.  AlibabaCLoud ECS has several versions of the base CentOS 7.6 public image, only the latest version is available to users, but in some situations, we need to use 
 an older image id, so that is what the `ShowExpired ` argument used for.

I agree with what @chhaj5236 suggested above to provide a `skip_image_validation` option for 'expired' images and I have update the commit, please have a review agiain. Thanks alot.

**Pull request merged**
