### PR TITLE
WIP: openstack: Report errors correctly

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Closes: #5466

### CODE REVIEW

**Comment by mwhooker** [comment]
would have assumed this change was unneeded

from the go fmt docs https://golang.org/pkg/fmt/#hdr-Printing

```
If the format (which is implicitly %v for Println etc.) is valid for a string (%s %q %v %x %X), the following two rules apply:

4. If an operand implements the error interface, the Error method will be invoked to convert the object to a string, which will then be formatted as required by the verb (if any).
```

**Comment by rickard-von-essen** [comment]
Yes that made me confused to, but then I tried:

```golang
package main

import (
	"fmt"
	"github.com/rackspace/gophercloud/openstack/compute/v2/servers"
)

func main() {
	e := servers.ErrArgument{"fn", "args", 1}
	fmt.Printf("Raw: %s\n", e)
	fmt.Printf("Error(): %s\n", e.Error())
}
```

Which gives

```
Raw: {fn args %!s(int=1)}
Error(): Bad argument in call to fn, formal parameter args, value 1
```

**Comment by rickard-von-essen** [comment]
Ok figured this out

```golang
type error interface {
  	Error() string
}
```

See definition of [error](https://golang.org/src/builtin/builtin.go#L254)

But [ErrArgument](https://github.com/rackspace/gophercloud/blob/master/openstack/compute/v2/servers/requests.go#L403) uses 

```golang
func (e *ErrArgument) Error() string {
	return fmt.Sprintf("Bad argument in call to %s, formal parameter %s, value %#v", e.Function, e.Argument, e.Value)
}
```

Trying to convert that to a `error` gives `cannot convert e (type servers.ErrArgument) to type error:
        servers.ErrArgument does not implement error (Error method has pointer receiver)`.

**Comment by rickard-von-essen** [comment]
I'll file a upstream bug on Gophercloud.

**Comment by SwampDragons** [comment]
@rickard-von-essen can you leave the gophercloud issue here so we can track it?

**Comment by rickard-von-essen** [comment]
@SwampDragons Realised that I tried this with the (old) `rackspace/gophercloud` and I'm nut sure this is correct for `gophercloud/gophercloud`. So I haven't opened an issue yet.

**Comment by SwampDragons** [comment]
@rickard-von-essen okay that's cool.  I was just browsing through old tickets and thinking of ways we can keep on top of them.  :)

**Comment by SwampDragons** [comment]
Should I close this PR for now?

**Comment by rickard-von-essen** [comment]
Yes, let's close this.

**Comment by SwampDragons** [comment]
Cool, thanks. Went on a bit of a spring cleaning binge yesterday :)

**Pull request closed without merging**
