### PR TITLE
Add image filtering on properties.

### PR DESCRIPTION
**Pull request by oseiberts11**
This change makes it possible with the openstack builder to filter source images based on image "properties". Example:

```
{
  "builders": [
    {
      "type": "openstack",
      "region": "foo",
      "image_name": "test-image",
      "ssh_username": "foo",
      "flavor": "m1.tiny",
      "source_image_filter": {
        "filters": {
          "visibility": "public",
          "properties": {
            "os_distro": "ubuntu",
            "os_type": "linux",
            "os_version": "18.04"
          }
        },
        "most_recent": false
      },
      "floating_ip_network": "foo"
    }
  ]
}
```
Since the openstack API doesn't allow filtering based on this, it is done in the builder.

### CODE REVIEW

**Comment by SwampDragons** [comment]
Is this still a WIP or is it ready for review?

**Comment by oseiberts11** [comment]
I left it on [WIP] for a while since maybe somebody on our side might have had comments. But they didn't :) so I'm removing the [WIP].

**Comment by stefreak** [comment]
@SwampDragons the merge request ist ready for review :) We would be so happy if you could have a look, we need this change :)

**Comment by stefreak** [comment]
@azr thank you, have a great day :)

**Pull request merged**
