### PR TITLE
[WIP] Bugfix builder profitbricks public ssh key

### PR DESCRIPTION
**Pull request by klemmster**

### CODE REVIEW

**Comment by SwampDragons** [comment]
Sorry for the late response here -- is there a linked issue for this? What specifically are you trying to fix here? I'd like to know what the problem is so I can validate that this solves it.

**Comment by klemmster** [comment]
> Sorry for the late response here -- is there a linked issue for this? What specifically are you trying to fix here? I'd like to know what the problem is so I can validate that this solves it.

There is no linked issue for that (although I've opened a support ticket with ionos (former profitbricks) when I opend this, asking them to take over).

The main issue this tackles: When providing the a private key to attach to the images, the public key was calculated form that, but not actually used. So the provisioner could never access the spun up instance.

**Comment by SwampDragons** [comment]
You've still got this tagged as a WIP. Is this ready for review? If so, I can help resolve conflicts.

**Comment by klemmster** [comment]
It looks like the same (and other issues I encountered) were tackled here:
https://github.com/hashicorp/packer/pull/10549 
So I'll close this.

**Pull request closed without merging**
