### PR TITLE
[proposal] merge vSphere builder from 'jetbrains-infra/packer-builder-vsphere'

### LINKED ISSUE #4526: investigate using vSphere API
There appear to be some limitations with how we work with vSphere, where the solution seems to be using the API directly.

Will use this as a meta-ticket to track the feasibility of that.

* https://github.com/mitchellh/packer/issues/2715
* #2841

### PR DESCRIPTION
**Pull request by mkuzmin**
Closes #4526 

Let's start a process of merging https://github.com/jetbrains-infra/packer-builder-vsphere into the Packer core.
This PR does not have the real code yet. I'll commit it after we settle a number of questions:

- *Backward compatibility*. Being an official builder, how strong should we keep compatibility of parameter naming schema? There are several features I'm going to significantly rewrite, and break current naming.
- *Parameter name review*. the current set of parameter names is quite inconsistent. Also, being non-native English speakers, we named some of them badly. I appreciate if you take a look at [the list](https://github.com/jetbrains-infra/packer-builder-vsphere/blob/master/README.md#parameter-reference) before the merging.
- *Contributor agreement*. We have commits from 14 people, 8 outside of JetBrains. Should all of them sign the new CLA?
- *Commit history*. Should I squash all the code into a single commit, or can import the whole history? `git blame` is super helpful in debugging.
- *Status of old plugins*. This builder overlaps with a remote mode of `vmware` builder, `vsphere` and `vsphere-template` post-processors. Technically they can coexist, but what kind of guidance are you going to give to your users? A product which performs a task by 3 different ways is a huge confusion for newcomers.
- *Acceptance tests*. The code is quite well covered by tests. Builds are run on our [public CI server](https://teamcity.jetbrains.com/viewType.html?buildTypeId=PackerVSphere_Build&guest=1), but use VPN to a vSphere lab hosted in our datacenter. I can manage this lab for a while, but cannot give any SLA for availability or recovery. Finally I'd like to migrate it to HashiCorp resources, maybe to the lab used by Terraform provider.

# Tasks

- [ ] Parameter name review
- [ ] Documentation

### CODE REVIEW

**Comment by SwampDragons** [comment]
my immediate responses:

Backward compatibility. 
 -- We do generally try to minimize backwards incompatibility, but it's sometimes just unavoidable. The way we handle backwards compatibility in Packer is to only make backwards-breaking changes on minor releases, not patch releases (e.g. 1.4.0 rather than 1.3.6), and to write "fixers" which allow people to pass their template through Packer to automatically rename variables whose names have been changed. I think it's fair to point out to users, also, that if a feature has recently been merged with Packer it can be considered to be in a "beta" state and less stable, with more backwards-breaking changes, than you'd see in our more battle-hardened plugins.

Parameter name review. 
-- I will happily review parameter names and help you rename them.

Contributor agreement.
-- Good question. The CLA you've had to deal with in Terraform hasn't even been rolled out for Packer yet.  I think we don't need to worry about this, but I'll check up the chain and get back to you.

Commit history. 
-- I would definitely like to preserve the commit history if possible. I'm happy to do the research to figure that out if you don't want to.

Status of old plugins. 
-- There is definitely overlap in functionality, but there is enough distinction that I don't think we will EOL the other plugins for some time. It might make sense to do a blog post or a flow-chart in our docs explaining which builder to use for a user's particular use case.

Acceptance tests. 
-- I agree that we should move acceptance tests to HashiCorp resources as soon as possible after we merge the plugin.

I'll review the plugin names now.

**Comment by SwampDragons** [comment]
@mkuzmin Turns out that we do need everyone who authored a commit inside this plugin to sign the CLA.

**Comment by seanmalloy** [comment]
I contributed to jetbrains-infra/packer-builder-vsphere and I signed the Hashicorp CLA.

**Comment by SwampDragons** [comment]
I went through all the parameter names and compared them to what we use for the vSphere post-processor and VMWare builders.  Here are the differences and/or name suggestions:

```

Parameter Reference

Connection

vcenter_server(string) --> Packer uses "host" in the VSphere post-processor, so I think that would be good to use here, too.

insecure_connection(boolean) --> We just use "insecure"

folder(string) --> We use "vm_folder"

host(string) --> Packer currently uses "esxi_host" for this value.

template(string) --> To help prevent confusion with vmx_template options, would it be okay to name this "source_vm_template" or something similar?

RAM(number) --> we've mostly standardized on "memory" for this

NestedHV(boolean) --> To keep the underscore convention, let's change to "nested_hv" or even "nested_virtualization".

vm_version(number) --> Currently we just use "version" for this.

disk_controller_type(string) --> I _think_ this is what we call "disk_adapter_type".

disk_thin_provisioned(boolean) --> this is a subset of options we allow. See the "disk_type_id" in the vmware builder

network_card(string) --> we use "network_adapter_type", I think.
usb_controller(boolean) --> We just use "usb"
cdrom_type(string) - We use "cdrom_adapter_type"

iso_paths(array of strings) and floppy_img_path(string): Since these are datastore paths I don't think we have clear correlaries for them, but it might be clearer to have them prefixed with "datastore_" to make it clearer where the paths are?
```

**Comment by SwampDragons** [comment]
There has been a bit of movement on the "status of old plugins" portion -- we're hoping to split the local vs remote functionality of the current vmware builders into their own builders to reduce confusion. I think there's still a place for both the vmware-esxi plugins and the vSphere plugins, for the people who use esxi but don't have a full vsphere cluster set up. We can make this distinction explicit in the docs and recommend that all people who have a true vSphere setup use the vSphere builder.

**Comment by SwampDragons** [comment]
@mkuzmin What else do you need from me to get this moving?

**Comment by SwampDragons** [comment]
@mkuzmin I'm getting some requests from the team at VMWare for making our tooling ready to work with their new vSphere products -- would you prefer we get this PR moving again, or would you prefer I start making PRs against your project?

**Comment by jhawk28** [comment]
Do we need the CLA signed by all contributors of the plugin or can we just merge the history over since it uses the same license (MPL)? I would like to see this done sooner and it seems to have stalled.

**Comment by mkuzmin** [comment]
Hi.

My job is not related to vSphere anymore, so I cannot maintain this plugin actively.
If you still want to take the ownership of the code, that's great, I'll complete the PR then. Unfortunately, I will not be able to participate in future maintenance.

**Comment by SwampDragons** [comment]
Hi @mkuzmin!  Yes, definitely let's finish this PR and have Packer take ownership of it if you can't maintain it any more. I really appreciate you getting back to us. And thanks for all your work on the plugin up to this point.

**Comment by timoline** [comment]
Please keep it going, you are almost there,
Keep up the good work!

**Comment by jhawk28** [comment]
This script will migrate the clone, iso, common, and driver directories to the packer repo with history. (sed command is for OSX)
```
git clone https://github.com/hashicorp/packer
git clone https://github.com/jetbrains-infra/packer-builder-vsphere
cd packer-builder-vsphere
git remote rm origin
git filter-branch --index-filter 'git rm --cached -qr --ignore-unmatch -- . && git reset -q $GIT_COMMIT -- clone iso driver common' --prune-empty -- --all
mkdir -p builder/vsphere
mv clone builder/vsphere/
mv iso builder/vsphere/
mv common builder/vsphere/
mv driver builder/vsphere/
find ./builder -type f -exec sed -i '.bak' "s~jetbrains-infra/packer-builder-vsphere~hashicorp/packer/builder/vsphere~g" {} \;
find . -name "*.bak" -exec rm {} \;
git add .
git commit -m "Closes #4526 add vsphere-iso and vsphere-clone"
cd ../packer
git pull ../packer-builder-vsphere master --allow-unrelated-histories
go get github.com/vmware/govmomi@v0.21.0
git add go.mod
git add go.sum
git commit -m "Closes #4526 add govmomi dependency"
```

**Comment by shotlom** [comment]
Any progress on merging this into packer?

**Comment by nilic** [comment]
Just another vote for merging vsphere-iso into Packer, epecialy since:
- vmware-iso approach of targeting ESXi host over SSH requires hacks and setups that aren't always viable in an enterprise environment
- vsphere-iso and vsphere-clone don't work with Packer 1.5.x - #8532

**Comment by shotlom** [comment]
@SwampDragons are you in a position to review this merge?

**Comment by jhawk28** [comment]
It looks like this pull request can be closed since #8480 is doing the work. (https://github.com/hashicorp/packer/pull/8480)

**Comment by shotlom** [comment]
> It looks like this pull request can be closed since #8480 is doing the work.

Ok I'll propose to close it ... any nays?

**Comment by SwampDragons** [comment]
Yeah, makes sense to close this -- we're going to merge in the other PR which actually contains code :)

**Pull request closed without merging**
