### PR TITLE
feat: versioned-docs

### PR DESCRIPTION
**Pull request by thiskevinwang**
# Description

This introduces versioned-docs to Packer!

https://packer-git-kevin-versioned-docs-hashicorp.vercel.app/docs

### CODE REVIEW

**Comment by azr** [comment]
This looks nice !!

Would you like me to try creating version branches for some plugins ? 

I saw that we will try fetching a new version every hour, what will happen if that fails or is rate limited ?

**Review by azr — APPROVED** [review]
Looking great !!!

From this page: https://packer-7ylry7avi-hashicorp.vercel.app/docs/v1.6.x/provisioners/ansible I tried to go back to the latest version and got a 404, which sounds normal, but I wonder if we should just redirect. Or maybe show a page that says plugins have moved.

**Comment by azr** [comment]
Ah, cool, super nice, yeah that message looks already super helpful lover in Waypoint

**Review by BRKalow — APPROVED** [review]
💯

**Pull request merged**
