### PR TITLE
hyperv: Add option to use legacy network adapter

### PR DESCRIPTION
**Pull request by gh2k**
Add an option to allow hyperv to use a legacy network adapter instead of the default.

### CODE REVIEW

**Comment by gh2k** [comment]
I was trying to fix #4404 with this, but it turns out that this doesn't actually help matters. My belief that having a legacy adapter would correctly report the IP address was, I think, based on faulty tests.

Nevertheless I'll leave this open as it might benefit someone and it doesn't do any harm.

**Comment by mwhooker** [comment]
Thanks very much for this. I appreciate leaving the PR open, but I don't think we'll merge this right away unless it's requested. Untargeting

**Comment by taliesins** [comment]
Can we close this PR?

**Comment by mwhooker** [comment]
@taliesins up to you

**Comment by puneetloya** [comment]
Is there a plan to merge this to main packer?

**Comment by Justin-DynamicD** [comment]
it's odd that it doesn't help matters as it should (I can install ubuntu using a legacy adapter and not need integration drivers).  While it may not "solve" the problem entirely I imagine it at least helps.

**Comment by matthew-hickok** [comment]
This would still be a great option to have.

**Comment by tuxillo** [comment]
Hi,

Why isn't this merged? It is not possible to use packer to build images of OSes that don't suport synthetic network adapters.

Before finding this PR I have done something similar (but much less elegant I think https://github.com/tuxillo/packer/commit/f67c26573c24ec8f8c11216369aba9c1293d4afd) and it's not reporting the IP back either, @gh2k did you figure out why?

Thanks,
Antonio Huete

**Comment by tuxillo** [comment]
The way the IP is retrieved in 

https://github.com/hashicorp/packer/blob/92940ec22666c72cda006975db1da65547c3c813/common/powershell/hyperv/hyperv.go#L979

seems to return "" for legacy network adapters:

    PS C:\Users\Administrator\go\bin> Hyper-V\Get-Vm | %{$_.NetworkAdapters}
    
    Name                   IsManagementOs VMName SwitchName                                       MacAddress   Status IPAddresses
    ----                   -------------- ------ ----------                                       ----------   ------ -----
    Legacy Network Adapter False          test   Red Hat VirtIO Ethernet Adapter - Virtual Switch 0155D792809 {Ok}   {}
    
I created the VM manually to test this, therefore it is not a replica, which is the only thing that would show an empty "IpAddresses" according to my google searches :)

Regards,
Antonio Huete

**Comment by SwampDragons** [comment]
Closing this due to old age and questions as to whether it ever worked. If someone wants to pick up development of this feature, I'll gladly review a new PR.

**Comment by tuxillo** [comment]
Hey wait, I'm still working on this! Sorry for the delay :)

**Comment by tuxillo** [comment]
All the work will likely happen in #5993, ignore my previous comment.

**Pull request closed without merging**
