### PR TITLE
add explanation of ui message types

### LINKED ISSUE #6880: machine readable format documentation is missing
documentation errata / missing documentation:

https://www.packer.io/docs/commands/index.html

>» Machine-Readable Message Types
The set of machine-readable message types can be found in the machine-readable format complete documentation section. This section contains documentation on all the message types exposed by Packer core as well as all the components that ship with Packer by default.

the link to **machine-readable format complete documentation** is broken, it links to the same page. I suspect this is leftover from a copy-paste from vagrant documentation, or similar, where there is a page dedicated to the format.

Google searching failed to surface the documentation, so I suspect it may be missing outright.

Hoping to get some information on the specific types and their machine readable format schema. Thanks!

Edit: Looking forward to the updated docs, thanks to the PR I've already got parsing working nicely:

```
1539905259 |  | version          | 1.3.1
1539905259 |  | version-prelease |
1539905259 |  | version-commit   | 53a792793+CHANGES
1539905259 |  | ui | say      | Packer v1.3.1
1539905260 |  | ui | error    | Error initializing core: 1 error(s) occurred:
1539905260 |  | ui | error    |
1539905260 |  | ui | error    | * required variable not set: aws_region
```

### PR DESCRIPTION
**Pull request by SwampDragons**
We had really unclear docs for what the "message type" is all about in the machine readable formatting. Clarified. 

Closes #6880

### CODE REVIEW

**Comment by eedwards-sk** [comment]
There also appears to be "version". Thanks for the quick PR!

**Comment by eedwards-sk** [comment]
I'm doing some parsing with python and I think the type is actually `ui` rather than `say`:

```
['1539903120', '', 'version', '1.3.1']
['1539903120', '', 'version-prelease', '']
['1539903120', '', 'version-commit', '53a792793+CHANGES']
['1539903120', '', 'ui', 'say', 'Packer v1.3.1']
```

types I've seen so far:
`ui`, `version`, `version-prerelease`, `version-commit`

and then documentation on each type's data would be cool, e.g. documentation for the `ui` type's data, which appears to be what you added in this pr, a la:

`say`, `message`, `error`

being the `data` segment

**Comment by SwampDragons** [comment]
Ah yes, the off-by-one error: not just a scourge for computers 😂 

Fixed, and added some flavor on the other commonly seen `target` for ya.

**Comment by eedwards-sk** [comment]
found one more :P

`artifact-count`

**Comment by SwampDragons** [comment]
Added.  If you find more, feel free to open a PR adding them to this list :)

**Comment by azr** [comment]
very interesting PR, this gave me hints for some other task !

**Comment by azr** [comment]
very interesting PR, this gave me hints for some other task !

**Comment by eedwards-sk** [comment]
For posterity if anyone else runs into this, here's the parser I wrote.
It prints out all the machine readable lines to screen, but can also turn the artifact output lines into a 'build manifest' where all the artifacts are proper python objects.

https://github.com/Snapkitchen/concourse-packer-resource/blob/master/lib/packer.py

**Pull request merged**
