### PR TITLE
fix(promox): update proxmox-api-go dependency

### LINKED ISSUE #7692: [proxmox] error calculating first free VMID on a blank proxmox server
- Packer version from `packer version`
1.4.1

- Host platform
Windows 7 x64 (running packer.exe)  and Proxmox VE separate.

- Bug Details:
When a Packer build for Proxmox is executed on a PVE server with no VMs, the build fails as it comes up with the "nextid" as "1". Proxmox needs the minimum VMID to be **100**.

```
$ packer.exe build one.json
proxmox output will be in this color.

==> proxmox: Creating VM
==> proxmox: No VM ID given, getting next free from Proxmox
==> proxmox: Error creating VM: 400 Parameter verification failed., error status:  (params: map[agent:1 cores:2 cpu:host description:Packer ephemeral build VM ide2:local:iso/CentOS-7-x86_64-Minimal-1810.iso,media=cdrom memory:2048 name:packer-5ce91ad0-c8aa-1f08-6c2e-b3da6c341fc0 net0:e1000=8E:6A:53:3F:A2:74,bridge=vmbr0 onboot:false ostype:l26 scsi0:media=disk,size=8G,file=local:1/vm-1-disk-0.qcow2,format=qcow2 sockets:1 vmid:1])
Build 'proxmox' errored: Error creating VM: 400 Parameter verification failed., error status:  (params: map[agent:1 cores:2 cpu:host description:Packer ephemeral build VM ide2:local:iso/CentOS-7-x86_64-Minimal-1810.iso,media=cdrom memory:2048 name:packer-5ce91ad0-c8aa-1f08-6c2e-b3da6c341fc0 net0:e1000=8E:6A:53:3F:A2:74,bridge=vmbr0 onboot:false ostype:l26 scsi0:media=disk,size=8G,file=local:1/vm-1-disk-0.qcow2,format=qcow2 sockets:1 vmid:1])

==> Some builds didn't complete successfully and had errors:
--> proxmox: Error creating VM: 400 Parameter verification failed., error status:  (params: map[agent:1 cores:2 cpu:host description:Packer ephemeral build VM ide2:local:iso/CentOS-7-x86_64-Minimal-1810.iso,media=cdrom memory:2048 name:packer-5ce91ad0-c8aa-1f08-6c2e-b3da6c341fc0 net0:e1000=8E:6A:53:3F:A2:74,bridge=vmbr0 onboot:false ostype:l26 scsi0:media=disk,size=8G,file=local:1/vm-1-disk-0.qcow2,format=qcow2 sockets:1 vmid:1])

==> Builds finished but no artifacts were created.
```

- Debug log output from `PACKER_LOG=1 packer build template.json`.
(not needed)

- The _simplest example template and scripts_ needed to reproduce the bug.
```
{
  "variables": {
    "username": "user@pve",
    "password": "supersecretpassword"
  },
  "builders": [
    {
      "type": "proxmox",
      "proxmox_url": "https://192.168.0.54:8006/api2/json",
      "insecure_skip_tls_verify": true,
      "username": "{{user `username`}}",
      "password": "{{user `password`}}",
      "node": "pve01",
      "network_adapters": [
        {
          "bridge": "vmbr0"
        }
      ],
      "disks": [
        {
          "type": "scsi",
          "disk_size": "8G",
          "storage_pool": "local",
          "storage_pool_type": "directory",
          "format": "qcow2"
        }
      ],
      "memory": 2048,
      "cores": 2,
      "sockets": 1,
      "os": "l26",
      "iso_file": "local:iso/CentOS-7-x86_64-Minimal-1810.iso",
      "http_directory":"config",
      "boot_wait": "10s",
      "boot_command": [
        "<up><tab> ip=dhcp inst.cmdline inst.ks=http://{{.HTTPIP}}:{{.HTTPPort}}/ks.cfg<enter>"
      ],

      "ssh_username": "root",
      "ssh_timeout": "15m",
      "ssh_password": "packer",

      "unmount_iso": true,
      "template_name": "centos-7",
      "template_description": "CentOS 7: {{ isotime \"2006-01-02T15:04:05Z\" }}"
    }
  ]
}

```

### PR DESCRIPTION
**Pull request by aerialls**
Closes #7692.

The VM id generator was broken when the cluster does not have any machines yet. Proxmox cannot handle VM ids lower than 100.

### CODE REVIEW

**Comment by aerialls** [comment]
I'm not sure to understand why tests are failing. It's working on my laptop.

**Comment by SwampDragons** [comment]
From the tests: 
>builder\proxmox\step_start_vm.go:32:3: cannot use agent (type int) as type string in field value

**Comment by aerialls** [comment]
I've updated the `vendor` folder with the latest dependencies and it seems to work.

**Comment by azr** [comment]
LGTM, thanks !

**Pull request merged**
