### PR TITLE
[WIP] Use go-rootcerts to support login-keychain in OSX

### PR DESCRIPTION
**Pull request by nwillems**
This change introduces go-rootcerts usage for the default http client, such requests made will be able to use the login-keychain in OSX. I haven't actually made this work locally, not quite sure why - inputs are very much welcome :-)

The change should be similar in functionality to what has already been done for the atlas provider #3494

I discovered this "error" when trying to use packer to upload a vagrant box to our internal repository, using a corporate internal certificate.

I'm not aware of any issues already opened.

### CODE REVIEW

**Comment by nwillems** [comment]
Is it possible to change one's CLA? Say I have confered with my employer, and they agree to let me work on this during company time?

**Comment by SwampDragons** [comment]
I'd say that falls under 4: 

>If your employer(s) has rights to intellectual property that you create that includes your Contributions, you represent that you have received permission to make Contributions on behalf of that employer

**Comment by SwampDragons** [comment]
Anyway, thanks for this -- lmk when you want a review; otherwise I normally wait to read over the code until the WIP tag is removed.

**Comment by nwillems** [comment]
No need to drag this further along. I'll keep doing this on my own time. So juist a rebase, and then I'll remove the WIP.

**Comment by SwampDragons** [comment]
Closing due to inactivity; if you want to resubmit after rebasing, you can either force-push here or open a new PR.

**Pull request closed without merging**
