### PR TITLE
Vagrant post-processor for using a Docker image

### PR DESCRIPTION
**Pull request by double16**
Adds support for packaging a Docker image as a vagrant box. This is useful when wanting to include settings such as ports, volumes, etc. in the Vagrantfile while still leveraging the benefits of Docker.

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Needs docs.

**Comment by rickard-von-essen** [comment]
I'm  not sure about the list of input artifacts. Why isn't the docker builders direct artifact there?

**Comment by double16** [comment]
I was focused on post-processors that specified a tag, but using the sha256 for referencing an image is also valid. The docker builder provides that as the artifact ID, so it works.

Added docs.

**Comment by rickard-von-essen** [comment]
I think I tricked you.

It looks like the `docker` builder when `commit: true` produces a `packer.post-processor.docker-import` artifact. And `packer.docker` is only used when a tar is exported, which of course can't be used.

See https://github.com/hashicorp/packer/blob/master/builder/docker/builder.go#L13-L14 and https://github.com/hashicorp/packer/blob/master/builder/docker/builder.go#L96-L104

**Comment by double16** [comment]
;) ok, I removed it

**Comment by SwampDragons** [comment]
Do you have a usage example? I just tried running this to create a vagrant box and got the following error message: 
```
* Post-processor failed: Unknown artifact type, can't build box: packer.docker
```

**Comment by rickard-von-essen** [comment]
If you set `commit` to true it should work *)

* I haven't actually tested this.

**Comment by SwampDragons** [comment]
You were right, @rickard-von-essen. I think I'd like to see that caveat about needing commit: true added to the documentation, but otherwise this looks good.

**Comment by double16** [comment]
I cleaned up the docs and included the `commit: true` requirement.

**Comment by double16** [comment]
A test case of docker builder -> docker-tag -> docker-push -> vagrant isn't working. Please don't merge this yet.

**Comment by double16** [comment]
I changed docker-push to return a docker-import artifact like docker-tag does. This fixes the docker builder -> docker-tag -> docker-push -> vagrant case.

**Pull request merged**
