### PR TITLE
alicloud: delete copied image and snapshots if corresponding options are specified

### PR DESCRIPTION
**Pull request by chhaj5236**
If `image_force_delete` and `image_force_delete_snapshots` are set to `true`, not only duplicated image in source region will be deleted, but also those in `image_copy_regions` will be deleted according to `image_copy_names`.

### CODE REVIEW

**Comment by SwampDragons** [comment]
Looks like you need to run `make fmt` to unstick the tests :)

**Comment by rickard-von-essen** [comment]
This seems to be overlapping with `--force`?

**Comment by chhaj5236** [comment]
> This seems to be overlapping with `--force`?

@rickard-von-essen Is "--force" a `packer` option? I'm not seeing it in the document. Did I miss it somewhere? I'd like to take a look and see if this PR is not needed. Thanks : )

Background here for clarity:
AliCloud provider now has two options (`image_force_delete` and `image_force_delete_snapshots`) to control deleting duplicated image and relevant snapshots, but only works on the source image. This PR will include deleting copied images as well if those two options are set.

**Comment by chhaj5236** [comment]
> Looks like you need to run `make fmt` to unstick the tests :)

I'll check that. Thanks for reminding.

**Comment by chhaj5236** [comment]
@SwampDragons @rickard-von-essen I have updated the codes to support `-force` and unstick the tests. But the following case that was not related to current change was failed. This case seems failed randomly, I run this on my laptop multiple times and it all passed. Do you have any suggestion?  Thanks.

```
==================
WARNING: DATA RACE
Write at 0x00c000119a51 by goroutine 90:
  testing.tRunner()
      /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:830 +0x174
Previous write at 0x00c000119a51 by goroutine 31:
  testing.(*common).FailNow()
      /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:589 +0x4c
  testing.(*common).Fatalf()
      /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:634 +0x94
  github.com/hashicorp/packer/packer/rpc.TestMuxBroker.func1()
      /home/travis/gopath/src/github.com/hashicorp/packer/packer/rpc/mux_broker_test.go:27 +0x1b2
Goroutine 90 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:878 +0x650
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:1119 +0xa8
  testing.tRunner()
      /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:827 +0x162
  testing.runTests()
      /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:1117 +0x4ee
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:1034 +0x2ee
  main.main()
      _testmain.go:98 +0x221
Goroutine 31 (finished) created at:
  github.com/hashicorp/packer/packer/rpc.TestMuxBroker()
      /home/travis/gopath/src/github.com/hashicorp/packer/packer/rpc/mux_broker_test.go:20 +0x2d6
  testing.tRunner()
      /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:827 +0x162
==================
--- FAIL: TestMuxBroker (0.00s)
    mux_broker_test.go:27: err: session shutdown
    testing.go:771: race detected during execution of test
```

**Comment by chhaj5236** [comment]
@SwampDragons @rickard-von-essen  I have re-run the CI and it passed. I opened another issue #7070 to follow. Please take a look at current PR if it's ready to merge. Thanks for your help : )

**Comment by SwampDragons** [comment]
@chhaj5236 can you send me an email at megan at hashicorp dot com? I want to have HashiCorp send you some swag as thanks for maintaining this builder and need some real life contact info.

**Pull request merged**
