### PR TITLE
Add UpCloud builder to community builders page

### PR DESCRIPTION
**Pull request by nywilken**

### CODE REVIEW

**Comment by nywilken** [comment]
Waiting to get approval on copy from plugin owner before merging.

**Review by sylviamoss — APPROVED** [review]
Nice!! 🎉

**Comment by maxfrei** [comment]
@nywilken lgtm 👍

**Comment by nywilken** [comment]
Thanks for the review :+1:

**Comment by nywilken** [comment]
Cherry-picking onto stable-website.

**Pull request merged**
