### PR TITLE
fix: set openstack metadata for use_blockstorage_volume

### LINKED ISSUE #7721: openstack image metadata not availabe for with use_blockstorage_volume
packer version 1.4.1

when setting [metadata](https://www.packer.io/docs/builders/openstack.html#metadata) for the openstack builder and setting [use_blockstorage_volume](https://www.packer.io/docs/builders/openstack.html#use_blockstorage_volume) no metadata is set on the image. this happens due to the following if else statement https://github.com/hashicorp/packer/blob/master/builder/openstack/step_create_image.go#L48
where the image metadata is only provided to `servers.CreateImage`, but not to `volumeactions.UploadImage`

### LINKED ISSUE #8009: openstack packer provisioner with volume fails with error on ceph backend
There appears to be a regression.

I am using packer openstack builder with the following configuration:

```
  "builders": [
    {
    "type": "openstack",
    "domain_name": "Default",
    "networks": ["{{ user `openstack_provider_network_id`}}"],
    "region": "regionOne",
    "ssh_username": "centos",
    "security_groups": "packer_provisioner",
    "image_name": "{{ user `openstack_image_name`}}",
    "source_image_name": "{{ user `openstack_source_image_name`}}",
    "flavor": "packer",
    "use_blockstorage_volume": "true",
    "volume_size": 56,
    "image_disk_format": "raw"
    }
  ]
```

After successful provisioning on an openstack vm, packer attempts to convert the volume to an image. It fails. Observed behaviour with packer 1.4.3

```
==> openstack: Stopping server: a84e213c-7c5a-4b82-a54f-3c641d084d39 ...
    openstack: Waiting for server to stop: a84e213c-7c5a-4b82-a54f-3c641d084d39 ...
==> openstack: Detaching volume packer_5d5acea6-c511-ad7a-3649-145419dad7e1 (volume id: 4be153c6-0333-42a5-aa5e-4803703b06c4)
==> openstack: Waiting for volume packer_5d5acea6-c511-ad7a-3649-145419dad7e1 (volume id: 4be153c6-0333-42a5-aa5e-4803703b06c4) to become available...
==> openstack: Creating the image: redacted
==> openstack: Error setting image metadata: Bad request with: [POST https://redacted/v3/6e95f572ba4449fba97791427d25fea4/volumes/4be153c6-0333-42a5-aa5e-4803703b06c4/action], error message: {"badRequest": {"message": "Invalid volume: Updat
ing volume metadata is not allowed for volumes in uploading status.", "code": 400}}
==> openstack: Terminating the source server: a84e213c-7c5a-4b82-a54f-3c641d084d39 ...
==> openstack: Deleting volume: 4be153c6-0333-42a5-aa5e-4803703b06c4 ...
==> openstack: Deleting temporary keypair: packer_5d5acea6-8871-8905-ae16-dc92bd0b7d7e ...
Build 'openstack' errored: Error setting image metadata: Bad request with: [POST https://redacted/v3/6e95f572ba4449fba97791427d25fea4/volumes/4be153c6-0333-42a5-aa5e-4803703b06c4/action], error message: {"badRequest": {"message": "Invalid v
olume: Updating volume metadata is not allowed for volumes in uploading status.", "code": 400}}
```

Expected behaviour (observed with packer 1.3.5):

```==> openstack: Stopping server: fe32f84d-db19-4c26-b840-9eed7922d95a ...
    openstack: Waiting for server to stop: fe32f84d-db19-4c26-b840-9eed7922d95a ...
==> openstack: Detaching volume packer_5d5ad655-cc33-a139-42cf-13871c552be0 (volume id: fd98a29d-5baa-4be3-8865-f38cb128bb61)
==> openstack: Waiting for volume packer_5d5ad655-cc33-a139-42cf-13871c552be0 (volume id: fd98a29d-5baa-4be3-8865-f38cb128bb61) to become available...
==> openstack: Creating the image: redacted
    openstack: Image: 2c52db5e-d94b-4b85-b554-2d10695ae656
==> openstack: Waiting for image redacted (image id: 2c52db5e-d94b-4b85-b554-2d10695ae656) to become ready...
==> openstack: Terminating the source server: fe32f84d-db19-4c26-b840-9eed7922d95a ...
==> openstack: Deleting volume: fd98a29d-5baa-4be3-8865-f38cb128bb61 ...
==> openstack: Deleting temporary keypair: packer_5d5ad655-3417-81ec-9401-5a80d2cfb29b ...
```

I am using ceph backend for block storage. Perhaps the recent changes in this area have not been tested against ceph.

### LINKED ISSUE #8178: openstack packer builder with use_blockstorage_volume:true fails with "Updating volume metadata is not allowed for volumes in uploading status"
#### Overview of the Issue

Even a simple template to clone an image 

```
 "builders":[
	{
		"type": "openstack",
		"use_blockstorage_volume": true,
		"volume_size": 8,
		"image_visibility": "private",
		"image_disk_format": "qcow2",
		"image_name": "output_image",
		"source_image_name": "source_image",
```

is failing to save the image, after successfully completing provisioning (in this case, I simplified the template to have no provisioners at all, so it would just be launching the server and saving an image.

```
==> openstack: Stopping server: 657a2adf-80ac-4130-9863-6835d0ea3f62 ...
    openstack: Waiting for server to stop: 657a2adf-80ac-4130-9863-6835d0ea3f62 ...
==> openstack: Detaching volume packer_5d93d4ba-65b8-070b-69cb-4cb6e030d626 (volume id: 6378cd7d-6f1a-4364-aafd-b392c21fb951)
==> openstack: Waiting for volume packer_5d93d4ba-65b8-070b-69cb-4cb6e030d626 (volume id: 6378cd7d-6f1a-4364-aafd-b392c21fb951) to become available...
==> openstack: Creating the image: clone-20191001-1035
    openstack: Image: 5418aa30-ebd9-476c-bb6a-40aa52215cad
==> openstack: Waiting for image clone-20191001-1035 (image id: 5418aa30-ebd9-476c-bb6a-40aa52215cad) to become ready...
==> openstack: Error setting image metadata: Bad request with: [POST https://openstack.example.com:8776/v3/e7f1c0de3e714e15a4d1d81c19a9d483/volumes/6378cd7d-6f1a-4364-aafd-b392c21fb951/action], error message: {"badRequest": {"message": "Invalid volume: Updating volume metadata is not allowed for volumes in uploading status.", "code": 400}}
==> openstack: Provisioning step had errors: Running the cleanup provisioner, if present...
==> openstack: Terminating the source server: 657a2adf-80ac-4130-9863-6835d0ea3f62 ...
==> openstack: Deleting volume: 6378cd7d-6f1a-4364-aafd-b392c21fb951 ...
Build 'openstack' errored: Error setting image metadata: Bad request with: [POST https://openstack.example.com:8776/v3/e7f1c0de3e714e15a4d1d81c19a9d483/volumes/6378cd7d-6f1a-4364-aafd-b392c21fb951/action], error message: {"badRequest": {"message": "Invalid volume: Updating volume metadata is not allowed for volumes in uploading status.", "code": 400}}

==> Some builds didn't complete successfully and had errors:
--> openstack: Error setting image metadata: Bad request with: [POST https://openstack.example.com:8776/v3/e7f1c0de3e714e15a4d1d81c19a9d483/volumes/6378cd7d-6f1a-4364-aafd-b392c21fb951/action], error message: {"badRequest": {"message": "Invalid volume: Updating volume metadata is not allowed for volumes in uploading status.", "code": 400}}
```

This seems like the same symptoms as #8009, but 1.4.4 contains the fix from #8016 and yet the failure still occurs. Packer does seem to wait longer (packerlog.txt shows "Waiting for image creation status: ..." 25 times, first with "queued" and then with "saving", before continuing on) but evidently not quite long enough, as it still fails with

```
2019/10/01 18:10:52 ui error: ==> openstack: Error setting image metadata: Bad request with: [POST https://openstack.example.com:8776/v3/e7f1c0de3e714e15a4d1d81c19a9d483/volumes/ad603640-82eb-48d3-8e92-914361816e25/action], error message: {"badRequest": {"message": "Invalid volume: Updating volume metadata is not allowed for volumes in uploading status.", "code": 400}}
```

#### Reproduction Steps

packer build [clone.packer.json.txt](https://github.com/hashicorp/packer/files/3678808/clone.packer.json.txt)

### Packer version

1.4.4

### Operating system and Environment details

Windows 10 amd64 
also reproduced on ubuntu 16.04 amd64

### Log Fragments and crash.log files

[packerlog.txt](https://github.com/hashicorp/packer/files/3678809/packerlog.txt)

### PR DESCRIPTION
**Pull request by puetzk**
Also set os-set_image_metadata on the tempoary volume before uploading
(volume metadata does not automatically become image metadata)
so the uploaded image will be created with the desired metadata

This avoids the race condition identified by #8178, and achieves the goal of #7792 (which did not actually work as intended even when that race did not cause an outright failure, since setting image metadata on a volume *after* upload doesn't change the already-uploaded image.

Fixes #8178
Fixes #8009
Fixes #7721

### CODE REVIEW

**Comment by puetzk** [comment]
I had missed that there would be a CLA with terms beyond the MPL license when filing this for my employer's contribution approval process. I'm waiting on the OSS governance team to review it...

**Comment by SwampDragons** [comment]
Sounds good. If your governance team have any questions, they can send them to legal at hashicorp dot com.

**Comment by puetzk** [comment]
Thanks. It's generally a pretty routine process, and I didn't spot anything that looked like a red flag. to me. Just not always immediate, and the main contact is traveling this week. So I commented to explain why I hadn't accepted the CLA yet.

What do you want me to do about the conflict with 0bd256326fb5aebf98c98682c13ba0a4d16a1c16 that was just introduced (my change already addressed that problem too since it move everything back inside) `if s.UseBlockStorageVolume`. Will you just accept my side (deleting the hunk that was changed), do you want add a merge from master into my branch, or something else? I'd somewhat prefer not to rebase the actual commit since I'm (temporarily) going to be running a build from this branch (i.e. 1.4.4. + this one fix), and I'd like there to keep a commit for the code we're actually running. Though I guess I can always have an original and a -rebased branch or something if I really have to.

**Comment by SwampDragons** [comment]
We're not super picky about how to resolve conflicts; I'd be happy for you to either merge master into your branch to resolve the conflict or make a new PR from a different branch so that we don't mess with your commit.

**Comment by puetzk** [comment]
Ok. Some projects are picky on "always rebase" vs "never force push", etc. I will merge master in and resolve any conflicts to get this ready for merge whenr the CLA is cleared.

**Comment by sdemura** [comment]
What is left to get this merged? I've been running into this exact issue.

**Comment by SwampDragons** [comment]
@sdemura Sorry, we can't merge until the contributor has signed the CLA and resolved conflicts. It sounds like they're waiting for internal permission to sign the CLA, so hopefully we will be able to merge soon.

**Comment by puetzk** [comment]
Sorry for the long delay, finally got the CLA approved last week and hadn't gotten back to this to merge the conflict yet.

**Comment by puetzk** [comment]
I don't really see how my patch could have anything to do with the amazon/ebs or azure diffs that check-generate flagged. Presumably that's just out of sync on master already?

**Pull request merged**
