### PR TITLE
Fix facterVar separator bug reported in #5338

### LINKED ISSUE #5338: [1.1.0] Packer + Puppet Masterless on Windows
First time I try the puppet-masterless provisioner with puppet on a windows guest os but it does not show the puppet error output and difficult to know what happened.

**PACKER_LOG**

```shell
    virtualbox-iso: Running Puppet: cd C:/Windows/Temp/packer-puppet-masterless && SET "FACTER_packer_builder_type=virtualbox-iso" & SET "FACTER_packer_build_name=virtualbox-iso" & && puppet apply --verbose --modulepath='C:/Windows/Temp/packer-puppet-masterless/module-0' --hiera_config='C:/Windows/Temp/packer-puppet-masterless/hiera.yaml' --detailed-exitcodes C:/Windows/Temp/packer-puppet-masterless/manifests/site.pp
2017/09/13 15:53:54 ui:     virtualbox-iso: Running Puppet: cd C:/Windows/Temp/packer-puppet-masterless && SET "FACTER_packer_builder_type=virtualbox-iso" & SET "FACTER_packer_build_name=virtualbox-iso" & && puppet apply --verbose --modulepath='C:/Windows/Temp/packer-puppet-masterless/module-0' --hiera_config='C:/Windows/Temp/packer-puppet-masterless/hiera.yaml' --detailed-exitcodes C:/Windows/Temp/packer-puppet-masterless/manifests/site.pp
2017/09/13 15:53:54 packer: 2017/09/13 15:53:54 [INFO] starting remote command: cd C:/Windows/Temp/packer-puppet-masterless && SET "FACTER_packer_builder_type=virtualbox-iso" & SET "FACTER_packer_build_name=virtualbox-iso" & && puppet apply --verbose --modulepath='C:/Windows/Temp/packer-puppet-masterless/module-0' --hiera_config='C:/Windows/Temp/packer-puppet-masterless/hiera.yaml' --detailed-exitcodes C:/Windows/Temp/packer-puppet-masterless/manifests/site.pp
2017/09/13 15:53:54 packer: 2017/09/13 15:53:54 [INFO] command 'cd C:/Windows/Temp/packer-puppet-masterless && SET "FACTER_packer_builder_type=virtualbox-iso" & SET "FACTER_packer_build_name=virtualbox-iso" & && puppet apply --verbose --modulepath='C:/Windows/Temp/packer-puppet-masterless/module-0' --hiera_config='C:/Windows/Temp/packer-puppet-masterless/hiera.yaml' --detailed-exitcodes C:/Windows/Temp/packer-puppet-masterless/manifests/site.pp' exited with code: 1
2017/09/13 15:53:54 packer: 2017/09/13 15:53:54 [INFO] RPC endpoint: Communicator ended with: 1
2017/09/13 15:53:54 [INFO] 0 bytes written for 'stdout'
2017/09/13 15:53:54 [INFO] 33 bytes written for 'stderr'
2017/09/13 15:53:54 [INFO] RPC client: Communicator ended with: 1
2017/09/13 15:53:54 [INFO] RPC endpoint: Communicator ended with: 1
    virtualbox-iso: && was unexpected at this time.
2017/09/13 15:53:54 ui:     virtualbox-iso: && was unexpected at this time.
2017/09/13 15:53:54 packer: 2017/09/13 15:53:54 [INFO] 0 bytes written for 'stdout'
2017/09/13 15:53:54 packer: 2017/09/13 15:53:54 [INFO] 33 bytes written for 'stderr'
2017/09/13 15:53:54 packer: 2017/09/13 15:53:54 [INFO] RPC client: Communicator ended with: 1
2017/09/13 15:53:54 [INFO] (telemetry) ending puppet-masterless
2017/09/13 15:53:54 [INFO] (telemetry) found error: Puppet exited with a non-zero exit status: 1
2017/09/13 15:53:54 packer: 2017/09/13 15:53:54 Executing VBoxManage: []string{"controlvm", "win2012r2-virtualbox", "poweroff"}
2017/09/13 15:53:55 packer: 2017/09/13 15:53:55 stdout:
2017/09/13 15:53:55 packer: 2017/09/13 15:53:55 stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2017/09/13 15:53:55 packer: 2017/09/13 15:53:55 Executing VBoxManage: []string{"storageattach", "win2012r2-virtualbox", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--medium", "none"}
2017/09/13 15:53:55 packer: 2017/09/13 15:53:55 stdout:
2017/09/13 15:53:55 packer: 2017/09/13 15:53:55 stderr:
2017/09/13 15:53:55 packer: 2017/09/13 15:53:55 Executing VBoxManage: []string{"storageattach", "win2012r2-virtualbox", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--medium", "none"}
2017/09/13 15:53:55 packer: 2017/09/13 15:53:55 stdout:
2017/09/13 15:53:55 packer: 2017/09/13 15:53:55 stderr:
2017/09/13 15:53:55 ui: ==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Unregistering and deleting virtual machine...
2017/09/13 15:53:55 packer: 2017/09/13 15:53:55 Executing VBoxManage: []string{"unregistervm", "win2012r2-virtualbox", "--delete"}
2017/09/13 15:53:56 packer: 2017/09/13 15:53:56 stdout:
2017/09/13 15:53:56 packer: 2017/09/13 15:53:56 stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2017/09/13 15:53:56 packer: 2017/09/13 15:53:56 Deleting floppy disk: /tmp/packer204111736
==> virtualbox-iso: Deleting output directory...
2017/09/13 15:53:56 ui: ==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Puppet exited with a non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Puppet exited with a non-zero exit status: 1

==> Builds finished but no artifacts were created.
2017/09/13 15:53:56 [INFO] (telemetry) ending virtualbox-iso
2017/09/13 15:53:56 [INFO] (telemetry) found error: Puppet exited with a non-zero exit status: 1
2017/09/13 15:53:56 ui error: Build 'virtualbox-iso' errored: Puppet exited with a non-zero exit status: 1
2017/09/13 15:53:56 Builds completed. Waiting on interrupt barrier...
2017/09/13 15:53:56 machine readable: error-count []string{"1"}
2017/09/13 15:53:56 ui error: 
==> Some builds didn't complete successfully and had errors:
2017/09/13 15:53:56 machine readable: virtualbox-iso,error []string{"Puppet exited with a non-zero exit status: 1"}
2017/09/13 15:53:56 ui error: --> virtualbox-iso: Puppet exited with a non-zero exit status: 1
2017/09/13 15:53:56 ui: 
==> Builds finished but no artifacts were created.
2017/09/13 15:53:56 waiting for all plugin processes to complete...
2017/09/13 15:53:56 /usr/local/bin/packer: plugin process exited
2017/09/13 15:53:56 /usr/local/bin/packer: plugin process exited
2017/09/13 15:53:56 /usr/local/bin/packer: plugin process exited
2017/09/13 15:53:56 /usr/local/bin/packer: plugin process exited
2017/09/13 15:53:56 /usr/local/bin/packer: plugin process exited
2017/09/13 15:53:56 /usr/local/bin/packer: plugin process exited
2017/09/13 15:53:56 /usr/local/bin/packer: plugin process exited
2017/09/13 15:53:56 /usr/local/bin/packer: plugin process exited
2017/09/13 15:53:56 /usr/local/bin/packer: plugin process exited
```

### PR DESCRIPTION
**Pull request by c22**
Untested, closes #5338

### CODE REVIEW

**Comment by c22** [comment]
Perhaps also worth mentioning that the same bug reported in #5338 for puppet-masterless also exists in puppet-serve. Both ares fixed with this PR.

**Comment by dimas-scilearn** [comment]
If it helps, I've tested this on one of my builds (windows2012, puppet masterless) and it works great!

**Comment by lmayorga1980** [comment]
Fixed in my Windows 2016 Packer Build with this PR. 🎉 🎈

**Comment by mwhooker** [comment]
👍

**Pull request merged**
