### PR TITLE
Add flag to skip cleaning up unnecessary VMware files.

### PR DESCRIPTION
**Pull request by natalieparellano**
We would like to download files as part of the build, but
they get deleted at the end because they do not end in
".nvram", ".vmdk", ".vmsd", ".vmx", or ".vmxf".

### CODE REVIEW

**Comment by mwhooker** [comment]
Could you describe your use case in a bit more detail? I want to understand a bit better what types of files are being downloaded and where you expect them to be saved

**Comment by natalieparellano** [comment]
We are trying to implement download functionality for the winrm communicator (this would be a separate PR, but we are awaiting the acceptance of https://github.com/masterzen/winrm/pull/67). We would like to download the files to our packer artifact [output directory](https://www.packer.io/docs/builders/vmware-vmx.html#output_directory).

**Comment by mwhooker** [comment]
Like when building on a remote server?

**Comment by natalieparellano** [comment]
It could be either. In our case, we're using packer to spin up a vm in Fusion/Workstation on our local machine, run some provisioners, and get the output. We tried implementing this solely through parsing packer stdout logs but there appears to be a limit to the total size of the output.

**Comment by aminjam** [comment]
@mwhooker Would it make sense if we pushed another commit to this PR that enables download for winrm or would you prefer getting a separate PR for that? Ideally we would like to have the following:

```json
{
  "type": "file",
  "source": "C:\\hello.txt",
   "destination": "hello.txt",
  "directtion": "download"
}
```
Currently this PR will allow the `hello.txt` to remain after `packer` finishes, but it doesn't have the download functionality yet.

**Comment by mwhooker** [comment]
@aminjam 

> @mwhooker Would it make sense if we pushed another commit to this PR that enables download for winrm or would you prefer getting a separate PR for that? Ideally we would like to have the following:

I think it would make sense as a separate PR

The file provisioner would run while the guest is still up, though. Wouldn't that mean you don't need to skip cleanup?

**Comment by aminjam** [comment]
Correct. The file is downloaded correctly, but the cleanup removes any file that's not needed by `vmware-vmx` after packer finished successfully.

**Comment by pnikonowicz** [comment]
@mwhooker just fixed conflicts and is ready to be merged again

**Comment by pnikonowicz** [comment]
Should we fix these tests before the PR can be merged?

**Comment by mwhooker** [comment]
I still don't understand this PR to be honest.

**Comment by aminjam** [comment]
@mwhooker I agree. The `skip_clean_files` feature is a bit confusing, but it's only valuable in the context of having the [Download WinRM](https://github.com/hashicorp/packer/pull/4748) and if it's downloaded to the current working directory. Let's get the Download WinRM PR merged then we can come back to this PR and re-evaluate it.

**Comment by SwampDragons** [comment]
I'm closing because this PR is over a year old and it sounds like there was a controversy to begin with. If someone wants to resolve conflicts and reopen with a compelling argument as to why it should be merged, I'll reconsider.

**Pull request closed without merging**
