### PR TITLE
hyperv: always set MacSpoofing and VirtualizationExtensions preferences.

### PR DESCRIPTION
**Pull request by mwhooker**
more fixes found in #4880 

cc @batzen 

@taliesins any reason not to merge?

### CODE REVIEW

**Comment by batzen** [comment]
Merging this will cause packer to fail on systems other than the latest windows 10 or windows 2016. There needs to be some kind of feature support check.

**Comment by mwhooker** [comment]
@batzen thanks for the check. You're saying the similar change in #5363 won't have that effect, or will it?

**Comment by batzen** [comment]
Dynamic memory is supported since Windows Server 2008 R2 Service Pack 1 (SP1) and is available in powershell since Set-VMMemory exists, as far as i could find, so i guess there is no check needed for dynamic memory.

**Comment by mwhooker** [comment]
Thanks for that. I will close this until someone requests support

**Pull request closed without merging**
