### PR TITLE
Add vagrant post-processor support for Google

### PR DESCRIPTION
**Pull request by seanmalloy**
Add the ability to create Google vagrant boxes
using the vagrant post-processor. The Google
plugin for vagrant is linked below.

https://github.com/mitchellh/vagrant-google

### CODE REVIEW

**Comment by seanmalloy** [comment]
I did not create any tests yet. I'm hoping to create the tests in the next few days.

**Comment by seanmalloy** [comment]
I pushed up the unit tests for this change. It looks like they are all passing.

I still need to do some real testing to verify that this is working correctly. Hoping to do that in the next few days.

**Comment by seanmalloy** [comment]
I was able to successfully test this, and from my perspective it is working. Any feedback on this PR would be greatly appreciated.

My example packer config used to generate the vagrant box.
```
{
  "builders": [
    {
      "type": "googlecompute",
      "account_file": "/path/to/gcp.json",
      "project_id": "seanm-test-kitchen",
      "source_image": "centos-7-v20171213",
      "zone": "us-central1-a",
      "ssh_username": "packer",
      "preemptible": "true"
    }
  ],
  "post-processors": [
    {
      "type": "vagrant"
    }
  ]
}
```

Example Vagrantfile used for testing.
```
Vagrant.configure("2") do |config|
  config.vm.box = "gce-demo"

  config.vm.provider :google do |google, override|
    google.google_project_id        = "seanm-test-kitchen"
    google.google_client_email      = "packer@seanm-test-kitchen.iam.gserviceaccount.com"
    google.google_json_key_location = "/tmp/gcp.json"

    override.ssh.username = "foobar"
    override.ssh.private_key_path = "~/.ssh/id_rsa"
  end
end
```

Vagrant commands used to test. These all work as expected.
```
vagrant box add --name gce-demo /tmp/packer_googlecompute_google.box
vagrant up
vagrant ssh
vagrant destroy
```

**Comment by seanmalloy** [comment]
It looks like this PR has been added to the v1.2.0 milestone, and currently the v1.1.4 milestone will be the next release. I'm more that happy to wait for the v1.2.0 release before having this merged.

Any feedback on this PR would be appreciated while we wait for the v1.1.4 release to be completed.

**Comment by SwampDragons** [comment]
We have a couple of critical bugs and regressions we need to fix before we put much more time into reviewing community PRs, which is why I scheduled it for the following release;  I'm afraid it'll be a bit before I get a chance to look this over thoroughly.

**Comment by SwampDragons** [comment]
Thanks for this contribution!

**Pull request merged**
