### PR TITLE
try to retype key if an error is received

### LINKED ISSUE #8957: vsphere-iso builder "boot_command" causes "invalid fault" in vSphere
#### Overview of the Issue

Almost every time I try to build a new vSphere VM using the Ubuntu Server installer, it fails shortly after inputting the boot command. This is similar to what is described in https://github.com/jetbrains-infra/packer-builder-vsphere/issues/63. The error probably a little different due to running vCenter 6.7u3 and vSphere 6.7u3. Packer version is 1.5.4. Here is the Packer build output.

```
$ packer build ubuntu_18.04.3_http.json
vsphere-iso: output will be in this color.

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mounting ISO images...
==> vsphere-iso: Starting HTTP server on port 8185
==> vsphere-iso: Set boot order...
==> vsphere-iso: Power on VM...
==> vsphere-iso: Waiting 10s for boot...
==> vsphere-iso: HTTP server is working at http://x.x.x.x:8185/
==> vsphere-iso: Typing boot command...
==> vsphere-iso: Power off VM...
==> vsphere-iso: The attempted operation cannot be performed in the current state (Powered on).
==> vsphere-iso: Destroying VM...
==> vsphere-iso: The attempted operation cannot be performed in the current state (Powered on).
Build 'vsphere-iso' errored: error typing a boot command: ServerFaultCode: A general system error occurred: Invalid fault

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: error typing a boot command: ServerFaultCode: A general system error occurred: Invalid fault

==> Builds finished but no artifacts were created.
```

### Simplified Packer Buildfile

```
{
  "builders": [
  {
    "type": "vsphere-iso",

    "vcenter_server": "{{user `vcenter_host`}}",
    "username": "{{user `vsphere_username`}}",
    "password": "{{user `vsphere_password`}}",
    "insecure_connection": "true",
    "cluster": "{{user `cluster`}}",
    "host": "{{user `vmw-01`}}",

    "vm_name": "packer-test",
    "guest_os_type": "ubuntu64guest",
    "CPUs": 2,
    "cpu_cores": 2,
    "RAM": 4096,

    "disk_controller_type": "pvscsi",
    "disk_size": "102400",
    "disk_thin_provisioned": "true",

    "network_card": "vmxnet3",
    "network": "{{user `network`}}",

    "boot_order": "disk,cdrom",
    "boot_wait": "10s",
    "convert_to_template": "false",

    "ssh_username": "{{user `ssh_username`}}",
    "ssh_password": "{{user `ssh_password`}}",
    "ssh_timeout": "15m",

    "iso_paths": [
    	"[{{user `vmw-01_datastore`}}] Images/Linux/ubuntu-18.04.3-live-server-amd64.iso"
    ],
    "http_directory": "http",
    "boot_command": [
        "<enter><enter><wait3><f6><wait3><esc><wait3>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs>",
        "/install/vmlinuz noapic ",
        "boot=casper ",
        "initrd=/casper/initrd ",
        "preseed/url=http://{{.HTTPIP}}:{{.HTTPPort}}/preseed.cfg ",
        "debian-installer=en_US auto locale=en_US kbd-chooser/method=us ",
        "grub-installer/bootdev=/dev/sda<wait> ",
        "fb=false debconf/frontend=noninteractive ",
        "-- <enter>"
    ]
  }]
}
```

### Log Fragments and crash.log files

https://gist.github.com/rmetschke/55bef5ef4b2002238ec32b290318b3ca

### PR DESCRIPTION
**Pull request by jhawk28**
checking to see if retyping the key works around #8957

Closes #8957

### CODE REVIEW

**Review by sylviamoss — COMMENTED** [review]
Nice! Hope that works 👍🏼

**Comment by SwampDragons** [comment]
This is still labeled as a WIP -- did it work?

**Comment by jhawk28** [comment]
I can't reproduce the issue in my environment and I haven't gotten a response from those who do.

**Comment by sylviamoss** [comment]
If this is the fix, it will always retype for an error different from the one that's being fixed. I think that's ok. What do you think? 
I'm asking this because maybe we can merge this PR as the output will be the same fixing the issue or not. 

Why did you think retyping would fix the issue?

**Comment by jhawk28** [comment]
The logging output will show if it tries to "retype" a key. I thought that a "retype" would work around the issue because it seemed to be an intermittent connection issue. One possible side effect that could make it worse is if the original keystroke went through, but it returned an error. This would result in a duplicate key.

**Comment by sylviamoss** [comment]
I was thinking about this one and if the keystroke returns an error even when typed successfully, the build will fail anyways and the image built so far will be removed (if not aborted). I think we should merge this and give a chance to fix the issue instead of waiting for someone to test it.

**Comment by azr** [comment]
That sounds good to me too !

**Pull request merged**
