### PR TITLE
Fix #1942, #2461 - Interpolation of nested variables

### LINKED ISSUE #1942: Interpolate user variables within other user variables
packer version:  0.7.2

Packer doesn't allow variables to be interpolated into other variables.  

This would be helpful when I want to switch to a different version of RHEL for instance, so I could do something like the following: 

```
  "variables": {
    "iso_url": "http://myserver/ISOs/rhel-server-{{ user `rhel_version`}}-x86_64-dvd.iso",
    "iso_checksum": "d717af33dd258945e6304f9955487017",
    "rhel_version": "6.3",
  },
```

Then via command line just pass in `rhel_version`. 

The only way of getting around this that I can think of now would be to split up the  iso_url field into 3 parts, and use the 3 parts everywhere..    which is a little messy.

### LINKED ISSUE #2461: HTTPIP and HHTPORT do not get evaluated  when using virtualbox
Hi,

I am using packer to create a CentOS image for virtualbox, the variable HTTPIP and HTTPPort do not get evaluated. When anaconda receives the boot command, it is showing 
ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg
and the installation continues as manual and not using kickstart.

The issue  seems to be present in packer 8.0 and 8.1. I reverted back to version 7.5 and problem is not present. 
workspace 1_063

I have run packer with PACKER_LOG=1 enabled and saved the output, please let me know where to upload.

### PR DESCRIPTION
**Pull request by fuhbar**
Switch behaviour of variable interpolation from single to multiple
rounded. This enables the substitution of nested variables.

This commit fixes #1942 and fixes #2461

### CODE REVIEW

**Comment by tylert** [comment]
I just attempted to apply this fix on top of commit id 344ed08 (current master HEAD).  It built correctly but doesn't seem to work as advertised in https://github.com/mitchellh/packer/issues/1942.  The expanded strings are all empty.

**Comment by somegithubuser** [comment]
@tylert This commit worked for me. However, I had to be very particular about where vars lived when having a var-file.

```
{
  "MIRROR": "<REDACTED>",
  "KS": "cent7.cfg",
  "SSHPORT": "5022",
  "KSPRIVOPTS": "mirror={{user `MIRROR`}} ssh={{user `SSHPORT`}}",
  "KSCMD": "ks={{user `MIRROR`}}/{{user `KS`}}"
}
```
and
```
{
  "variables": {
    "KSOPTS": "biosdevname=0 net.ifnames=0",
    "KSPRIVOPTS": null,
    "DISKSIZE": "8192"
  },
  "builders": [{
    "type": "virtualbox-iso",
<..>
    "boot_command": [
      "<up><tab> {{user `KSCMD`}}",
      " {{user `KSOPTS`}}",
      " {{user `KSPRIVOPTS`}}"
    ],
<..>
```

If I moved KSCMD to the variables section, it returned empty, presumably because it was being evaluated prior to everything in the var-file. I'm going to continue playing around with ordering, especially with the order of multiple `-var-file` options since the goal is to have a set of files that have absolutely nothing in them but that which will differ between them and then all the other files can be boilerplate.

**Comment by somegithubuser** [comment]
This commit seems to only handle nested vars in `-var-file`, not for `variables{}` vars. From within `variables{}` you cannot reference another variable regardless of order and regardless whether the referent is in `variables{}` or `-var-file`.

However, from within `-var-file` you can reference `variables{}` vars or `-var-file` vars (regardless of order).

I have what I believe to be a complete test case here:
https://gist.github.com/somegithubuser/073a47f60584060d4953147b4ec762c6

**Comment by SwampDragons** [comment]
Closing because this seems somewhat brittle and there's been no activity on it for over a year and a half. If someone wants to take a stab at a more robust version of this, feel free to open a new PR :D

**Pull request closed without merging**
