### PR TITLE
Remove the VC product line

### PR DESCRIPTION
**Pull request by sieben**
Scaleway VC product line is replaced with the START1 product line.

### CODE REVIEW

**Comment by SwampDragons** [comment]
Does this have any backwards-compatibility implications?

**Comment by SwampDragons** [comment]
I guess I should have actually read the PR before asking that. This is tests and docs update, not a behavior change.  IGNORE ME!  😆

**Comment by SwampDragons** [comment]
based on https://www.scaleway.com/faq/servers/ It doesn't look like the VC product line has been deprecated; what is the motivation for this change?  (forgive me; I'm no scaleway expert)

**Comment by dimtion** [comment]
Hi @SwampDragons,

The VC product line was replaced by the START1-*, this change is accompanied with a boost in performances, and new features. You can have more details in the following blog post: https://blog.online.net/2018/05/03/introducing-scaleway-nextgen-nvme-cloud-servers-with-hot-snapshots/

The change should not have any backward compatible change as the old instances can be upgraded to the new ones.

**Comment by SwampDragons** [comment]
@dimtion sounds good to me! Thanks for the explanation!

**Pull request merged**
