### PR TITLE
Packer builder profitbricks updates

### PR DESCRIPTION
**Pull request by alibazlamit**
This PR adds the ability to user ProfitBricks image aliases feature, users now  can provide any of the ProfitBricks available image aliases in the config.json as the image parameter i.e `ubuntu:latest` will install the latest Ubuntu version.
Alongside updating the `vendors.js` It also updates the version of the go SDK to v4 to be able to access the image alias feature

### CODE REVIEW

**Comment by mwhooker** [comment]
going to let @jasmingacic review and merge this. If you don't hear back in a few weeks, feel free to @-ping me and I'll merge

**Comment by mwhooker** [comment]
are there any updates to the docs that need to happen? i.e. does this change how users interact with the builder?

**Comment by jasmingacic** [comment]
@alibazlamit Maybe it is worth mentioning what values can be used for volume images? Since image alias are used like `ubuntu:latest` instead of ubuntu-16.04. Can you update the docs to reflect this change.

**Comment by jasmingacic** [comment]
@mwhooker Is the failing test in AppVeyor blocking this merge?

**Comment by jasmingacic** [comment]
@alibazlamit Disregard my previous comment. No need to do that the image parameter will accept both old and new values.

**Comment by jasmingacic** [comment]
@mwhooker what's next?

**Comment by jasmingacic** [comment]
@mwhooker Should I merge this?

**Comment by jasmingacic** [comment]
@alibazlamit Thanks for your contribution.

**Comment by mwhooker** [comment]
@jasmingacic yeah feel free to merge these in the future

**Pull request merged**
