### PR TITLE
dont set the host for the datastore upload

### LINKED ISSUE #9076: vsphere-iso doesn't respect no_proxy when sending floppy_files to vsphere server
#### Overview of the Issue

When using vsphere-iso on a system with proxy vars defined, and using the floppy_files directive, the upload of the floppy file image to the vsphere server does not respect the no_proxy setting.

#### Reproduction Steps

* Have a corporate proxy server that will respond with a 403 page when you try to access an invalid web page.
* Have http_proxy, https_proxy, and no_proxy defined appropriately for that proxy server.  For example on a windows machine:
set https_proxy=http://myproxy.mycompany.com:8080
set http_proxy=http://myproxy.mycompany.com:8080
set no_proxy=127.0.0.1,localhost,.local,.mycompany.com
* Specify packer config for vsphere-iso, including floppy_files to send to vsphere (example below)
* Results:
```
D:\Work\packer-test-1-vsphere>packer build -on-error=ask -only=vsphere-iso centos.json
vsphere-iso: output will be in this color.

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mounting ISO images...
==> vsphere-iso: Creating floppy disk...
    vsphere-iso: Copying files flatly from floppy_files
    vsphere-iso: Copying file: D:\Work\packer-test-1-vsphere/http/ks.cfg
    vsphere-iso: Done copying files from floppy_files
    vsphere-iso: Collecting paths from floppy_dirs
    vsphere-iso: Resulting paths from floppy_dirs : []
    vsphere-iso: Done copying paths from floppy_dirs
==> vsphere-iso: Uploading created floppy image
==> vsphere-iso: 403 URLBlockedInternalResource
==> vsphere-iso: Step "StepAddFloppy" failed
==> vsphere-iso: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
```

The ```403 URLBlockedInternalResource``` is being returned by our corporate proxy server, however packer should not have contacted the proxy server because the target is ```myvcenter.mycompany.com``` and no_proxy contains ```.mycompany.com```.

### Packer version

1.5.5

### Simplified Packer Buildfile

```
{
  "min_packer_version": "1.5.5",
  "_comment": "Incomplete example",
  "variables": {
    "vsphere_user": "myuser1",
    "vsphere_pass": "mypass1",
    "ssh_user": "myuser2",
    "ssh_pass": "mypass2"
  },
  "builders": [
    {
      "type": "vsphere-iso",
      "vcenter_server": "myvcenter.mycompany.com",
      "username": "{{user `vsphere_user`}}",
      "password": "{{user `vsphere_pass`}}",
      "insecure_connection": "true",
      "datacenter": "mydatacenter",
      "cluster": "mycluster",
      "resource_pool": "mypool",
      "host": "myesxhost01.mycompany.com",
      "folder": "Parent/Folder",
      "datastore": "vsan01",
      "network": "mynetwork01",
      "vm_name": "packer-test-1",
      "guest_os_type": "centos7_64Guest",
      "cpus": "2",
      "ram": 2048,
      "disk_size": "50000",
      "disk_thin_provisioned": true,
      "network_card": "vmxnet3",
      "boot_command": [
        "<up><wait><tab> text ks=hd:/dev/fd0:ks.cfg<enter><wait>"
      ],
      "boot_wait": "8s",
      "floppy_files": [
        "{{template_dir}}/http/ks.cfg"
      ],
      "iso_checksum": "9bba3da2876cb9fcf6c28fb636bcbd01832fe6d84cd7445fa58e44e569b3b4fe",
      "iso_checksum_type": "sha256",
      "iso_paths": [
        "[mydatastore] ISOs/CentOS-7-x86_64-DVD-1908.iso"
      ],
      "shutdown_command": "echo '{{user `ssh_pass`}}' | sudo -S /sbin/halt -h -p",
      "ssh_port": 22,
      "ssh_username": "{{user `ssh_user`}}",
      "ssh_password": "{{user `ssh_pass`}}",
      "ssh_timeout": "15m"
    }
  ]
}
```

### Operating system and Environment details

Packer 1.5.5 running on a Windows 10 system with proxy vars defined, trying to reach vSphere vCenter 6.5.

### Log Fragments and crash.log files

```
2020/04/15 19:13:59 ui:     vsphere-iso: Copying files flatly from floppy_files
2020/04/15 19:13:59 ui:     vsphere-iso: Copying file: D:\Work\packer-test-1-vsphere/http/ks.cfg
2020/04/15 19:13:59 ui:     vsphere-iso: Done copying files from floppy_files
2020/04/15 19:13:59 ui:     vsphere-iso: Collecting paths from floppy_dirs
2020/04/15 19:13:59 ui:     vsphere-iso: Resulting paths from floppy_dirs : []
2020/04/15 19:13:59 ui:     vsphere-iso: Done copying paths from floppy_dirs
2020/04/15 19:13:59 ui: ==> vsphere-iso: Uploading created floppy image
2020/04/15 19:14:02 ui error: ==> vsphere-iso: 403 URLBlockedInternalResource
2020/04/15 19:14:02 ui: ==> vsphere-iso: Step "StepAddFloppy" failed
2020/04/15 19:14:02 ui: ask: ==> vsphere-iso: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
( Clean up was chosen )
2020/04/15 19:17:01 packer.exe plugin: Deleting floppy disk: C:\Users\<redacted>\AppData\Local\Temp\1\packer228529739
2020/04/15 19:17:01 ui: ==> vsphere-iso: Destroying VM...
2020/04/15 19:17:02 [INFO] (telemetry) ending vsphere-iso
2020/04/15 19:17:02 ui error: Build 'vsphere-iso' errored: 403 URLBlockedInternalResource
2020/04/15 19:17:02 machine readable: error-count []string{"1"}
2020/04/15 19:17:02 ui error: 
==> Some builds didn't complete successfully and had errors:
2020/04/15 19:17:02 machine readable: vsphere-iso,error []string{"403 URLBlockedInternalResource"}
2020/04/15 19:17:02 ui error: --> vsphere-iso: 403 URLBlockedInternalResource
2020/04/15 19:17:02 ui: 
==> Builds finished but no artifacts were created.
2020/04/15 19:17:02 [INFO] (telemetry) Finalizing.
2020/04/15 19:17:04 waiting for all plugin processes to complete...
2020/04/15 19:17:04 C:\Users\<redacted>\Bin\packer.exe: plugin process exited
2020/04/15 19:17:04 C:\Users\<redacted>\Bin\packer.exe: plugin process exited
2020/04/15 19:17:04 C:\Users\<redacted>\Bin\packer.exe: plugin process exited
```

### Workaround

If we temporarily undefine the http_proxy, https_proxy, and no_proxy environment variables while calling packer, then this works.  However then no external web access is available since we are required to go through the corporate proxy to get outside.

### PR DESCRIPTION
**Pull request by jhawk28**
govc doesn't set the host. see details in #9076 if we want to merge this.

Closes #9076

### CODE REVIEW

**Comment by SwampDragons** [comment]
based on the fact that the host lookup seems to solve other cases, maybe this belongs behind a feature flag?  set_host_for_datastore_uploads or something.

**Comment by jhawk28** [comment]
so many flags...

**Comment by SwampDragons** [comment]
I know. I wish it were easier to just have reasonable defaults, but everyone's use cases are _so different_.

**Comment by SwampDragons** [comment]
Just rebased and pushed. Sorry for letting this get stale. I'll merge as soon as tests are green.

**Pull request merged**
