### PR TITLE
Amazon ebssnap post-processor

### PR DESCRIPTION
**Pull request by dnABic**
This is Packer Amazon EBS Snapshot post-processor which takes EBS Volume IDs from an artifact from ebsvolume builders and creates snapshots out of them.

My use case is the following:

I have quite some stateful services running on AWS. Therefore, I use ebs-volumes to keep service data. In case of ec2 instance loss or replacement, new instance will attach already existing ebs-volume. So, basically standard situation on AWS.

For managing infrastructure i use Terraform. It creates ec2 instances, ebs volumes and attaches volumes to the instances.

But for creating AMIs and Snapshots I use Packer. This post-processor simplifies described process and removes some workarounds when creating snapshot out of ebs volume.

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Maybe it should be named `amazon-ebssnapshot`?

**Comment by dnABic** [comment]
@rickard-von-essen Makes sense. Done.

**Comment by missinglink** [comment]
I would like to use this, how likely is it to be merged?

@dnABic there seems to be a branch conflict now, could you resolve it please?

**Comment by rickard-von-essen** [comment]
IMHO we will merge this as soon as we have time for a review. A quick glance and it looks good just need a rebase and some more information in the docs that mostly can be copy pasted from `amazon-ebs`.

**Comment by dnABic** [comment]
Yes, will do it in the next couple of days. I would need some time to get
back to this.

2017-07-21 13:01 GMT+02:00 Peter Johnson <notifications@github.com>:

**Comment by SwampDragons** [comment]
I'm going to close this due to old age. If you end up having the time to work on this some more and do the rebase and docs update, please open a new PR and we'll try to get to it within a reasonable time frame.

**Pull request closed without merging**
