### PR TITLE
amazon-chroot: Allow users to specify custom block device mapping

### PR DESCRIPTION
**Pull request by sargun**
Previously, when you built from an existing image, you were unable
to reconfigure block device mappings, as it just took them and
copied them over. This allows users to specify new, custom
block device mappings, even when building from an existing
image.

It requires that the user completely rewrites the ami_block_device_mappings,
with one specified in their packer manifest.

### CODE REVIEW

**Comment by SwampDragons** [comment]
Thanks for opening this! Can you add some notes to the chroot docs and provide an example template?

**Comment by sargun** [comment]
@SwampDragons Where should I add the example template?

**Comment by SwampDragons** [comment]
Just sharing in the PR would be fine. I just want to be able to test it out.

**Comment by sargun** [comment]
Template:


```
{
  "builders": [
    {
      "ami_name": "titus-agent-{{user `jenkins_version`}}-{{isotime `200601021504`}}--xenial-hvm-sriov-ebs",
      "type": "amazon-chroot",
      "region": "us-east-1",
      "source_ami_filter": {
        "filters": {
          "name": "${PARAVIRTUAL_IMAGE}"
        }
      },
      "ami_block_device_mappings": [
        {
          "device_name": "/dev/xvda",
          "delete_on_termination": true,
          "volume_type": "gp2"
        },
        {
          "device_name": "/dev/sdb",
          "delete_on_termination": true,
          "volume_type": "gp2",
          "volume_size": 512
        }
      ],
      "root_device_name": "/dev/xvda",
      "root_volume_size": 25,
      "root_volume_type": "gp2",
      "ami_description": "name=titus-agent, arch=x86_64, ancestor_name={{.SourceAMIName}}, ancestor_id={{.SourceAMI}}, ancestor_version={{.SourceAMITags.base_ami_version}}, version={{user `jenkins_version`}}",
      "mount_options": "commit=900,relatime",
      "ami_virtualization_type": "hvm",
      "copy_files": [],
      "ena_support": true,
      "device_path": "/dev/sdf",
      "chroot_mounts": [
         ["devpts", "devpts", "/dev/pts"],
         ["proc", "proc", "/proc"],
         ["bind", "/dev", "/dev"],
         ["sysfs", "sysfs", "/sys"],
         ["binfmt_misc", "binfmt_misc", "/proc/sys/fs/binfmt_misc"],
         ["bind", "/run/resolvconf", "/run/resolvconf"]
      ],
      "tags": {
        "creation_time": "{{isotime `2006-01-02 15:04:05 UTC`}}",
        "base_ami_version": "{{.SourceAMITags.base_ami_version}}",
        "app": "titus-agent",
        "appversion": "titus-agent-{{user `jenkins_version`}}/titus-agent/{{user `build_number_suffix`}}",
        "git_hash": "{{user `git_hash`}}",
        "git_version": "{{user `git_version`}}",
        "git_branch": "{{user `git_branch`}}",
        "expiration_time": "never"
      },
      "snapshot_tags": {},
      "mount_partition": "0",
      "pre_mount_commands": [
        "partprobe",
        "dd if=/dev/zero of={{.Device}} bs=512 count=1",
        "tune2fs -m 0 {{.Device}}",
        "fsck.ext4 -f -y {{.Device}}",
        "mkdir -p /run/resolvconf"
      ]
    }
  ],
  "provisioners": []
}
```

You have to set the machine image name to a PV image you have access to. In addition, you have to format your image in the provisioners and add a bootloader.

**Comment by sargun** [comment]
@SwampDragons I added some docs.

**Comment by SwampDragons** [comment]
This was a nice change; thanks.

**Pull request merged**
