### PR TITLE
Debug prompt between provisioner scripts

### LINKED ISSUE #1475: Debug should prompt between provisioner scripts
Using v0.6.0 at least, running with `debug` does not pause/prompt between each provisioner, but between all of them. This is really the only part of `-debug` that matters to me...

### PR DESCRIPTION
**Pull request by marema31**
Looking for implementing #4647. I found this idea, could be a first step to add the ability to prompt between each provisionner. If it's correct for you, it could be used as base to implement #4647.

Closes #1475

### CODE REVIEW

**Comment by mwhooker** [comment]
Seems good. I'll need to test a bit. Perhaps it can go in 1.1 or 1.2. 

Would like to see a unit test for this to have more confidence before merging, though

**Comment by mwhooker** [comment]
I think this is probably fine, but will have to give it more attention when I have time. This might be better implemented as a Hook, but I'm not very familiar with those

**Comment by marema31** [comment]
@mwhooker, I'm beginning in go, I'm not familiar with hooks but for me I've use the same mechanism that PausedProvisioner to allow the chain of my addition to PausedProvisioner to normal Provisionner. I was thinking it was that the concept of hook.

I've added unit tests as you asked me.

**Comment by mwhooker** [comment]
Packer has it's own notion of hooks. See here:

https://github.com/mitchellh/packer/blob/master/packer/hook.go
https://github.com/mitchellh/packer/blob/d310de8cf5871354bd1d12996a87020803d373ea/packer/provisioner.go#L30

Unfortunately I wont be able to examine this more closely for a little while. Feel free to ping me in early April when I should have more time

**Comment by SwampDragons** [comment]
I <3 this change so much!  Pushed a couple changes to resolve conflicts, and will merge for 1.3.0 if tests pass.

**Pull request merged**
