### PR TITLE
Introduces the post publish website event

### PR DESCRIPTION
**Pull request by claire-labry**
This PR introduces a new CRT workflow event in the ci.hcl file, post-publish-website and this event handles the dispatching of an API call (HTTP POST) to the mktg-dev endpoint. This is responsible for automating the triggering of marketing-dev's versioned docs pipeline to release versioned docs for product repos.

This only gets triggered as a post-publish event after you release your artifacts to production. The workflow should wait for the docs to be published and report passed/failed status.

I will merge this PR in next Monday (07/25)-- this is a new event set up so feel free to reach out in #team-rel-eng if you notice your product's documentation does not get released on the website after releasing.

Thanks!

### CODE REVIEW

**Review by nywilken — APPROVED** [review]
LGTM

**Review by sarahethompson — APPROVED** [review]

**Comment by nywilken** [comment]
@claire-labry is this good to merge?

**Comment by sarahethompson** [comment]
> 

Yes, thanks @nywilken we're merging these in today! Could you check I've applied the right backport labels? 🙇‍♀️

**Comment by nywilken** [comment]
> > 
> 
> Yes, thanks @nywilken we're merging these in today! Could you check I've applied the right backport labels? 🙇‍♀️

Sounds good @sarahethompson thanks. 

In the release/1.7.x branch we do not have any CRT configuration as we moved to CRT for the 1.8.0 release. So we can drop the `backport/1.7.x label` if I am not mistaken.

**Pull request merged**
