### PR TITLE
Format path on Windows for url.Parse call

### PR DESCRIPTION
**Pull request by avoidik**
https://github.com/hashicorp/packer/issues/5643

### CODE REVIEW

**Comment by SwampDragons** [comment]
Hi there!  I'm struggling to reproduce the issue in #5643 on master.  Are you sure https://github.com/hashicorp/packer/pull/5591 didn't already fix it?

**Comment by avoidik** [comment]
I've tried this against master today, and issue is still there. The issue is in virtualbox-ovf builder, did you used sample case from #5643?

**Comment by SwampDragons** [comment]
yeah, I did.  Must be because I'm running this in a windows vm instead of on windows hardware.  The download goes fine.  @Occams would you be willing to do a sanity check for me that this solves the problem, since I can't seem to be able to reproduce?

**Comment by avoidik** [comment]
Checked master today once again, this PR is irrelevant

**Comment by SwampDragons** [comment]
Thanks for checking this again.  If you see another issue crop up, let me know.

**Pull request closed without merging**
