### PR TITLE
Elevated support for puppet-* & chef-client provisioners

### PR DESCRIPTION
**Pull request by bodgit**
This implementation is currently very naive as  it just lifts the various bits out of the powershell provisioner however it does seem to work.

I'm not suggesting this be merged as-is, but I'm wondering how I can generalise this for all/most/some of the providers that may need to use this?

`generateElevatedRunner()` pokes about with many of the Provisioner struct members, should I create an interface with getters for all of these things or is there a another way?

### CODE REVIEW

**Comment by bodgit** [comment]
I've had a go at generalising the elevated code, how does that look? Still seems to work with my testing so far.

**Comment by SwampDragons** [comment]
Thanks for this code! I'm in the middle of a couple of other things at the moment and probably won't get a chance to fully review/merge until next week, but at a glance it looks good.  

I'm not a puppet guru though; any chance you could help me test by giving me a sample template?

**Comment by bodgit** [comment]
I've updated the `puppet-masterless` provisioner with the same changes and also refactored the original `powershell` provisioner in terms of the shared code. @lfarnell if you want to give the masterless changes a try it should hopefully fix your original problem from #5478.

**Comment by lfarnell** [comment]
@bodgit thanks for the heads up! I can test over the weekend and see if that fixes things for me. The project I used packer for is in maintenance mode but I still give it a go and see how everything works :)

**Comment by bodgit** [comment]
@SwampDragons for a sample template, it's a bit tricky as the `puppet-server` provisioner will require existing Puppet infrastructure. The `puppet-masterless` provisioner should be straightforward as that's standalone but I'm not sure the easiest way for you to get a Windows AMI with the Puppet agent baked in; my environment is completely internal. For the test Puppet manifest, the following should be sufficient saved to a `.pp` file:
```puppet
$filename = $::kernel ? {
  'Windows' => 'c:/test.txt',
  default   => '/test',
}

file { $filename:
  ensure  => file,
  content => "Packer test\n",
}
```
It's a bit hard to come up with something that _requires_ the elevated account as that tends to be something complicated like installing SQLServer or requiring an AD domain, etc. but the above should at least run.

**Comment by SwampDragons** [comment]
@bodgit thanks I can probably work with that 😄

**Comment by SwampDragons** [comment]
@lfarnell any chance you were able to test this out? a real use case is always better validation that a toy repro.

**Comment by lfarnell** [comment]
@SwampDragons If you can give me a day or two I should be able to try a legitimate install with SQL Server and see how it goes?

**Comment by lfarnell** [comment]
@bodgit @SwampDragons Would someone be able to drop a Windows binary for this PR so that I can save some time setting up a golang environment? Thanks! 😊

**Comment by bodgit** [comment]
I'm building on Linux but I've managed to get cross-compilation working however I don't have anywhere to easily host it from that won't violate my employers network access policy. I can possibly upload it somewhere though?

**Comment by azr** [comment]
You can upload it to github using drag'n' drop.


Here's a bunch of binaries from this PR :

[packer_windows_amd64.zip](https://github.com/hashicorp/packer/files/2667985/packer_windows_amd64.zip)
[packer_darwin_amd64.zip](https://github.com/hashicorp/packer/files/2667955/packer_darwin_amd64.zip)
[packer_darwin_amd64.zip](https://github.com/hashicorp/packer/files/2667980/packer_darwin_amd64.zip)

**Comment by bodgit** [comment]
That never occurred to me!

**Comment by lfarnell** [comment]
So I have been trying to get the installation to fail for the last 5 hours and haven't been able too. These are the configs I used. I didnt have to use the elevated user and password, it worked without.

packer config
```json
{
    "builders": [
        {
            "type": "null",
            "communicator": "winrm",
            "winrm_host": "192.168.203.205",
            "winrm_insecure": false,
            "winrm_username": "Administrator",
            "winrm_password": "Password1"
        }
    ],
    "provisioners": [
        {
            "type": "puppet-masterless",
            "manifest_file": "./site.pp",
            "guest_os_type": "windows"
        }
    ]
}
```
site.pp
```puppet
windowsfeature { 'Web-WebServer':
  ensure                 => present,
  installmanagementtools => true,
}

windowsfeature { 'Net-Framework-45-Core':
  ensure                 => present,
}

dsc_sqlsetup {'InstallDefaultInstance':
    dsc_instancename        => 'MSSQLSERVER',
    dsc_features            => 'SQLENGINE',
    dsc_sourcepath          => 'E:/',
    dsc_sqlsysadminaccounts => ['Administrators'],
    dsc_updateenabled       =>  'false',
}
```

Not sure what else to try.

**Comment by SwampDragons** [comment]
@lfarnell ah well, thanks for trying.

**Comment by SwampDragons** [comment]
Just a  review update; I like what you've done with the elevated provisioner interface, and the code looks good to me. So far I've validated that the elevated powershell provisioner performs the same, which is my primary concern. I didn't get a chance to run a test against the puppet provisioner, but I intend to do so tomorrow.

**Pull request merged**
