### PR TITLE
Adding a configuration settings  for the floppy label

### PR DESCRIPTION
**Pull request by i-fimafeng**
### Background 

Cloud-init (https://cloud-init.io/) offer tools for early initialization of cloud instances.

Outside of a cloud provider (hyper-v, parallels, qemu, virtualbox, vmware) it use a `datasource` called nocloud  (https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html) which can read configuration from a vfat or a iso9660 IF the volume label is `cidata` or `CIDATA`.

### With packer

Packer provide a common way to provide a virtual floppy containing files to be used by the booted VM.
The volume label for the built filesystem is `packer`.

### Changes

1. Adding a `floppy_label` string along `floppy_dirs` and `floppy_files` in `common/floppy_config.go`
```
type FloppyConfig struct {
	FloppyFiles       []string `mapstructure:"floppy_files"`
	FloppyDirectories []string `mapstructure:"floppy_dirs"`
	FloppyLabel       string   `mapstructure:"floppy_label"`
}
```

2. Adding a `Label` along with `Files` and `Directories` in `common/step_create_floppy.go`
```
// StepCreateFloppy will create a floppy disk with the given files.
type StepCreateFloppy struct {
	Files       []string
	Directories []string
	Label       string

	floppyPath string

	FilesAdded map[string]bool
}
```

3. Change filesystem label from `packer` to the configured one. `packer` remains the default.
```
	// Format the block device so it contains a valid FAT filesystem
	log.Println("Formatting the block device with a FAT filesystem...")
	formatConfig := &fat.SuperFloppyConfig{
		FATType: fat.FAT12,
		Label:   s.Label,
		OEMName: s.Label,
	}
```

4. Map `FloppyConfig` to `StepCreateFloppy` in related builder:
   - hyperv-iso,
   - hyperv-vmcx,
   - parallels-iso,
   - parallels-pvm,
   - qemu,
   - virtualbox-iso,
   - virtualbox-ovf,
   - vmware-iso,
   - vmware-vmx.

5. Updated documention

### Test performed

Tests has been perform with hyper-v with a centos atomichost which is cloud-init enabled.

test files are regrouped in https://github.com/i-fimafeng/packer-vfd-label-test

### CODE REVIEW

**Comment by allinwait** [comment]
@taliesins What can we do in order to merge this? I see that there are other people who need this functionality (including me) and I'm willing to create a new pull request... with the same changes though.

**Comment by azr** [comment]
Hello there; we just have to make sure every commit in the PR is made by someone that has signed the CLA. We'll be happy to review 🙂.

**Comment by allinwait** [comment]
@azr thank you for the quick response! I see that @i-fimafeng has closed the issue, so he probably didin't sign the CLA. The question is if I can replicate his changes, and make a new PR, this time signing the CLA. It's just a small change and I don't see what else I can include.

**Comment by azr** [comment]
👍

**Pull request closed without merging**
