### PR TITLE
WIP: Switch Docker Driver to use the API instead of CLI

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Supersedes #3921, and includes #3922.

These things must handled/fixed:
- [x] [run_command](https://www.packer.io/docs/builders/docker.html#run_command) must be changed
- [x] Add support for overriding DOCKER_HOST,  DOCKER_CERT_PATH, and
  DOCKER_TLS_VERIFY
- [ ] Fixer to migrate from the old config with `run_command` to `command` etc.
- [ ] Login & Logout support
- [x] Allow setting more options previously handled by `run_command`.
- [ ] Handle privileged mode 
- [ ] Update docs

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Ping @vancluever

**Comment by vancluever** [comment]
Thanks @rickard-von-essen, yeah things have been pretty busy for me on this side and I haven't had time to do any work on the builder with other commitments. I do have some code that  might help with some of the above items though, I'll take some time to dig it up this evening!

**Comment by rickard-von-essen** [comment]
Closes #2809

**Comment by vancluever** [comment]
Hey @rickard-von-essen, unfortunately I think I'm not going to have too much time to work on the builder as a whole right now, just given my current work and personal project load. I do have the code in a gist though, check out the URL below:

https://gist.github.com/vancluever/51b19bf900faab62c87a750b3bf79f06

This may need some fixing for build errors and what not but it should show what the config would look like.

**Comment by rickard-von-essen** [comment]
Ok, thanks for letting me know. I'll have some more work on this that I can
share, hopefully soon.

**Comment by mwhooker** [comment]
note to myself: closing a couple of docker issues that would be better implemented after this PR. look at referenced issues

**Comment by vtolstov** [comment]
Does this pr needs help from somebody to get it merged?

**Comment by rickard-von-essen** [comment]
@vtolstov Yes please some help would be great! See the description for a list of tasks.

**Comment by mwhooker** [comment]
We'll want to make sure std{err,out} is always sent to the user. See 

* 2620

**Comment by hybmg57** [comment]
Is there a work around for running packer inside docker for now until this is merged?

**Comment by rickard-von-essen** [comment]
Not that I'm aware of.

**Comment by hybmg57** [comment]
@rickard-von-essen so there's absolutely no way of going around it? Such as using something a particular type for the provisioner?

**Comment by vtolstov** [comment]
@hybmg57 what you need? i'm already run packer inside docker and build qemu images.

**Comment by hybmg57** [comment]
@vtolstov how do you do this? Please share.

**Comment by hybmg57** [comment]
I'm running provisioners and they hang when I run with type shell

**Comment by vtolstov** [comment]
enable PACKER_LOG=1 and send debug log

**Comment by dolobanko** [comment]
Have the same problem, when running Packer inside a Docker container.
Docker version 1.12.3
Packer version 0.12.2

**Comment by dolobanko** [comment]
Here is a shortcut:

[0;32m    docker: Run command: docker run -v /var/lib/jenkins/.packer.d/tmp/packer-docker826911088:/packer-files -d -i -t ubuntu:16.04 /bin/bash[0m
[0;32m    docker: Container ID: 4e9661cd0557d74cd662c9276aa96739f9a2aff75d5a972370a7c1011a91373e[0m
[1;32m==> docker: Provisioning with shell script: /tmp/packer-shell177956160[0m
[1;32m==> docker: Killing the container: 4e9661cd0557d74cd662c9276aa96739f9a2aff75d5a972370a7c1011a91373e[0m
[1;31mBuild 'docker' errored: Retryable error: Error uploading script: Upload failed with non-zero exit status: 1[0m

==> Some builds didn't complete successfully and had errors:
--> docker: Retryable error: Error uploading script: Upload failed with non-zero exit status: 1

==> Builds finished but no artifacts were created.

**Comment by WeatherGod** [comment]
I am getting hit by this as well:
Docker version 1.13.1, build 092cba3
packer version 0.12.2

I am not doing anything fancy:
```
{
  "builders": [{
    "type": "docker",
    "image": "amazonlinux:latest",
    "export_path": "test.tar.gz"
}],
  "provisioners": [{
    "type": "shell",
    "inline": [
        "sudo useradd bizops"
    ]
  }]
}
```
It is a bit of an contrived example, but it fails just like my original. If I knew Go, I'd lend a hand in getting things completed. Is the problem limited to just inline shell provisioners? Is there any work-around? I would hate to have to go over to dockerfiles.

**Comment by WeatherGod** [comment]
I gave this branch a spin, and it did manage to attach onto the spun-up container image and tried to execute the script (that failed, but that is stemming from issues with the amazonlinux images not matching the AMIs).

**Comment by rickard-von-essen** [comment]
@WeatherGod sorry didn't really follow what you tested. This PR is only partially complete and require some more work before being complete.

**Comment by WeatherGod** [comment]
I followed the instructions in the contributions guide to `go get` the packer repository. I then fetched this branched, rebased it upon master, and fixed a couple tiny things (`if len(foo)` --> `if len(foo) > 0`). I then built the packer binary, and ran `bin/packer build docker-test.json`, which was the JSON file I posted above. It mostly worked. The failure I encountered was with the container not having a `sudo` command, surprisingly.

I'll be doing some more tests with it shortly, and I'll certainly provide more feedback if desired. Unfortunately, as I said, I have zero experience with Go (I am a Python dev, primarially), so I am afraid I can't really provide much help code-wise.

**Comment by WeatherGod** [comment]
So, I found an issue that is probably a result of the WIP nature of this PR. For my purposes to make the packer config the same between amazon-ebs and docker builders, I tweaked the `run_command` so that `sudo -i -u ec2-user` is used instead of `/bin/bash`. The docker container does indeed run that way (confirmed by manually attaching during -debug), but the provisioners are still executed as root.

**Comment by ktham** [comment]
I have the same issue as @dolobanko and ran into this pull request. @rickard-von-essen are you still working on this?

**Comment by rickard-von-essen** [comment]
@ktham _Working on it_ might be a bit strong. I have very little time to spend on this right now, but I plan to finish it. The bigest problem is not just implementing the driver but that the config have to be migrated since it's tightly bound to the cli and that will require allot of work.

I'm glad for any assistance we can get on this.

**Comment by ktham** [comment]
I see, gotcha, when I get the time, I'll try to learn some Go and help chip in where/when I can. We'll just run Packer outside of Docker to workaround #4213 in the meantime.

**Comment by promethe42** [comment]
Hi there!
Trying to use packer in docker-in-docker.
I was wondering if anyone was working on this?

**Comment by rickard-von-essen** [comment]
It's stalled. I plan to pick it up next year if no one steps up. There is quite some work needed to migrate a template.

**Comment by rickard-von-essen** [comment]
Closing this for now. I'll reopen when this is getting closer to done.

**Comment by ghostsquad** [comment]
Can this be re-opened? It doesn't make sense to close an issue that hasn't been resolved.

**Comment by rickard-von-essen** [comment]
This is a PR. I'll reopen it when I get back to work on it. My plan is to pick this up next year.

**Comment by bbrala** [comment]
@rickard-von-essen almost at the aniversary, any update? :)

**Comment by rickard-von-essen** [comment]
@bbrala 2018 hasn't ended yet 😏. Currently no ETA.

**Comment by bbrala** [comment]
Hehe, ok then 😄

**Comment by markmsmith** [comment]
Any plans to revisit this?  I think I may be seeing a related issue with a file provisioner download hanging when running with Docker for Mac.

**Comment by rickard-von-essen** [comment]
@markmsmith Currently I don't have any time to work on such a big thing. And I think that it would be better to add a new builder (`docker-api`) to not have to mimic the behaviour and configuration of the current one.

**Comment by markmsmith** [comment]
ok, thanks.  I'll open an issue to track the specific problem I'm seeing.

**Pull request closed without merging**
