### PR TITLE
[WIP] Use password

### LINKED ISSUE #9283: ansible-remote requiring private key even when ansible_password provided
ansible-remote requiring private key even when ansible_password provided
This change in behavior broke all my windows pipelines.
It also seems to force people down
A paragraph or two about the issue you're experiencing.

In the process of figuring it out I submitted PR https://github.com/hashicorp/packer/pull/9279
to help get to easier steps for checking if ansible args were proper or not.

#### Reproduction Steps

Steps to reproduce this issue
use ansible remote with any windows build that uses ssh and does not have the pubkey on it already.
or any ssh setup that does not allow for authorized keys.
```
{
        "type": "ansible",
        "extra_arguments": ["-vv",
            "-T 1200",
            "--extra-vars",
            "ansible_host_key_checking=False ansible_scp_if_ssh=True ansible_python_interpreter=/usr/bin/python3.6 ansible_ssh_retries=20 ansible_ssh_common_args='-C -o ControlMaster=auto -o ControlPersist=180s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' ansible_shell_type=powershell ansible_user={{user `ssh_username`}} ansible_password={{user `ssh_password`}} ansible_become_method=runas ansible_become_user=System ansible_shell_executable=None"
        ],
        "playbook_file": "{{user `path`}}/template.yaml",
        "use_sftp": true,
        "user": "{{user `ssh_username`}}",
        "inventory_directory": "{{user `path`}}",
        "inventory_file": "{{user `path`}}/inventory.yaml",
        "groups": "windows",
        "pause_before": "20s",
        "use_proxy": false,
        "timeout": "2h"
    }
```
### Packer version

1.5.6
### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

force to use ssh keys from packer
causes failures
```

==> windows_2019_05_22_20_15_46: Provisioning with Ansible...
    windows_2019_05_22_20_15_46: Not using Proxy adapter for Ansible run:
    windows_2019_05_22_20_15_46:        Using ssh keys from Packer communicator...
==> windows_2019_05_22_20_15_46: Executing Ansible: ansible-playbook -e packer_build_name=windows_2019_05_22_20_15_46 -e packer_builder_type=virtualbox-iso -e ansible_ssh_private_key_file=/var/folders/39/nsnpc_td69g56700msy0kwq40000gn/T/ansible-key086989184 --ssh-extra-args -o IdentitiesOnly=yes -i /Users/.../Documents/Server2016_Packer/inventory.yaml /Users/.../Documents/Server2016_Packer/template.yaml -vv -T 1200 --extra-vars ansible_host_key_checking=False ansible_scp_if_ssh=True ansible_python_interpreter=/usr/bin/python3.6 ansible_ssh_retries=20 ansible_ssh_common_args='-C -o ControlMaster=auto -o ControlPersist=180s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' ansible_shell_type=powershell ansible_user=vagrant ansible_password=vagrant ansible_become_method=runas ansible_become_user=System ansible_shell_executable=None

windows_2019_05_22_20_15_46: TASK [Gathering Facts] *********************************************************
    windows_2019_05_22_20_15_46: task path: /Users/.../Documents/Server2016_Packer/template.yaml:3
    windows_2019_05_22_20_15_46: fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"127.0.0.1\". Make sure this host can be reached over ssh: Warning: Permanently added '127.0.0.1' (ECDSA) to the list of known hosts.\r\nLoad key \"/var/folders/39/nsnpc_td69g56700msy0kwq40000gn/T/ansible-key086989184\": invalid format\r\nConnection closed by 127.0.0.1 port 22\r\n", "unreachable": true}


```

### PR DESCRIPTION
**Pull request by gamethis**
Adding ability to select `use_password` to ansible-remote options.
This allows user to choose password versus private key authentication.
It will leverage the password that packer already has and uses.

Closes #9283

### CODE REVIEW

**Comment by gamethis** [comment]
Questions.... as this is one of my first pull requests... is there anything in general I am missing? or anything that would like to be done different?

**Comment by SwampDragons** [comment]
Hi, Larry. Thanks for opening this! 

I _think_ instead of forcing another option here, we can guess based on context whether we should add it to the inventory file.  We can check whether the "Password" field in generatedData is an empty string. If it isn't empty, we know we should probably add ansible_password to the inventory. If it is empty, we know we can skip it. What do you think?

**Comment by gamethis** [comment]
Megan,

so I like the idea of making decisions based on context.

Am I wrong in thinking "Password" field in generatedData would always be present?? 
I believe the solution should be for whether the inventory file is user provided or not.

Scenarios for context switching 
=====

|scenario|answer|
|---|---|
|privatekeyfile is not ""|  use private key|
|pivatekeyfile == "auto"| use auto generated private key|
|ansible_password provided in argument| use password|
|privatekeyfile is ""|use password|

If you agree with this I will do another pass at the code.

**Comment by gamethis** [comment]
so i updated so if ansible_password is provided then it will not put the keyfile in args

**Comment by SwampDragons** [comment]
Cool, thanks. I'll try to review your new PR as soon as I can.

**Pull request closed without merging**
