### PR TITLE
Update CONTRIBUTING.md with community guideline

### PR DESCRIPTION
**Pull request by sylviamoss**
Inspired on https://github.com/hashicorp/boundary/pull/1014. This adds a guideline on how to better address our team.

### CODE REVIEW

**Review by azr — APPROVED** [review]
Really cool ! Could this apply to other members of the community too ?

**Review by nywilken — APPROVED** [review]
Nice!  Thanks for adding.

**Comment by sylviamoss** [comment]
> Really cool ! Could this apply to other members of the community too ?

Do you mean making the guideline more general when addressing not only the packer maintainers but other contributors as well?

**Comment by azr** [comment]
@sylviamoss, yes !

**Comment by SwampDragons** [comment]
Late to the party here, but +1.

**Pull request merged**
