### PR TITLE
WIP: VMware vSphere builder

### PR DESCRIPTION
**Pull request by marema31**
NOTE: I've closed my previous PR (#4662 ) after messing up completly my repository (sorry for the annoyance)

Attempt to do a builder for Vsphere using API as described in #4526.

Currently only the vsphere-iso is fully implemented. vsphere-vm as the skeleton, but driver parts and the corresponding config has to be done.

It currently use govc for interacting with VSphere, but a better way will be to replace the driver with a one using directly the govmomi library, but it was to difficult to me to tackle at the same time the learning of go, the structure of packer and the usage of this library.

It is working in my small lab, but I'm pretty sure that fancy environments (clusters, ressource-pools, distributed vswitch and SAN) will necessitate testing and correction.

Thanks for all the guys working on #4591, I've try to integrate as much as possible the proposed modification in this new builder

### CODE REVIEW

**Comment by mwhooker** [comment]
awesome! Will try to find some time to review. I don't think this will make it into the next release, but we should try to get it ready for the one after

**Comment by marema31** [comment]
Thanks @mwhooker .

As I told in my last comment of #1050, it's not finished, I needed some review to see if I was going in the right direction. I think @LizaTretyakova has in her proposal nearly all the missing part of this pull request to create a driver that use directly the vsphere API (via govmomi ? like in #4110 that I'd like to be integrated) to supplement/replace the implentation I have done with govc.

**Comment by LizaTretyakova** [comment]
Yes, it is govmomi. @marema31, you understand correctly.

**Comment by marema31** [comment]
Hello @LizaTretyakova, I've added the cloning functionality to this PR (via the vsphere-vm builder). I won't have access to my test infra in the next days, you may want to give it a try. It's only need to install the govc binary (like you've have done for ovftool). My next step will be to create the driver_api.go using govmomi and not govc ( I can't tell when for the moment).

**Comment by rismoney** [comment]
is there any update on this - i do realize this is major, but it seems as if the other vmware builders have limitations this will ultimately resolve.  What is needed to get this merged?

**Comment by marema31** [comment]
For the moment, it works on my test environment, the only constraint is to install govc utility on the machine that runs packer (like ovftool currently). I don't have access anymore to more complex test environnement (may be this summer). 

Since I've changed of job recently, I have less time to work on it, I've planned to go deeper in the next weeks. The next step for me is to create a second driver that use directly the govmomi API. 

If your are able to compile and test this builder, I'm very interested by all remarks on it.

**Comment by NickLarsenNZ** [comment]
I'm having trouble building your fork (for vsphere-iso), it seems the builder is not found.

I followed the build instructions from: https://github.com/hashicorp/packer/blob/master/CONTRIBUTING.md#working-on-forks, and all tests passed.

Steps:
```
go get github.com/hashicorp/packer
brew install govendor
cd ~/go/src/github.com/hashicorp/packer/
git remote add
git remote add marema31 https://github.com/marema31/packer.git
git checkout -b builder-vsphere-govc
make
cp ./bin/packer ~/bin/packer-vsphere
```

Then when I run `packer-vsphere build template.json`, I get the following output:
```
Failed to initialize build 'k8s-master': builder type not found: vsphere-iso
k8s-master output will be in this color.


==> Builds finished but no artifacts were created.
```

Is there a step I'm missing? I'd really like to try this out as it seems exactly what I need (rather than directly to an ESXi host).

**Comment by marema31** [comment]
@NickLarsenNZ , sorry for the delay for the answer, to be honest, I haven't followed this PR since month due to the comments in august 2017 on the #4526 that show that is was not the right solutions and a better one was also available.  When I first created the PR, I was asking for a review from more seasoned go/packer developper to tell me if I was going in the right tracks, and I precised that I wanted to go further by replacing CLI dependencies by official VMware SDK with help from some peers. At that time, packer's maintainers was focussed on the v1.0 preparation and decided to look at this after, answer I had agreed with. And several monthes later, other contributors came with arguments against this PR, the main arguments was the flaws I was aware of and that were the reason of my request to have advices and may be help to remove them. The other argument was that they will come with a solution in the next weeks that will make obsolete my proposal. 

At the same time, I've changed my job for a main cloud provider that provide vSphere as a service, but I do not had packer usage in this context, it's a project for last quarter of 2018. I therefore had less time and interest to follow this.

Since no review was done in 10 month, I suppose that this PR does not fit to packer needs, @mwhooker, @SwampDragons, if it is the case, just close the PR, if not I'll be pleased to have a look to this again.

**Pull request closed without merging**
