### PR TITLE
Hyper-V builder: Add support for differencing disk

### PR DESCRIPTION
**Pull request by vijayinvites**
Adds support for differencing disks in Hyper-V builder.

use "differencing_disk": "true" in your builder step to use this feature.

### CODE REVIEW

**Comment by vijayinvites** [comment]
@pvandervelde can you please test this out and post your comments/feedback?

**Comment by pvandervelde** [comment]
@vijayinvites I can try but it might be a while. Currently busy trying to finish some of my own projects

**Comment by vijayinvites** [comment]
@pvandervelde Thanks 👍

**Comment by vijayinvites** [comment]
@mwhooker, do you think @taliesins will find time to review this. I don't see him online now a days. it has been a while.

**Comment by mwhooker** [comment]
I don't know, but if someone can test this I'll merge

**Comment by pvandervelde** [comment]
I unfortunately don't have any time at the moment. Got too many things I need to finish this week. Maybe in the weekend if nobody else can get to it before then

**Comment by mwhooker** [comment]
unfortunately needs a rebase. If someone else can +1 this I will merge, but untargeting since we don't have the pieces in place

**Comment by vijayinvites** [comment]
I will do a rebase today or tomorrow and push the changes. Thanks.

**Comment by vijayinvites** [comment]
@mwhooker I have rebased the branch and fixed the merge conflicts.

**Comment by abhipallav** [comment]
I have been using it for two weeks. It works without any issue.

**Comment by Ajmal-S** [comment]
I have been using it for a week or so, saves a lot of space and i haven't found any issues.

**Comment by vijayinvites** [comment]
@mwhooker can this be merged soon? I have few more changes to be sent as PR.

**Comment by vijayinvites** [comment]
@SwampDragons @mwhooker Can you guys take a look at this PR. I have other changes to be submitted that need this change.

**Comment by SwampDragons** [comment]
Thanks for writing this -- the code looks clean and since we have people already using the branch I'm going to merge.

**Pull request merged**
