### PR TITLE
comm/ssh: Add support for using SSH Agent auth towards a bastion host.

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Adds `ssh_bastion_agent_auth`

Fixes: #4732

### CODE REVIEW

**Comment by yfronto** [comment]
I don't receive the error described in the bug but SSH never connects. On debug logging, I see:

```
2017/05/28 11:43:49 packer: 2017/05/28 11:43:49 [DEBUG] TCP connection to SSH ip/port failed: Error connecting to bastion: ssh: must specify HostKeyCallback
```

Is this a config on my side that I need to fix? The full output is below. I CTL-C cancelled after I started getting the error, but the error continues to print every few seconds before eventually giving up if I don't cancel.

```
kurt@thor ~/S/g/h/packer (bastion-agent-auth) [1]> 
env PACKER_LOG=1 packer build test.json
2017/05/28 11:43:27 [INFO] Packer version: 1.1.0-dev (2164700)
2017/05/28 11:43:27 Packer Target OS/Arch: linux amd64
2017/05/28 11:43:27 Built with Go Version: go1.8
2017/05/28 11:43:27 Detected home directory from env var: /home/kurt
2017/05/28 11:43:27 Using internal plugin for amazon-chroot
2017/05/28 11:43:27 Using internal plugin for amazon-ebssurrogate
2017/05/28 11:43:27 Using internal plugin for digitalocean
2017/05/28 11:43:27 Using internal plugin for null
2017/05/28 11:43:27 Using internal plugin for triton
2017/05/28 11:43:27 Using internal plugin for amazon-ebs
2017/05/28 11:43:27 Using internal plugin for amazon-instance
2017/05/28 11:43:27 Using internal plugin for azure-arm
2017/05/28 11:43:27 Using internal plugin for openstack
2017/05/28 11:43:27 Using internal plugin for parallels-iso
2017/05/28 11:43:27 Using internal plugin for parallels-pvm
2017/05/28 11:43:27 Using internal plugin for profitbricks
2017/05/28 11:43:27 Using internal plugin for vmware-vmx
2017/05/28 11:43:27 Using internal plugin for amazon-ebsvolume
2017/05/28 11:43:27 Using internal plugin for cloudstack
2017/05/28 11:43:27 Using internal plugin for docker
2017/05/28 11:43:27 Using internal plugin for file
2017/05/28 11:43:27 Using internal plugin for hyperv-iso
2017/05/28 11:43:27 Using internal plugin for qemu
2017/05/28 11:43:27 Using internal plugin for googlecompute
2017/05/28 11:43:27 Using internal plugin for oneandone
2017/05/28 11:43:27 Using internal plugin for virtualbox-iso
2017/05/28 11:43:27 Using internal plugin for virtualbox-ovf
2017/05/28 11:43:27 Using internal plugin for vmware-iso
2017/05/28 11:43:27 Using internal plugin for shell
2017/05/28 11:43:27 Using internal plugin for powershell
2017/05/28 11:43:27 Using internal plugin for puppet-masterless
2017/05/28 11:43:27 Using internal plugin for puppet-server
2017/05/28 11:43:27 Using internal plugin for ansible
2017/05/28 11:43:27 Using internal plugin for ansible-local
2017/05/28 11:43:27 Using internal plugin for chef-client
2017/05/28 11:43:27 Using internal plugin for chef-solo
2017/05/28 11:43:27 Using internal plugin for salt-masterless
2017/05/28 11:43:27 Using internal plugin for windows-restart
2017/05/28 11:43:27 Using internal plugin for windows-shell
2017/05/28 11:43:27 Using internal plugin for converge
2017/05/28 11:43:27 Using internal plugin for file
2017/05/28 11:43:27 Using internal plugin for shell-local
2017/05/28 11:43:27 Using internal plugin for manifest
2017/05/28 11:43:27 Using internal plugin for shell-local
2017/05/28 11:43:27 Using internal plugin for atlas
2017/05/28 11:43:27 Using internal plugin for docker-save
2017/05/28 11:43:27 Using internal plugin for artifice
2017/05/28 11:43:27 Using internal plugin for checksum
2017/05/28 11:43:27 Using internal plugin for docker-import
2017/05/28 11:43:27 Using internal plugin for docker-push
2017/05/28 11:43:27 Using internal plugin for vagrant-cloud
2017/05/28 11:43:27 Using internal plugin for vsphere
2017/05/28 11:43:27 Using internal plugin for amazon-import
2017/05/28 11:43:27 Using internal plugin for docker-tag
2017/05/28 11:43:27 Using internal plugin for googlecompute-export
2017/05/28 11:43:27 Using internal plugin for vagrant
2017/05/28 11:43:27 Using internal plugin for compress
2017/05/28 11:43:27 Detected home directory from env var: /home/kurt
2017/05/28 11:43:27 Attempting to open config file: /home/kurt/.packerconfig
2017/05/28 11:43:27 [WARN] Config file doesn't exist: /home/kurt/.packerconfig
2017/05/28 11:43:27 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[amazon-instance:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-instance vmware-vmx:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-vmx docker:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-docker amazon-chroot:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-chroot amazon-ebssurrogate:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebssurrogate parallels-iso:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-iso profitbricks:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-profitbricks amazon-ebsvolume:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebsvolume file:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-file digitalocean:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-digitalocean openstack:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-openstack hyperv-iso:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-hyperv-iso googlecompute:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-googlecompute oneandone:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oneandone vmware-iso:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-iso azure-arm:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-azure-arm cloudstack:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-cloudstack amazon-ebs:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebs parallels-pvm:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-pvm qemu:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-qemu virtualbox-iso:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-iso virtualbox-ovf:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-ovf null:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-null triton:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-triton] PostProcessors:map[vagrant-cloud:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant-cloud amazon-import:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-amazon-import docker-tag:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-tag manifest:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-manifest shell-local:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-shell-local artifice:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-artifice docker-push:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-push docker-import:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-import vsphere:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere googlecompute-export:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-googlecompute-export vagrant:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant atlas:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-atlas docker-save:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-save checksum:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-checksum compress:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-compress] Provisioners:map[powershell:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-powershell puppet-server:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-server file:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-file salt-masterless:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-salt-masterless windows-shell:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-shell puppet-masterless:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-masterless ansible-local:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible-local chef-client:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-client shell:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell ansible:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible shell-local:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell-local chef-solo:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-solo windows-restart:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-restart converge:/usr/local/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-converge]}
2017/05/28 11:43:27 Setting cache directory: /home/kurt/SourceControl/github.com/hashicorp/packer/packer_cache
2017/05/28 11:43:27 Detected home directory from env var: /home/kurt
2017/05/28 11:43:27 Loading builder: amazon-ebs
2017/05/28 11:43:27 Plugin could not be found. Checking same directory as executable.
2017/05/28 11:43:27 Current exe path: /usr/local/bin/packer
2017/05/28 11:43:27 Creating plugin client for path: /usr/local/bin/packer
2017/05/28 11:43:27 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-builder-amazon-ebs"}
2017/05/28 11:43:27 Waiting for RPC address for: /usr/local/bin/packer
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 [INFO] Packer version: 1.1.0-dev (2164700)
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Packer Target OS/Arch: linux amd64
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Built with Go Version: go1.8
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Detected home directory from env var: /home/kurt
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Attempting to open config file: /home/kurt/.packerconfig
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 [WARN] Config file doesn't exist: /home/kurt/.packerconfig
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Setting cache directory: /home/kurt/SourceControl/github.com/hashicorp/packer/packer_cache
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 args: []string{"packer-builder-amazon-ebs"}
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Plugin minimum port: 10000
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Plugin maximum port: 25000
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Plugin address: unix /tmp/packer-plugin635968690
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Waiting for connection...
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Detected home directory from env var: /home/kurt
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Serving a plugin connection...
2017/05/28 11:43:27 ui: amazon-ebs output will be in this color.
2017/05/28 11:43:27 ui: 
2017/05/28 11:43:27 Build debug mode: false
2017/05/28 11:43:27 Force build: false
2017/05/28 11:43:27 On error: 
2017/05/28 11:43:27 Preparing build: amazon-ebs
amazon-ebs output will be in this color.

2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 Config: {PackerConfig:{PackerBuildName:amazon-ebs PackerBuilderType:amazon-ebs PackerDebug:false PackerForce:false PackerOnError: PackerUserVars:map[]} AccessConfig:{AccessKey: SecretKey: RawRegion:us-west-2 SkipValidation:false Token: ProfileName: CustomEndpointEc2:} AMIConfig:{AMIName:packer-test-1495989807 AMIDescription:Base Test AMIVirtType: AMIUsers:[] AMIGroups:[] AMIProductCodes:[] AMIRegions:[] AMISkipRegionValidation:false AMITags:map[] AMIEnhancedNetworking:false AMIForceDeregister:false AMIForceDeleteSnapshot:false AMIEncryptBootVolume:false AMIKmsKeyId: SnapshotTags:map[] SnapshotUsers:[] SnapshotGroups:[]} BlockDevices:{AMIBlockDevices:{AMIMappings:[]} LaunchBlockDevices:{LaunchMappings:[]}} RunConfig:{AssociatePublicIpAddress:false AvailabilityZone: EbsOptimized:false IamInstanceProfile: InstanceType:t2.micro RunTags:map[] SourceAmi: SourceAmiFilter:{Filters:map[0xc4202f5f50:0xc4202f5f70 0xc4202f5f90:0xc4202f5fb0 0xc4202f5fd0:0xc4202f5ff0] Owners:[] MostRecent:true} SpotPrice: SpotPriceAutoProduct: DisableStopInstance:false SecurityGroupId: SecurityGroupIds:[] SubnetId:subnet-******* TemporaryKeyPairName: UserData: UserDataFile: WindowsPasswordTimeout:20m0s VpcId:vpc-******* InstanceInitiatedShutdownBehavior:stop Comm:{Type:ssh SSHHost: SSHPort:22 SSHUsername:ubuntu SSHPassword: SSHPrivateKey: SSHPty:false SSHTimeout:5m0s SSHAgentAuth:true SSHDisableAgent:false SSHHandshakeAttempts:10 SSHBastionHost:10.104.42.91 SSHBastionPort:22 SSHBastionAgentAuth:true SSHBastionUsername:ubuntu SSHBastionPassword: SSHBastionPrivateKey: SSHFileTransferMethod:scp WinRMUser: WinRMPassword: WinRMHost: WinRMPort:0 WinRMTimeout:0s WinRMUseSSL:false WinRMInsecure:false WinRMTransportDecorator:<nil>} SSHKeyPairName:ansible-bot SSHPrivateIp:true} VolumeRunTags:map[] ctx:{Data:<nil> Funcs:map[clean_ami_name:0xb3faa0] UserVariables:map[] EnableEnv:false BuildName:amazon-ebs BuildType:amazon-ebs TemplatePath:/home/kurt/SourceControl/github.com/hashicorp/packer/test.json}}
2017/05/28 11:43:27 Waiting on builds to complete...
2017/05/28 11:43:27 Starting build run: amazon-ebs
2017/05/28 11:43:27 Running builder: amazon-ebs
2017/05/28 11:43:27 packer: 2017/05/28 11:43:27 [INFO] Finding AZ and VpcId for the given subnet 'subnet-*******'
2017/05/28 11:43:28 packer: 2017/05/28 11:43:28 [INFO] AvailabilityZone found: 'us-west-2a'
2017/05/28 11:43:28 ui: ==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Prevalidating AMI Name...
2017/05/28 11:43:29 packer: 2017/05/28 11:43:29 Using AMI Filters {
2017/05/28 11:43:29 packer:   Filters: [{
2017/05/28 11:43:29 packer:       Name: "virtualization-type",
2017/05/28 11:43:29 packer:       Values: ["hvm"]
2017/05/28 11:43:29 packer:     },{
2017/05/28 11:43:29 packer:       Name: "name",
2017/05/28 11:43:29 packer:       Values: ["*ubuntu-xenial-16.04-amd64-server-*"]
2017/05/28 11:43:29 packer:     },{
2017/05/28 11:43:29 packer:       Name: "root-device-type",
2017/05/28 11:43:29 packer:       Values: ["ebs"]
2017/05/28 11:43:29 packer:     }]
2017/05/28 11:43:29 packer: }
2017/05/28 11:43:31 ui:     amazon-ebs: Found Image ID: ami-45224425
    amazon-ebs: Found Image ID: ami-45224425
2017/05/28 11:43:31 ui: ==> amazon-ebs: Using SSH Agent for existing key pair ansible-bot
2017/05/28 11:43:31 ui: ==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Using SSH Agent for existing key pair ansible-bot
2017/05/28 11:43:31 packer: 2017/05/28 11:43:31 Temporary group name: packer 592afe33-76f1-4fb5-4e71-be83db3eb00e
==> amazon-ebs: Creating temporary security group for this instance...
2017/05/28 11:43:31 ui: ==> amazon-ebs: Authorizing access to port 22 on the temporary security group...
==> amazon-ebs: Authorizing access to port 22 on the temporary security group...
2017/05/28 11:43:31 packer: 2017/05/28 11:43:31 [DEBUG] Waiting for temporary security group: sg-9a0a52e1
2017/05/28 11:43:31 packer: 2017/05/28 11:43:31 [DEBUG] Found security group sg-9a0a52e1
2017/05/28 11:43:31 ui: ==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Launching a source AWS instance...
2017/05/28 11:43:32 ui:     amazon-ebs: Instance ID: i-0463118788e77eccd
    amazon-ebs: Instance ID: i-0463118788e77eccd
2017/05/28 11:43:32 ui: ==> amazon-ebs: Waiting for instance (i-0463118788e77eccd) to become ready...
2017/05/28 11:43:32 packer: 2017/05/28 11:43:32 Waiting for state to become: running
2017/05/28 11:43:32 packer: 2017/05/28 11:43:32 Using 2s as polling delay (change with AWS_POLL_DELAY_SECONDS)
2017/05/28 11:43:32 packer: 2017/05/28 11:43:32 Allowing 300s to complete (change with AWS_TIMEOUT_SECONDS)
==> amazon-ebs: Waiting for instance (i-0463118788e77eccd) to become ready...
2017/05/28 11:43:48 ui: ==> amazon-ebs: Adding tags to source instance
==> amazon-ebs: Adding tags to source instance
2017/05/28 11:43:48 ui:     amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Adding tag: "Name": "Packer Builder"
2017/05/28 11:43:49 packer: 2017/05/28 11:43:49 [INFO] Not using winrm communicator, skipping get password...
2017/05/28 11:43:49 packer: 2017/05/28 11:43:49 [INFO] Waiting for SSH, up to timeout: 5m0s
2017/05/28 11:43:49 ui: ==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Waiting for SSH to become available...
2017/05/28 11:43:49 packer: 2017/05/28 11:43:49 [DEBUG] TCP connection to SSH ip/port failed: Error connecting to bastion: ssh: must specify HostKeyCallback
2017/05/28 11:43:54 packer: 2017/05/28 11:43:54 [DEBUG] TCP connection to SSH ip/port failed: Error connecting to bastion: ssh: must specify HostKeyCallback
2017/05/28 11:43:59 packer: 2017/05/28 11:43:59 [DEBUG] TCP connection to SSH ip/port failed: Error connecting to bastion: ssh: must specify HostKeyCallback
^C2017/05/28 11:44:00 Closing stdin because interrupt received.
2017/05/28 11:44:00 Stopping build: amazon-ebs
2017/05/28 11:44:00 packer: 2017/05/28 11:44:00 Received interrupt signal (count: 1). Ignoring.
2017/05/28 11:44:00 packer: 2017/05/28 11:44:00 Cancelling the step runner...
2017/05/28 11:44:01 packer: 2017/05/28 11:44:01 [WARN] Interrupt detected, quitting waiting for SSH.
2017/05/28 11:44:01 packer: 2017/05/28 11:44:01 [DEBUG] SSH wait cancelled. Exiting loop.
2017/05/28 11:44:01 ui: ==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Terminating the source AWS instance...
2017/05/28 11:44:02 packer: 2017/05/28 11:44:02 Waiting for state to become: terminated
2017/05/28 11:44:02 packer: 2017/05/28 11:44:02 Using 2s as polling delay (change with AWS_POLL_DELAY_SECONDS)
2017/05/28 11:44:02 packer: 2017/05/28 11:44:02 Allowing 300s to complete (change with AWS_TIMEOUT_SECONDS)
2017/05/28 11:44:59 ui: ==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Cleaning up any extra volumes...
2017/05/28 11:44:59 ui: ==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: No volumes to clean up, skipping
2017/05/28 11:44:59 ui: ==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary security group...
2017/05/28 11:44:59 ui: Build 'amazon-ebs' finished.
2017/05/28 11:44:59 Builds completed. Waiting on interrupt barrier...
2017/05/28 11:44:59 Build cancelled: amazon-ebs
2017/05/28 11:44:59 ui: Cleanly cancelled builds after being interrupted.
Build 'amazon-ebs' finished.
2017/05/28 11:44:59 waiting for all plugin processes to complete...
Cleanly cancelled builds after being interrupted.
2017/05/28 11:44:59 /usr/local/bin/packer: plugin process exited
```

**Comment by yfronto** [comment]
Here's my test, removed vpc/subnet ids:

```
{
  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{ user `aws_access_key` }}",
      "secret_key": "{{ user `aws_secret_key` }}",
      "region": "us-west-2",
      "vpc_id": "vpc-62ebfc05",
      "subnet_id": "subnet-ea0f2c8d",
      "ssh_agent_auth": true,
      "ssh_username": "ubuntu",
      "ssh_bastion_host": "10.104.42.91",
      "ssh_bastion_username": "ubuntu",
      "ssh_bastion_agent_auth": true,
      "ssh_keypair_name": "ansible-bot",
      "ssh_private_ip": true,
      "associate_public_ip_address": false,
      "instance_type": "t2.micro",
      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "*ubuntu-xenial-16.04-amd64-server-*",
          "root-device-type": "ebs"
        },
        "most_recent": true
      },
      "ami_name": "packer-test-{{ timestamp }}",
      "ami_description": "Base Test"
    }
  ]
}
```

**Comment by yfronto** [comment]
Possibly due to this? https://github.com/golang/crypto/commit/e4e2799dd7aab89f583e1d898300d96367750991

**Comment by rickard-von-essen** [comment]
Added a commit that should fix that, but you shouldn't hit that problem since we vendored an older version.

**Comment by yfronto** [comment]
Confirmed to work on amazon-ebs; lgtm. Thanks @rickard-von-essen!

**Comment by mwhooker** [comment]
thanks!

**Pull request merged**
