### PR TITLE
Building Azure devtestlabs Images using Packer

### PR DESCRIPTION
**Pull request by VaijanathB**
This pull request adds a new packer Builder to build Custom Images and upload them to DevTest Lab image repository automatically. Additionally images can be uploaded to Shared Image Gallery to be consumed in DevTest Labs. This change enables users to consume provisioners from Packer and also artifacts from DevTest lab making it easy for users to mix and match the artifacts  in building a custom image. 
The builder uses Azure common packages for Authentication and is in sync with the design with other Azure builders. 
As part of the check in we are also adding a custom Provisioner which can add the DevTestLab artifacts<resources> during the provisioning phase also. Note we can add these artifacts during the building of the image but adding a custom provisioner enables DevTestLab users to mix and match artifacts. 
We have added sample end to end template scripts in the dtl builder directory that can be used as examples on how to consume this change. 

As part of this change I am also checking in the Go SDK for Azure Devtest lab service in the vendor folder. 
I have updated the documentation to reflect these new changes.

### CODE REVIEW

**Comment by SwampDragons** [comment]
Cool, thanks @VaijanathB! I won't have a chance to review this until next week but it looks good at a glane.

**Comment by VaijanathB** [comment]
Hello @SwampDragons ,

Just wanted to see if you can give some feedback on this PR. I have fixed all my linting issues and have followed all the steps in the Conrtibuting.md to get the PR. I still see the Check vendor vs mod step failing in Circle CI. Please let me know if I am missing any steps or need to update PR in anyways. 

Thanks,
Vaijanath

**Comment by SwampDragons** [comment]
Sorry for the delay here. Just ran `go mod vendor` to fix that failing tests, and reviewing now.

**Comment by VaijanathB** [comment]
@SwampDragons , I had just run the make command and fixed all the tests in that command. I will fix all the acceptance tests and update the PR. Thanks for the feedback.

**Comment by VaijanathB** [comment]
Hello @SwampDragons , 

I have fixed the acceptance tests and have updated the PR. To run the acceptance test you need to have created a devtestlab where the images will be stored.  The instructions are 

1) Create a resource group using the following az cli command. 
**az group create --name packer-acceptance-test --location "South Central US"**
2) Deploy the arm template to create the Devtest lab. 
 **az deployment group create \
  --name ExampleDeployment \
  --resource-group packer-acceptance-test \
  --template-file acceptancetest.json**

Please let me know if you have any more feedback. 

Thanks,
VJ

**Comment by SwampDragons** [comment]
This looks good now; just needs the CLA signed. Thanks VJ!

**Comment by VaijanathB** [comment]
@SwampDragons ,

I have signed the CLA. But it still shows as pending. Am I doing something wrong ? I have signed it as saying I am making submissions on behalf of my employer.  Please let me know If I am doing anything wrong here. 

Thanks,
VJ

**Comment by SwampDragons** [comment]
Normally that means you've signed it using a different email address than the one that is associated with the commits on github. Is that the case here?

**Comment by VaijanathB** [comment]
Hello @SwampDragons ,

I am using the same email id as I signed in with Github. Its my primary email on my github id. I also updated my user.email setting and uploaded a commit to see if that works. I am not having any luck with it. Can you please help me get this thing resolved?

Thanks,
VaijanathB

**Comment by SwampDragons** [comment]
Hmm. Looks like it's got you in here twice, as  Vaijanath Angadihiremath and as VaijanathB.

**Comment by SwampDragons** [comment]
The error message it's giving me is ```Vaijanath Angadihiremath seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please add the email address used for this commit to your account.```

**Comment by VaijanathB** [comment]
Vaijanath Angadihiremath is my name and VaijanathB is my github user id. I have vaangadi@microsoft.com as my email id which is the primary email id on my account. I also sent a commit after setting user.email on my github client thinking that was the problem. Anyway we can get around this problem ?

**Comment by SwampDragons** [comment]
I've reached out to the team in charge of the bot for help.

**Comment by SwampDragons** [comment]
Hey somehow this PR has 10k commits -- I think you may have gotten into a bit of trouble with a rebase/merge conflict, which may be why the CLA bot is so confused. Can you try to fix the history on your branch?  (In the past when I've gotten my git history really messed up, sometimes I've found that cherry-picking my commits to a new branch off master, then resetting the PR branch to that branch is the way to go).

**Comment by VaijanathB** [comment]
Hello @SwampDragons , 

I tried to resolve this with multiple ways and was not able to. It still shows merging 10k commits. This happened when I tried to update my email address with my git account and somehow it updated all logs/history. I will instead send a clean new PR with just my changes so that its easy to merge. Sorry for the trouble. 

Thanks,
VJ

**Pull request closed without merging**
