### PR TITLE
Fixes the DHCP lease and configuration pathfinders for VMware Player.

### PR DESCRIPTION
**Pull request by arizvisa**
This also adds some logs that output how packer determines the interfaces found for a chosen network and locates the different files that its detection depends on.

Closes Issue #5882 for VMware Player.

### CODE REVIEW

**Comment by akulbe** [comment]
I'm not sure if this bug is actually fixed. I have the latest version installed, and I'm still seeing issues with packer getting back onto the VM with SSH.

➜  build_here git:(master) ✗ packer version
Packer v1.2.3-dev (83162717e)

[debug.log](https://github.com/hashicorp/packer/files/1886664/debug.log)

➜  ~ ssh -i ~/.ssh/my_key_rsa -oConnectTimeout=5 vagrant@172.16.15.131
The authenticity of host '172.16.15.131 (172.16.15.131)' can't be established.
ECDSA key fingerprint is SHA256:csKmJuAYMPTPVOVcGpKib6enzLocV4CpG893Xyy+Av0.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.16.15.131' (ECDSA) to the list of known hosts.
[vagrant@localhost ~]$ logout
Connection to 172.16.15.131 closed.

So I can get on to the VM with SSH, but packer cannot.

**Comment by arizvisa** [comment]
@akulbe, according to the logs it seems unable to authenticate via ssh.

```
2018/04/07 12:20:26 packer: 2018/04/07 12:20:26 GuestAddress found MAC address in VMX: 00:0c:29:aa:bf:96
2018/04/07 12:20:26 packer: 2018/04/07 12:20:26 Trying DHCP leases path: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
2018/04/07 12:20:26 packer: 2018/04/07 12:20:26 Detected IP: 172.16.15.131
...
2018/04/07 12:20:41 packer: 2018/04/07 12:20:41 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 172.16.15.131:22: i/o timeout
...
2018/04/07 12:20:46 packer: 2018/04/07 12:20:46 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 172.16.15.131:22: connect: host is down
...
2018/04/07 12:20:52 packer: 2018/04/07 12:20:52 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 172.16.15.131:22: connect: connection refused
```

Then later:
```
2018/04/07 12:28:43 packer: 2018/04/07 12:28:43 Lookup up IP information...
2018/04/07 12:28:43 packer: 2018/04/07 12:28:43 GuestAddress found MAC address in VMX: 00:0c:29:aa:bf:96
2018/04/07 12:28:43 packer: 2018/04/07 12:28:43 Trying DHCP leases path: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
2018/04/07 12:28:43 packer: 2018/04/07 12:28:43 Detected IP: 172.16.15.131
...
2018/04/07 12:28:43 packer: 2018/04/07 12:28:43 [INFO] Attempting SSH connection...
2018/04/07 12:28:43 packer: 2018/04/07 12:28:43 [DEBUG] reconnecting to TCP connection for SSH
2018/04/07 12:28:43 packer: 2018/04/07 12:28:43 [DEBUG] handshaking with SSH
2018/04/07 12:28:43 packer: 2018/04/07 12:28:43 [ERROR] handshake error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
2018/04/07 12:28:43 packer: 2018/04/07 12:28:43 [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
2018/04/07 12:28:43 packer: 2018/04/07 12:28:43 [DEBUG] Detected authentication error. Increasing handshake attempts.
```
Which seems to repeat until it gives up.

**Comment by arizvisa** [comment]
@akulbe, can you share your json template?

**Comment by akulbe** [comment]
@arizvisa Actually, I think it's on me. In my KS file, I was disabling PasswordAuthentication in the SSH config. A mailing list entry clued me in. 
(Sure enough, once I commented out that line, the build would succeed. So my post is invalid. My apologies!) 

That leads me to another question, though. Is there a way to get packer to use SSH keys for auth, rather than just a password? This would let a user have a more secure configuration, out of the box.

**Comment by arizvisa** [comment]
kk.

With regards to your question, it might be in the docs for communicators: https://www.packer.io/docs/templates/communicator.html

If it's not, you can create an issue and one of the devers might be able to help you (i'm just a former contributor). Comments in a PR are typically the wrong place to discuss problems/features.

**Pull request merged**
