### PR TITLE
Revert "Merge pull request #4494 from tb3088/EOL-handling"

### PR DESCRIPTION
**Pull request by mwhooker**
This reverts commit dfe4f56c75abe1fb25f5453a5e7828a4c2504260, reversing
changes made to e90c87f88524c2f4a41f4b721e3b7b0eb29eafcc.

Revert changes to makefile and format checker, as they no longer work

### CODE REVIEW

**Comment by tb3088** [comment]
Makefile from 'master' doesn't work either (on Cygwin)
/cygdrive/c/Users/pattonm/AppData/Local/go/src/github.com/hashicorp/packer/scripts/gofmtcheck.sh $(find . -not -path "./vendor/*" -name "*.go")
/cygdrive/c/Users/pattonm/AppData/Local/go/src/github.com/hashicorp/packer/scripts/gofmtcheck.sh: line 2: $'\r': command not found
==> Checking that code complies with gofmt requirements...
/cygdrive/c/Users/pattonm/AppData/Local/go/src/github.com/hashicorp/packer/scripts/gofmtcheck.sh: line 5: /cygdrive/c/Program Files/GoLang/bin/gofmt: Argument list too long
/cygdrive/c/Users/pattonm/AppData/Local/go/src/github.com/hashicorp/packer/scripts/gofmtcheck.sh: line 15: syntax error: unexpected end of file
make: *** [Makefile:64: fmt-check] Error 2

**Comment by tb3088** [comment]
I have reconfirmed that my Makefile, build.sh and gofmtchk.sh work precisely as intended. Again on Cygwin. I will find a Linux environment to investigate why it might be misbehaving.

**Comment by mwhooker** [comment]
> line 2: $'\r': command not found 

I think this is an issue with how you've checked out the file. It's a 0x0A line feed on my system, not a carriage return.

I'll try to put up a patch to switch to xargs instead of passing files to check through argv

**Comment by mwhooker** [comment]
@tb3088 #6230 is up for xargs

**Comment by tb3088** [comment]
I checked out master, replaced with my Makefile and scripts/build.sh gofmtcheck.sh and verified all Make targets. uname=Linux, Ubuntu 16.04, go=1.10.2.
So, I still don't know how/what you observed as failing?

**Pull request merged**
