### PR TITLE
[WIP] Check for Linode account image limit before starting.

### PR DESCRIPTION
**Pull request by phillc**
A Linode account is only allowed limited to a certain number of Images, typically 3, before receiving an error that they have reached that limit.

This work is an attempt to address feedback on the frustration of not finding out that they have hit this limit until the very end of the build process, potentially 10+ minutes after they started the script. Instead, if configured, check the number of images already on the account.

I am not hard coding `3` in favor of this being an opt in feature, to make it backwards compatible, and to be resistant to any changes Linode may make against this number.

I still need to add documentation, and will mention that `3` is the typical setting.

I have also updated our linodego module while I am here.

I need help with the integration test. My intent is to build an image (exactly as the original test did), then build another image with an assumption of the account limit being 1, which should error. I have looked at many of the other builder tests, and cannot find an example of asserting that there is a failure. I also cannot figure out how to properly clean the artifacts after the test, as I have set SkipArtifactTeardown on the first run to be able to exert the failure condition. Perhaps there is a different way to achieve this.

Thank you.

### CODE REVIEW

**Comment by phillc** [comment]
I will need to send the CLA to our legal department so it may take some time.

**Comment by phillc** [comment]
FYI. Still waiting for our CLA to be approved internally.

**Comment by phillc** [comment]
Signed. I still need the help requested in the original message.

**Comment by SwampDragons** [comment]
Thanks -- I'll try to take a look tomorrow.

**Comment by phillc** [comment]
@Charliekenney23 or @LBGarber will be taking this PR going forward, from the Linode perspective.

**Comment by SwampDragons** [comment]
Closing this since the Linode builder has been extracted to its own repo: https://github.com/hashicorp/packer-plugin-linode. I'm sorry this didn't get reviewed. The acceptance testing framework in the SDK has also changed; I can give some advice whoever decides to move this patch over to the new repo and get tests up, but since it can't be applied wholesale I'm going to leave this to the folks at linode.

**Pull request closed without merging**
