### PR TITLE
test that parsing fails on a certain kind of malformed JSON

### PR DESCRIPTION
**Pull request by WeatherGod**
Adding a test for the change introduced in #4906.

### CODE REVIEW

**Comment by WeatherGod** [comment]
I have no clue if this actually works... I apparently can't build packer anymore since it requires the `context` package which requires go1.7 and I have go1.6.3.

**Comment by mwhooker** [comment]
thanks!

**Comment by mwhooker** [comment]
looks like a simple fix, will merge once tests pass

**Comment by WeatherGod** [comment]
ok, test fixed (and commit fixed to have the right email address)

**Comment by mwhooker** [comment]
thanks!

**Pull request merged**
