### PR TITLE
Packer plugin support ZStack

### PR DESCRIPTION
**Pull request by koven2049**
[ZStack](http://en.zstack.io/) is an IaaS platform designed for private and hybrid cloud.
The PR integrated ZStack plugin to the Packer builder.

file change list:
- CODEOWNERS
- builder/zstack/
- examples/zstack/
- command/plugin.go
- website/source/docs/builders/zstack-vminstance.html.md

Here are the plugin executes screenshot:
image

See more informations in builder/zstack/NOTE.md

### CODE REVIEW

**Comment by koven2049** [comment]
lack of website/source/docs/builders/zstack.html.md

**Comment by koven2049** [comment]
@hashicorp-cla please check my cla status

**Comment by SwampDragons** [comment]
Hi @koven2049, thanks for opening!

Internally, we've been having a conversation about whether it makes sense to keep merging third party builders that we (HashiCorp) don't have the engineering resources to officially support -- I think it's been causing confusion in the community to have the officially-supported and community-supported plugins in the same place, and it makes the issue tracker a bit cluttered.

I'm working on a roadmap that will hopefully come up with a solution that makes managing plugins a bit more seamless so that users don't have to worry about compiling, etc... but I think for now at least we're not going to be merging new builders until that path forward has been figured out.

I'm happy to leave this open while we're deliberating on that, but it'll be a while and my suspicion at this point is that we're going to end up saying "keep it separate as a third party builder that you (ZStack) maintain".

In the meantime, if you have a repo that currently provides the ZStack as a third party plugin, I'd love to link it in our docs so that users can find it. 

If you need help figuring out how to provide ZStack as a third party plugin, you can take a look at our docs page here: https://www.packer.io/docs/extending/plugins.html

Thanks for opening this!

**Comment by koven2049** [comment]
Thanks for your reply @SwampDragons .  I understand it's not an easy way to find out how to constraint the third party plugins. ZStack(https://github.com/zstackio) is an open source IaaS platform also and we met the same problem before. I am a pleasure to handle our builder in my [repo](https://github.com/koven2049/packer/tree/master/builder/zstack) at present and to post a doc later. In the meanwhile I 'm sincerely to expect the official roadmap and wish to merge the ZStack builder anytime.

**Comment by SwampDragons** [comment]
We've officially decided to go the route of a "packer init" type feature, which we're hoping to roll out this year. With that in mind, I am going to close this PR, and I'll create a meta-issue to make sure that any builders added to our community pages get incorporated into the registry we create. 

I would be happy to help you convert your builder into a third party plugin, or you can refer to our docs on how to do so: https://www.packer.io/docs/extending/plugins.html

It is worth noting that some of the interfaces changed between when you opened this PR and now; in order to get your plugin working you will want to take a look at 

https://www.packer.io/guides/hcl/component-object-spec
and 
https://www.packer.io/docs/extending/custom-builders.html

Thanks for understanding, and let me know if I can be any help.

**Pull request closed without merging**
