### PR TITLE
website: Add community maintained IPSW data source Packer plugin

### PR DESCRIPTION
**Pull request by torarnv**

### CODE REVIEW

**Comment by torarnv** [comment]
Ping. What's needed to move this forward?  Thanks!

**Comment by torarnv** [comment]
@lbajolet-hashicorp @nywilken

**Review by lbajolet-hashicorp — APPROVED** [review]
Hi @torarnv,

Sorry for letting this one slide, I'll merge it today.

Please note however that we have changed our documentation practices recently, we don't have yet a documentation available for all the plugin developers to work with, but this will be published soon.
In the meantime, I'll merge your PR, and do the necessary steps on our infra code to make it accessible for users of the plugin.

Thanks!

**Comment by torarnv** [comment]
Thanks @lbajolet-hashicorp !

**Comment by torarnv** [comment]
@lbajolet-hashicorp Maybe I misunderstood, but were https://github.com/hashicorp/packer/pull/12648 and https://github.com/hashicorp/packer/pull/12647 the parts that made the plugin docs available in the current doc infra? It doesn't seem to pop up in the preview at https://packer-4c6dbhdhh-hashicorp.vercel.app/packer/integrations?tiers=community&components=data-source, nor in the current official docs at https://developer.hashicorp.com/packer/integrations?product_intent=packer&tiers=community&components=data-source 

No rush, just trying to understand where to look/find them at some point 😃

**Comment by lbajolet-hashicorp** [comment]
Hi @torarnv,

So, in the past you'd have just needed to merge this, and we'd backport it to the website for it to be available, and it would happen in a not too long delay (depends on when the docs get refreshed based on that branch).

Nowadays with the `Integrations` workflow, we're changing this a bit, and as I mentioned in my previous comment, this will have an impact on your repo once it's generally available, but in the meantime you did all you had to do for now, I've opened a PR on an internal project to add your repo to the list of integrations, and once it's available you'll be able to access the docs from the `Integrations` tab on the docs site.

In the meantime, I would think you can access the docs directly, they should already be available (can confirm they are: https://developer.hashicorp.com/packer/plugins/datasources/ipsw). They will become more visible once the PR I opened is merged, and we'll update the docs guides to account for the changes we made in order to adopt the new docs system.

Hope that helps, I would expect the plugin to be visible by next week, but please feel free to reping us on this PR by late next week if it's still not there, at that point we'll see what we can do to unblock that.

**Comment by torarnv** [comment]
Awesome, thank you so much @lbajolet-hashicorp <3

**Pull request merged**
