### PR TITLE
Enable implicit plugins

### PR DESCRIPTION
**Pull request by lbajolet-hashicorp**
As we continue working towards bundled plugins removal, we enable implicitly required plugins.

This automatically installs the missing plugins when invoking `packer init` on an HCL2 template which relies on a known, official, component, and gives guidance to users that they are relying on plugins which will no longer be part of Packer in the next minor version: v1.10.0.

# Example:

## build.pkr.hcl

```hcl
source "amazon-ebs" "test" {
  ami_name      = "test-amazon-ebs-packer-implicit-plugin"
  instance_type = "m3.medium"
  region        = "us-east-1"
  source_ami    = "ami-76b2a71e"
  ssh_username  = "ubuntu"
}

source "qemu" "autogenerated_2" {
}

build {
  sources = ["source.amazon-ebs.test", "source.qemu.autogenerated_2"]

  provisioner "ansible-local" {
  }

  post-processor "googlecompute-import" {
  }
}
```

## packer build

```shell-session
$ packer build build.pkr.hcl
Warning: Bundled plugins used

This template relies on the use of plugins bundled into the Packer binary.
The practice of bundling external plugins into Packer will be removed in an
upcoming version.

To remove this warning, add the following section to your template:

packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
    qemu = {
      source  = "github.com/hashicorp/qemu"
      version = "~> 1"
    }
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}

Then run 'packer init' to manage installation of the plugins

[...]
```

## packer init

```shell-session
$ packer init build.pkr.hcl
Installed implicitly required plugin github.com/hashicorp/amazon v1.2.6 in "[...]/.packer.d/plugins/github.com/hashicorp/amazon/packer-plugin-amazon_v1.2.6_x5.0_linux_amd64"
Installed implicitly required plugin github.com/hashicorp/ansible v1.1.0 in "[...]/packer.d/plugins/github.com/hashicorp/ansible/packer-plugin-ansible_v1.1.0_x5.0_linux_amd64"
Installed implicitly required plugin github.com/hashicorp/googlecompute v1.1.1 in "[...]/.packer.d/plugins/github.com/hashicorp/googlecompute/packer-plugin-googlecompute_v1.1.1_x5.0_linux_amd64"

Warning, at least one component used in your config file(s) has moved out of Packer and is now being implicitly required. 
For more details on implicitly required plugins see https://packer.io/docs/commands/init#implicit-required-plugin

To avoid any backward incompatible changes with your
config file you may want to lock the plugin version by pasting the following to your config:

packer {
  required_plugins {

    "amazon" = {
      source = "github.com/hashicorp/amazon"
      version = "v1.2.6"
    }

    "ansible" = {
      source = "github.com/hashicorp/ansible"
      version = "v1.1.0"
    }

    "googlecompute" = {
      source = "github.com/hashicorp/googlecompute"
      version = "v1.1.1"
    }

  }
}
```

NOTE: In the latter example `qemu` is not being installed since I had it installed locally, and it got discovered, hence why we don't see it in the suggested warning (or in the installed plugins). We can iterate on this if this is relevant.

### CODE REVIEW

**Comment by nywilken** [comment]
> This automatically installs the missing plugins when invoking packer init on an HCL2 template which relies on a known, official, component

I'm still working through this review but I do wonder if there should be a flag to not auto install especially since Packer is still shipping with the bundled plugins. What do you think? 

When the plugins are removed from the binary will have to install the plugins in order to resolve the issue. So the story might be slightly different and would warrant a manual install or required plugins block.

**Comment by nywilken** [comment]
> NOTE: In the latter example qemu is not being installed since I had it installed locally, and it got discovered, hence why we don't see it in the suggested warning (or in the installed plugins). We can iterate on this if this is relevant.

Again dropping before fully reviewing. Is the locally installed version of qemu one that was installed via a previous `packer init` or `packer plugins install`? 

Locally installed plugins via `make dev` or manually installed plugins that do not match the version constraint format will fail to load once a user moves to using a `required_plugin` block. Maybe a workflow that needs some consideration from our end.

**Comment by lbajolet-hashicorp** [comment]
> > This automatically installs the missing plugins when invoking packer init on an HCL2 template which relies on a known, official, component
> 
> I'm still working through this review but I do wonder if there should be a flag to not auto install especially since Packer is still shipping with the bundled plugins. What do you think?
> 
> When the plugins are removed from the binary will have to install the plugins in order to resolve the issue. So the story might be slightly different and would warrant a manual install or required plugins block.

I'm not sure about the flag in this case, if a user invokes `packer init`, I would think they expect packer to manage their plugins for them (which to this day is the only purpose of the command), so I don't think this is too far of a stretch to have packer install and warn about the missing plugins, even while we bundle them in the binary.
The flag certainly won't hurt though, but I'm not sure it is needed.

> > NOTE: In the latter example qemu is not being installed since I had it installed locally, and it got discovered, hence why we don't see it in the suggested warning (or in the installed plugins). We can iterate on this if this is relevant.
> 
> Again dropping before fully reviewing. Is the locally installed version of qemu one that was installed via a previous `packer init` or `packer plugins install`?

In my case, it's a locally compiled plugin, installed without a version (since dev version), in `~/.packer.d/plugins`. So it is loaded, and that's why we don't see it in the message here.

> 
> Locally installed plugins via `make dev` or manually installed plugins that do not match the version constraint format will fail to load once a user moves to using a `required_plugin` block. Maybe a workflow that needs some consideration from our end.

Very true, I remember we talked about this, and I brought up maybe adding some `path` argument to the `required_plugins` block, so that we'd be able to point exactly to the executable file we want to use in this case. I feel this may also be useful for users who want to test a dev version of a plugin, but aren't sure where to place the actual binary to test it.
We can chat about this later if you think this may be a solution, or we can figure something else out.

**Comment by nywilken** [comment]
@lbajolet-hashicorp thanks for the work here. As we discussed internally let's mark this PR as invalid for not as the feature feels a bit contradictory to the work we've started with phasing out bundled plugins.
This implicit plugin work also doesn't account for users who need to manually install plugins, which is a valid use case, and further hinders the use of required_plugins since the only way to disable this featured would be to add a required_plugins block but if used with manually installed plugins it doesn't work. 

All that to say - this adds more work on the user than needed. So punting 🏈 🦶 in favor of instrumentation for bundle plugin loading.

**Pull request closed without merging**
