### PR TITLE
update aliyungo common package

### LINKED ISSUE #6149: Unknown region alicloud - ap-southeast-5
- Packer version 1.2.2
- Mac OS

 I got 
```
Errors validating build 'packer_redis'. 1 error(s) occurred:

* Unknown alicloud region: ap-southeast-5
```
when trying to run `packer validate base.json` for creating image in alicloud with region ap-southeast-5, but actually the region is stated here https://github.com/denverdino/aliyungo/blob/master/common/regions.go#L21

### PR DESCRIPTION
**Pull request by LieAlbertTriAdrian**
## Problems ##
- We cannot validate packer image for several regions in alicloud
- We cannot build packer image for several regions in alicloud

## Solutions ##
- Update the alicloud common package that contains the logic for checking region validity
- Run the make file to make sure all unit test passed and the updates won't cause any breaking change

## Notes ##
This will close #6149, as ap-southeast-5 region is also included.

### CODE REVIEW

**Comment by LieAlbertTriAdrian** [comment]
## Test Result ##
==> Checking that code complies with gofmt requirements...
Check passed.
ok  	github.com/hashicorp/packer	0.102s
ok  	github.com/hashicorp/packer/builder/alicloud/ecs	0.067s
ok  	github.com/hashicorp/packer/builder/amazon/chroot	0.040s
ok  	github.com/hashicorp/packer/builder/amazon/common	0.078s
ok  	github.com/hashicorp/packer/builder/amazon/ebs	0.028s
ok  	github.com/hashicorp/packer/builder/amazon/ebssurrogate	0.022s
ok  	github.com/hashicorp/packer/builder/amazon/ebsvolume	0.076s
ok  	github.com/hashicorp/packer/builder/amazon/instance	0.047s
ok  	github.com/hashicorp/packer/builder/azure/arm	3.200s
ok  	github.com/hashicorp/packer/builder/azure/common	0.017s
?   	github.com/hashicorp/packer/builder/azure/common/constants	[no test files]
?   	github.com/hashicorp/packer/builder/azure/common/lin	[no test files]
?   	github.com/hashicorp/packer/builder/azure/common/logutil	[no test files]
ok  	github.com/hashicorp/packer/builder/azure/common/template	0.035s
ok  	github.com/hashicorp/packer/builder/azure/pkcs12	0.370s
ok  	github.com/hashicorp/packer/builder/azure/pkcs12/rc2	0.014s
ok  	github.com/hashicorp/packer/builder/cloudstack	0.035s
ok  	github.com/hashicorp/packer/builder/digitalocean	0.082s
ok  	github.com/hashicorp/packer/builder/docker	0.033s
ok  	github.com/hashicorp/packer/builder/file	0.017s
ok  	github.com/hashicorp/packer/builder/googlecompute	6.908s
ok  	github.com/hashicorp/packer/builder/hyperv/common	0.025s
ok  	github.com/hashicorp/packer/builder/hyperv/iso	0.062s
ok  	github.com/hashicorp/packer/builder/hyperv/vmcx	0.092s
ok  	github.com/hashicorp/packer/builder/lxc	0.032s
ok  	github.com/hashicorp/packer/builder/lxd	0.060s
ok  	github.com/hashicorp/packer/builder/ncloud	0.070s
ok  	github.com/hashicorp/packer/builder/null	0.064s
ok  	github.com/hashicorp/packer/builder/oneandone	0.022s
ok  	github.com/hashicorp/packer/builder/openstack	0.072s
ok  	github.com/hashicorp/packer/builder/oracle/classic	0.029s
?   	github.com/hashicorp/packer/builder/oracle/common	[no test files]
ok  	github.com/hashicorp/packer/builder/oracle/oci	7.007s
ok  	github.com/hashicorp/packer/builder/oracle/oci/client	7.411s
ok  	github.com/hashicorp/packer/builder/parallels/common	2.543s
ok  	github.com/hashicorp/packer/builder/parallels/iso	0.025s
ok  	github.com/hashicorp/packer/builder/parallels/pvm	0.025s
ok  	github.com/hashicorp/packer/builder/profitbricks	0.024s
ok  	github.com/hashicorp/packer/builder/qemu	0.050s
ok  	github.com/hashicorp/packer/builder/scaleway	0.074s
ok  	github.com/hashicorp/packer/builder/triton	0.037s
ok  	github.com/hashicorp/packer/builder/virtualbox/common	5.549s
ok  	github.com/hashicorp/packer/builder/virtualbox/iso	0.083s
ok  	github.com/hashicorp/packer/builder/virtualbox/ovf	0.025s
ok  	github.com/hashicorp/packer/builder/vmware/common	5.195s
ok  	github.com/hashicorp/packer/builder/vmware/iso	0.034s
ok  	github.com/hashicorp/packer/builder/vmware/vmx	0.020s
ok  	github.com/hashicorp/packer/command	1.420s
ok  	github.com/hashicorp/packer/common	0.070s
ok  	github.com/hashicorp/packer/common/json	0.006s [no tests to run]
ok  	github.com/hashicorp/packer/common/powershell	0.007s
?   	github.com/hashicorp/packer/common/powershell/hyperv	[no test files]
?   	github.com/hashicorp/packer/common/ssh	[no test files]
ok  	github.com/hashicorp/packer/common/uuid	0.010s
ok  	github.com/hashicorp/packer/communicator/none	0.011s
ok  	github.com/hashicorp/packer/communicator/ssh	0.080s
ok  	github.com/hashicorp/packer/communicator/winrm	0.065s
ok  	github.com/hashicorp/packer/fix	0.036s
ok  	github.com/hashicorp/packer/helper/builder/testing	0.061s
?   	github.com/hashicorp/packer/helper/common	[no test files]
ok  	github.com/hashicorp/packer/helper/communicator	0.049s
ok  	github.com/hashicorp/packer/helper/config	0.012s
?   	github.com/hashicorp/packer/helper/enumflag	[no test files]
ok  	github.com/hashicorp/packer/helper/flag-kv	0.012s
ok  	github.com/hashicorp/packer/helper/flag-slice	0.012s
ok  	github.com/hashicorp/packer/helper/multistep	0.135s
ok  	github.com/hashicorp/packer/helper/useragent	0.012s
ok  	github.com/hashicorp/packer/packer	0.315s
ok  	github.com/hashicorp/packer/packer/plugin	0.422s
ok  	github.com/hashicorp/packer/packer/rpc	0.152s
ok  	github.com/hashicorp/packer/plugin/example	0.025s [no tests to run]
?   	github.com/hashicorp/packer/post-processor/alicloud-import	[no test files]
?   	github.com/hashicorp/packer/post-processor/amazon-import	[no test files]
ok  	github.com/hashicorp/packer/post-processor/artifice	0.019s [no tests to run]
ok  	github.com/hashicorp/packer/post-processor/atlas	1.456s
ok  	github.com/hashicorp/packer/post-processor/checksum	0.054s
ok  	github.com/hashicorp/packer/post-processor/compress	0.046s
ok  	github.com/hashicorp/packer/post-processor/docker-import	0.023s
ok  	github.com/hashicorp/packer/post-processor/docker-push	0.054s
ok  	github.com/hashicorp/packer/post-processor/docker-save	0.063s
ok  	github.com/hashicorp/packer/post-processor/docker-tag	0.061s
ok  	github.com/hashicorp/packer/post-processor/googlecompute-export	0.064s [no tests to run]
?   	github.com/hashicorp/packer/post-processor/manifest	[no test files]
ok  	github.com/hashicorp/packer/post-processor/shell-local	0.115s
ok  	github.com/hashicorp/packer/post-processor/vagrant	0.040s
ok  	github.com/hashicorp/packer/post-processor/vagrant-cloud	0.027s
ok  	github.com/hashicorp/packer/post-processor/vsphere	0.055s
?   	github.com/hashicorp/packer/post-processor/vsphere-template	[no test files]
ok  	github.com/hashicorp/packer/provisioner	0.021s
ok  	github.com/hashicorp/packer/provisioner/ansible	0.316s
ok  	github.com/hashicorp/packer/provisioner/ansible-local	0.062s
ok  	github.com/hashicorp/packer/provisioner/chef-client	0.035s
ok  	github.com/hashicorp/packer/provisioner/chef-solo	0.039s
ok  	github.com/hashicorp/packer/provisioner/converge	0.017s
ok  	github.com/hashicorp/packer/provisioner/file	0.064s
ok  	github.com/hashicorp/packer/provisioner/powershell	0.281s
ok  	github.com/hashicorp/packer/provisioner/puppet-masterless	0.076s
ok  	github.com/hashicorp/packer/provisioner/puppet-server	0.063s
ok  	github.com/hashicorp/packer/provisioner/salt-masterless	0.025s
ok  	github.com/hashicorp/packer/provisioner/shell	0.028s
ok  	github.com/hashicorp/packer/provisioner/shell-local	0.031s
ok  	github.com/hashicorp/packer/provisioner/windows-restart	3.207s
ok  	github.com/hashicorp/packer/provisioner/windows-shell	0.185s
?   	github.com/hashicorp/packer/scripts	[no test files]
ok  	github.com/hashicorp/packer/template	0.028s
ok  	github.com/hashicorp/packer/template/interpolate	0.016s
?   	github.com/hashicorp/packer/version	[no test files]

**Comment by mwhooker** [comment]
thanks!

**Comment by LieAlbertTriAdrian** [comment]
@mwhooker Your welcome! Anyway for this fix, when will this be released? And in what version of packer?

**Comment by mwhooker** [comment]
next release is 1.2.3 and should be out in a week or so

**Pull request merged**
