### PR TITLE
Add support for specifying vGPU profiles

### LINKED ISSUE #8872: Adding vGPU option for vsphere-iso builder
#### Feature Description

When building a Virtual Machine on vSphere, it would be great if we could add a vGPU (PCIe device). 

#### Use Case(s)

It's getting more and more common on VDI and AI/ML workload.

### PR DESCRIPTION
**Pull request by thor**
Adds the field `vgpu_profile` to `vsphere-iso` and `vsphere-clone` to enable building templates with NVIDIA GRID vGPU backing.

_I would love feedback on how to improve it, and even how to move forward with acceptance tests if that's interesting._

## Motivation

We originally started using Packer to build our internal templates for VDI usage, creating a pipeline from commit to finished VDI available to end-users. Currently we use custom PowerShell-modules to finish the last mile, but we'd like to reduce that where possible and let Packer do what Packer's great at.

## Questions

- ~How should I best separate between the private functions on `VirtualMachine` and the public ones?~
- ~Perhaps I should look at the Packer step-flow? I probably should.~
- Any terse/short pointers on what to do for something like this that introduces a property for both cloning and fresh builds?
- Should I create acceptance tests for adding vGPU profiles?
  - Determine if hardware exists for acceptance tests
- Are there mock tests used?

## Tasks

- [x] Get it working for `vsphere-iso`
- [x] Get it working for `vsphere-clone`
- [x] Evaluate possibility for adding vGPU device _after_ provisioning
  - This would have to be a separate issue, as much as we'd want this.
- [x] Add documentation

Closes #8872
Closes jetbrains-infra/packer-builder-vsphere#208

### CODE REVIEW

**Comment by thor** [comment]
Requesting a review on this; I'll happily squash and reword the commits to be a bit more descriptive, but I'll leave that for later. :+1:

**Comment by KaiserThaws** [comment]
Hello,

Thanks for taking care of this !
If you need some infra to try it. I can do a bunch of tests on ours. 
Let me know

**Comment by KaiserThaws** [comment]
> @KaiserThaws if you need a binary to test, do let me know. I did a quick test locally and had no issues creating a `vsphere-iso` builder that added the driver successfully. Even gave a sensible error message at first because all of our profiles had been used up! :)
Hi @thor  !
Thanks ! yeah, it would be great !

**Comment by thor** [comment]
> > @KaiserThaws if you need a binary to test, do let me know. I did a quick test locally and had no issues creating a `vsphere-iso` builder that added the driver successfully. Even gave a sensible error message at first because all of our profiles had been used up! :)
> 
> Hi @thor !
> Thanks ! yeah, it would be great !

@KaiserThaws you should be able to use the [artifacts listed on CircleCI for the build](https://circleci.com/gh/hashicorp/packer/41732#artifacts/containers/0).

**Comment by SwampDragons** [comment]
The conflict can probably be solved by rebasing on master. @KaiserThaws if you can confirm this works as expected for you, I'll merge.

**Comment by KaiserThaws** [comment]
> The conflict can probably be solved by rebasing on master. @KaiserThaws if you can confirm this works as expected for you, I'll merge.

Yes ! it works like a charm 👍 
Thanks @thor

**Comment by thor** [comment]
@KaiserThaws thanks for testing!

@SwampDragons Rebased! :heavy_check_mark: I see there are builders with tests for validating that the builder-specific configuration parameters work, whereas there are still disabled acceptance tests from JetBrains in `vsphere-iso` and `vsphere-clone`. If you don't mind me asking, would you prefer I add acceptance tests for something like this, or should I just take a look at implementing validation/unit tests instead due to the issue of testing and validating with GPU resources? 

If the latter, are there any particular pointers to follow, or would looking at other builders be the best starting point?

**Comment by SwampDragons** [comment]
Normally I'd just add a unit test for that driver code, but we don't have mocks for that driver and it's third party code without an interface so it's probably easier just to add an acceptance test. I'll be re-enabling them shortly; we've been doing a big overhaul of our acceptance testing setup.

**Comment by thor** [comment]
@SwampDragons In that case, what do you think of going ahead with the merge and then creating a new issue for tracking the acceptance testing for `vsphere-*`?

**Comment by SwampDragons** [comment]
That sounds good. I'll do a quick manual test and then merge.

**Pull request merged**
