### PR TITLE
fix docker email fixer

### LINKED ISSUE #6660: Post processor validator regression: "expected a map, got 'slice'"
I went to test out the new `split` function, and found out the hard way that `packer validate` is rejecting perfectly valid templates. (Or at least they were valid in the past, and seem to build just fine.)

Packer seems to be getting hung up on the nested arrays used by post processor configurations. Removing the nested array allows the template to validate, but doesn't actually work. Keeping the nested array will work during a `packer build`, but still fail to validate with an error that which says `expected a map, got 'slice'` ...

To illustrate, the following sample will fail validation, but build just fine:
```json 
"post-processors": [
      [
              {
                "type": "vagrant",
                "compression_level": 9,
                "vagrantfile_template": "tpl/{{split build_name \"-\" 1}}.rb",
                "output": "output/{{build_name}}-{{user `box_version`}}.box",
                "include": [
                  "tpl/generic/info.json"
                ]
            },
            {
                "type": "vagrant-cloud",
                "box_tag": "generic/{{split build_name \"-\" 1}}",
                "version": "{{user `box_version`}}",
                "version_description": "A build environment for use in cross platform development."
            }
        ]
      ]
```
  
While the following (note the only different is a set of brackets) will validate, but fails with the error `Post-processor failed: Unknown artifact type, requires box from vagrant post-processor: mitchellh.vmware` during post-processing:

```json
  "post-processors": [
              {
                "type": "vagrant",
                "compression_level": 9,
                "vagrantfile_template": "tpl/{{split build_name \"-\" 1}}.rb",
                "output": "output/{{build_name}}-{{user `box_version`}}.box",
                "include": [
                  "tpl/generic/info.json"
                ]
            },
            {
                "type": "vagrant-cloud",
                "box_tag": "generic/{{split build_name \"-\" 1}}",
                "version": "{{user `box_version`}}",
                "version_description": "A build environment for use in cross platform development."
            }
        ]
```
  
If your going to write a unit test based on this, might I suggest it include multiple post processor pipelines, like so:

```json
  "post-processors": [
      [
              {
                "type": "vagrant",
                "compression_level": 9,
                "vagrantfile_template": "tpl/{{split build_name \"-\" 1}}.rb",
                "output": "output/{{build_name}}-{{user `box_version`}}.box",
                "include": [
                  "tpl/generic/info.json"
                ]
            },
            {
                "type": "vagrant-cloud",
                "box_tag": "generic/{{split build_name \"-\" 1}}",
                "version": "{{user `box_version`}}",
                "version_description": "A build environment for use in cross platform development."
            }
        ],
        [
            {
                "type": "artifice",
                "keep_input_artifact": true,
                "files": [
                    "output/{{build_name}}-{{user `box_version`}}.box"
                ]
            },
            {
                "type": "checksum",
                "checksum_types": [
                    "sha256"
                ],
                "keep_input_artifact": true,
                "output": "output/{{build_name}}-{{user `box_version`}}.box.sha256"
            }
        ]
      ]
```

The obligatory data follows.

- Packer version from `packer version`
packer version v1.2.6-dev 819bda50d5050c015077089f01feee29b73341df
  
- Host platform
Linux
  
- Debug log output from `PACKER_LOG=1 packer build template.json`.
```bash
[ladar@darla robox]$ PACKER_LOG=1
[ladar@darla robox]$ packer validate generic-vmware.json
Error checking against fixers: 2 error(s) decoding:

* 'post-processors[0]' expected a map, got 'slice'
* 'post-processors[1]' expected a map, got 'slice'
```
  
- The example post processor from the vagrant cloud plugin documentation triggers this issue.
```json
"post-processors": [
    [
      {
        "type": "vagrant",
        "include": ["image.iso"],
        "vagrantfile_template": "vagrantfile.tpl",
        "output": "proxycore_{{.Provider}}.box"
      },
      {
        "type": "vagrant-cloud",
        "box_tag": "hashicorp/precise64",
        "access_token": "{{user `cloud_token`}}",
        "version": "{{user `version`}}"
      }
    ]
  ]
```

### PR DESCRIPTION
**Pull request by mwhooker**
Fixing post-processors requires some smart parsing of the template.
Let's turn that logic into a helper and use it everywhere.

Closes #6660

### CODE REVIEW

**Comment by mwhooker** [comment]
ah, good catch, thanks. A similar issue popped up before, so this is definitely an edge-casie area

**Comment by mwhooker** [comment]
good catch with that bug. I've pushed a fix, @ladar

**Comment by mwhooker** [comment]
actually this is still buggy. still working on it

**Comment by ladar** [comment]
@mwhooker take your time. When you think it's ready for review/merge let me know I can test it again.

Or if you want to give it a shot:

```bash
git clone https://github.com/lavabit/robox.git && cd robox
./robox.sh validate
```
Should work. You'll need a `.credentialsrc` file, but the script _should_ see that it's missing and create it.

**Comment by mwhooker** [comment]
> Should I also test packer build

hah, I appreciate the offer. This doesn't touch the build path so I don't think it's necessary.

Thanks again for all the help identifying this issue

**Pull request merged**
