### PR TITLE
Complete Atlas deprecation.

### PR DESCRIPTION
**Pull request by mwhooker**
Removes the push command and the Atlas post-processor.  Please see our
guide on building immutable infrastructure with Packer on CI/CD for
ideas on implementing these features yourself.
https://www.packer.io/guides/packer-on-cicd/

@SwampDragons Please take a look at this and let me know if you think it's complete or if I'm missing anything.

### CODE REVIEW

**Comment by SwampDragons** [comment]
Found a few things that look like they also need to go: 

https://github.com/hashicorp/packer/blob/atlas-deprecation/command/test-fixtures/fix/template.json#L4
https://github.com/hashicorp/packer/blob/atlas-deprecation/contrib/zsh-completion/_packer#L8
https://github.com/hashicorp/packer/blob/atlas-deprecation/packer/core.go#L305-L308
https://github.com/hashicorp/packer/blob/atlas-deprecation/packer/core_test.go#L429-L461
https://github.com/hashicorp/packer/blob/atlas-deprecation/packer/test-fixtures/push-vars.json
https://github.com/hashicorp/packer/blob/atlas-deprecation/template/parse.go#L27
https://github.com/hashicorp/packer/blob/atlas-deprecation/template/parse.go#L188-L196
https://github.com/hashicorp/packer/blob/atlas-deprecation/template/parse_test.go#L299-L305
https://github.com/hashicorp/packer/blob/atlas-deprecation/template/template.go#L57-L66
https://github.com/hashicorp/packer/blob/atlas-deprecation/template/template.go#L25
https://github.com/hashicorp/packer/blob/atlas-deprecation/template/test-fixtures/parse-push.json

**Comment by SwampDragons** [comment]
Other than those files above, what you've removed looks good to me. I notice the website stuff is included here -- did you just deploy the web changes and wait to merge them with master for this PR?

**Comment by mwhooker** [comment]
Good catch with all those links. Will take care of some of the stuff I missed.

I'm not sure I want to remove the code for parsing the push config. It's like when you get shot it's usually safer to just leave the bullet in place. If someone has a push stanza in their config, and are not running `packer push`, I don't want to break their build without good reason.

What do you think?

**Comment by SwampDragons** [comment]
That's a hilarious metaphor. I can respect that call. Makes sense. Long-term maybe we'll clean it out.

**Pull request merged**
