### PR TITLE
Wait until source instance OK before continuing

### LINKED ISSUE #5627: Packer uses private IP (and fails) when building on C5.* instance
I'm unable to launch and provision a `c5.large` instance type in AWS. These were recently released by AWS - https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-amazon-ec2-c5-instances-the-next-generation-of-compute-optimized-instances/ and https://aws.amazon.com/blogs/aws/now-available-compute-intensive-c5-instances-for-amazon-ec2/ - and are notable that they _require_ `ena` support: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html

i.e., `"ena_support": true`

When launching a `c5.large` instance, packer times out trying to SSH to the _private_ IP address in the subnet, despite a public address existing (and `"associate_public_ip_address": true` in the config). I can confirm that the public IP address is set and can connect to it via SSH without packer.

An `i3.large` instance type, also with `"ena_support": true`, is successful.

- `packer version`: 

```
$ packer --version
1.1.3
```
(built from `master`, with `HEAD` at `61d8274096e3af1173850714b7f91afe4878e432`)

- Host platform

OSX Sierra 10.12.6
```
$ go version
go version go1.9.1 darwin/amd64
```

- Gist of *unsuccessful* run - `"instance_type": "c5.large"`: https://gist.github.com/nyetsche/9ad9a667f19c6b251c9bbc1f4461c4e6

- Gist of *successful* run - "instance_type": "i3.large"`:
https://gist.github.com/nyetsche/e6624750ddbadbddd6d6476410299608

Template file that will reproduce:

`ami-c998b6b2` is RHEL7, `RHEL-7.4_HVM_GA-20170808-x86_64-2-Hourly2-GP2 (ami-c998b6b2)` in `us-east-1`

```
{
  "builders": [
    {
      "type": "amazon-ebs",
      "ami_name": "packer-c5-ami",
      "region": "us-east-1",
      "associate_public_ip_address": true,
      "sriov_support": true,
      "ena_support": true,
      "instance_type": "c5.large",
      "ssh_username": "ec2-user",
      "ssh_pty": true,
      "ssh_timeout": "5m",
      "vpc_id": "VPC-id",
      "subnet_id": "VPC-subnet",
      "security_group_id": "SG-with-ssh",
      "source_ami": "ami-c998b6b2"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "echo SSH test successful"
      ]
    }
  ]
}
```

Change `c5.large` to `i3.large` and packer will connect successfully.

### PR DESCRIPTION
**Pull request by mwhooker**
Closes #5627

Seems to work every time for me. If anyone wants to confirm that would be appreciated!

### CODE REVIEW

**Comment by mwhooker** [comment]
oh I should do this to `builder/amazon/common/step_run_spot_instance.go` too

**Comment by mwhooker** [comment]
really working to restrain myself from removing all the custom state change code

**Comment by SwampDragons** [comment]
This seems clean, simple, and way better.  👍 I tested on the c5 instance example, as well with a few other aws repro cases I have lying around; it all seems good.  Interestingly, it takes longer than our old wait for these windows instances, pushing back the amount of time we wait for winRM to connect... meaning this change might resolve some other random flakiness that occurs from trying to connect too early.

**Comment by elisiano** [comment]
I am assuming this change is responsible for the error I'm facing right now, but I'm not 100% certain of it.
```
Error waiting for instance (i-XXXX) to become ready: ResourceNotReady: exceeded wait attempts
```
The instance is up, everything is ready but it would not appear that packer is able to identify that.
I've also enable `-debug` which saves the temporary key in the current directory and attempted an ssh while packer was waiting for it. That worked.
Additionally I also tested aws cli with: `aws ec2 wait instance-running --instance-ids i-XXXX` and also exited with 0 once the instance was running (yet packer was still waiting).

Switching back to packer v1.1.2 everything works as expected.
Logs are not very useful, please find below an excerpt ran with the environment variable `PACKER_LOG=1` and the `-debug` flag.

```
[...]
2017/12/18 10:37:01 ui:     centos-6-goldmaster: Adding tag: "Name": "Packer Builder"
    centos-6-goldmaster: Adding tag: "Name": "Packer Builder"
2017/12/18 10:37:03 ui:     centos-6-goldmaster: Instance ID: i-01a3ad1f2409ac0c6
    centos-6-goldmaster: Instance ID: i-01a3ad1f2409ac0c6
2017/12/18 10:37:03 ui: ==> centos-6-goldmaster: Waiting for instance (i-01a3ad1f2409ac0c6) to become ready...
==> centos-6-goldmaster: Waiting for instance (i-01a3ad1f2409ac0c6) to become ready...
2017/12/18 10:47:23 ui error: ==> centos-6-goldmaster: Error waiting for instance (i-01a3ad1f2409ac0c6) to become ready: ResourceNotReady: exceeded wait attempts
2017/12/18 10:47:23 ui: ==> centos-6-goldmaster: Terminating the source AWS instance...
==> centos-6-goldmaster: Error waiting for instance (i-01a3ad1f2409ac0c6) to become ready: ResourceNotReady: exceeded wait attempts
==> centos-6-goldmaster: Terminating the source AWS instance...
2017/12/18 10:47:25 packer: 2017/12/18 10:47:25 Waiting for state to become: terminated
2017/12/18 10:47:25 packer: 2017/12/18 10:47:25 Using 2s as polling delay (change with AWS_POLL_DELAY_SECONDS)
2017/12/18 10:47:25 packer: 2017/12/18 10:47:25 Allowing 300s to complete (change with AWS_TIMEOUT_SECONDS)
2017/12/18 10:47:55 ui: ask: ==> centos-6-goldmaster: Pausing before cleanup of step 'stepCleanupVolumes'. Press enter to continue.
==> centos-6-goldmaster: Pausing before cleanup of step 'stepCleanupVolumes'. Press enter to continue.
2017/12/18 10:48:48 ui: ==> centos-6-goldmaster: No volumes to clean up, skipping
==> centos-6-goldmaster: No volumes to clean up, skipping
2017/12/18 10:48:48 ui: ask: ==> centos-6-goldmaster: Pausing before cleanup of step 'StepSecurityGroup'. Press enter to continue.
==> centos-6-goldmaster: Pausing before cleanup of step 'StepSecurityGroup'. Press enter to continue.
2017/12/18 10:48:48 ui: ==> centos-6-goldmaster: Deleting temporary security group...
==> centos-6-goldmaster: Deleting temporary security group...
2017/12/18 10:48:50 ui: ask: ==> centos-6-goldmaster: Pausing before cleanup of step 'StepKeyPair'. Press enter to continue.
==> centos-6-goldmaster: Pausing before cleanup of step 'StepKeyPair'. Press enter to continue.
2017/12/18 10:48:50 ui: ==> centos-6-goldmaster: Deleting temporary keypair...
==> centos-6-goldmaster: Deleting temporary keypair...
2017/12/18 10:48:51 ui: ask: ==> centos-6-goldmaster: Pausing before cleanup of step 'StepSourceAMIInfo'. Press enter to continue.
==> centos-6-goldmaster: Pausing before cleanup of step 'StepSourceAMIInfo'. Press enter to continue.
2017/12/18 10:48:51 ui: ask: ==> centos-6-goldmaster: Pausing before cleanup of step 'StepPreValidate'. Press enter to continue.
==> centos-6-goldmaster: Pausing before cleanup of step 'StepPreValidate'. Press enter to continue.
2017/12/18 10:48:52 [INFO] (telemetry) ending amazon-ebs
2017/12/18 10:48:52 [INFO] (telemetry) found error: Error waiting for instance (i-01a3ad1f2409ac0c6) to become ready: ResourceNotReady: exceeded wait attempts
2017/12/18 10:48:52 ui error: Build 'centos-6-goldmaster' errored: Error waiting for instance (i-01a3ad1f2409ac0c6) to become ready: ResourceNotReady: exceeded wait attempts
2017/12/18 10:48:52 Waiting on builds to complete...
2017/12/18 10:48:52 Builds completed. Waiting on interrupt barrier...
2017/12/18 10:48:52 machine readable: error-count []string{"1"}
2017/12/18 10:48:52 ui error:
==> Some builds didn't complete successfully and had errors:
2017/12/18 10:48:52 machine readable: centos-6-goldmaster,error []string{"Error waiting for instance (i-01a3ad1f2409ac0c6) to become ready: ResourceNotReady: exceeded wait attempts"}
2017/12/18 10:48:52 ui error: --> centos-6-goldmaster: Error waiting for instance (i-01a3ad1f2409ac0c6) to become ready: ResourceNotReady: exceeded wait attempts
2017/12/18 10:48:52 ui:
==> Builds finished but no artifacts were created.
2017/12/18 10:48:52 [INFO] (telemetry) Finalizing.
Build 'centos-6-goldmaster' errored: Error waiting for instance (i-01a3ad1f2409ac0c6) to become ready: ResourceNotReady: exceeded wait attempts

==> Some builds didn't complete successfully and had errors:
--> centos-6-goldmaster: Error waiting for instance (i-01a3ad1f2409ac0c6) to become ready: ResourceNotReady: exceeded wait attempts
[...]
```

**Comment by SwampDragons** [comment]
@elisiano You're right, and we're tracking this in https://github.com/hashicorp/packer/issues/5705

**Pull request merged**
