### PR TITLE
Support templates in YAML format - but don't advertise it

### PR DESCRIPTION
**Pull request by pdericson**
It's a bit rough but keen to hear feedback if you're interested in taking the patch

### CODE REVIEW

**Comment by leroux** [comment]
Since I don't like staring at JSON, I wrote a little python script to read a Packer template in YAML format and then dump it to `packer build` in JSON. This works since JSON is a subset of YAML (1.2, iirc). In doing so, I could utilize YAML's [node anchors](http://yaml.org/spec/1.2/spec.html#id2785586). All valid JSON can be loaded by a YAML parser.

Packerfile.yml:
```yml
_ALIASES:
  - &default_builder_template
    disk_size: 40000
    headless: true

    http_directory: http
    iso_urls:
      - http://releases.ubuntu.com/14.04/ubuntu-14.04.2-server-amd64.iso
    iso_checksum: 83aabd8dcf1e8f469f3c72fff2375195
    iso_checksum_type: md5

    boot_wait: 15s
    boot_command:
      - <esc><esc><enter><wait>
      - '/install/vmlinuz noapic auto '
      - 'preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg '
      - 'debian-installer=en_US auto locale=en_US kbd-chooser/method=us '
      - 'hostname={{ .Name }} '
      - 'fb=false debconf/frontend=noninteractive '
      - 'keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA '
      - 'keyboard-configuration/variant=USA console-setup/ask_detect=false '
      - 'initrd=/install/initrd.gz -- '
      - <enter>

    ssh_username: '{{ user `ssh_user` }}'
    ssh_password: '{{ user `ssh_password` }}'
    ssh_port: 22
    ssh_wait_timeout: 30m

    shutdown_command: 'echo {{ user `ssh_password` }} | sudo -S shutdown -P now'
  
  - &execute_command 'chmod +x {{ .Path }}; echo {{ user `ssh_password` }} | {{ .Vars }} sudo -E -S {{ .Path }}'

builders:
  - <<: *default_builder_template
    name: ubuntu-vm-vmware
    type: vmware-iso
    guest_os_type: ubuntu-64
    vmx_data:
      cpuid.coresPerSocket: 1
      memsize: 1024
      numvcpus: 1

  - <<: *default_builder_template
    name: ubuntu-vm-virtualbox
    type: virtualbox-iso
    guest_os_type: Ubuntu_64
    vboxmanage:
      - [ "modifyvm", "{{.Name}}", "--memory", "512" ]
      - [ "modifyvm", "{{.Name}}", "--cpus", "1" ]

provisioners:
  - type: shell
    execute_command: *execute_command
    scripts:
      - scripts/base.sh

variables:
  ssh_user: ubuntu
  ssh_password: ubuntu
```

And then convert it into JSON in python with `json.dump(yaml.safe_load(packer_template), sys.stdout, indent=4)`, resulting in the following.

Packerfile.json:
```json
{
    "variables": {
        "ssh_user": "ubuntu",
        "ssh_password": "ubuntu"
    },
    "provisioners": [
        {
            "type": "shell",
            "execute_command": "chmod +x {{ .Path }}; echo {{ user `ssh_password` }} | {{ .Vars }} sudo -E -S {{ .Path }}",
            "scripts": [
                "scripts/base.sh"
            ]
        }
    ],
    "builders": [
        {
            "ssh_port": 22,
            "ssh_username": "{{ user `ssh_user` }}",
            "iso_checksum_type": "md5",
            "shutdown_command": "echo {{ user `ssh_password` }} | sudo -S shutdown -P now",
            "boot_command": [
                "<esc><esc><enter><wait>",
                "/install/vmlinuz noapic auto ",
                "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg ",
                "debian-installer=en_US auto locale=en_US kbd-chooser/method=us ",
                "hostname={{ .Name }} ",
                "fb=false debconf/frontend=noninteractive ",
                "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA ",
                "keyboard-configuration/variant=USA console-setup/ask_detect=false ",
                "initrd=/install/initrd.gz -- ",
                "<enter>"
            ],
            "guest_os_type": "ubuntu-64",
            "disk_size": 40000,
            "name": "ubuntu-vm-vmware",
            "iso_checksum": "83aabd8dcf1e8f469f3c72fff2375195",
            "boot_wait": "15s",
            "http_directory": "http",
            "vmx_data": {
                "cpuid.coresPerSocket": 1,
                "numvcpus": 1,
                "memsize": 1024
            },
            "headless": true,
            "iso_urls": [
              "http://releases.ubuntu.com/14.04/ubuntu-14.04.2-server-amd64.iso"
            ],
            "ssh_password": "{{ user `ssh_password` }}",
            "ssh_wait_timeout": "30m",
            "type": "vmware-iso"
        },
        {
            "ssh_port": 22,
            "ssh_username": "{{ user `ssh_user` }}",
            "iso_checksum_type": "md5",
            "shutdown_command": "echo {{ user `ssh_password` }} | sudo -S shutdown -P now",
            "vboxmanage": [
                [
                    "modifyvm",
                    "{{.Name}}",
                    "--memory",
                    "512"
                ],
                [
                    "modifyvm",
                    "{{.Name}}",
                    "--cpus",
                    "1"
                ]
            ],
            "boot_command": [
                "<esc><esc><enter><wait>",
                "/install/vmlinuz noapic auto ",
                "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg ",
                "debian-installer=en_US auto locale=en_US kbd-chooser/method=us ",
                "hostname={{ .Name }} ",
                "fb=false debconf/frontend=noninteractive ",
                "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA ",
                "keyboard-configuration/variant=USA console-setup/ask_detect=false ",
                "initrd=/install/initrd.gz -- ",
                "<enter>"
            ],
            "guest_os_type": "Ubuntu_64",
            "disk_size": 40000,
            "name": "ubuntu-vm-virtualbox",
            "iso_checksum": "83aabd8dcf1e8f469f3c72fff2375195",
            "boot_wait": "15s",
            "http_directory": "http",
            "headless": true,
            "iso_urls": [
                "http://releases.ubuntu.com/14.04/ubuntu-14.04.2-server-amd64.iso"
            ],
            "ssh_password": "{{ user `ssh_password` }}",
            "ssh_wait_timeout": "30m",
            "type": "virtualbox-iso"
        }
    ],
    "_ALIASES": [
        {
            "disk_size": 40000,
            "iso_checksum": "83aabd8dcf1e8f469f3c72fff2375195",
            "ssh_port": 22,
            "boot_wait": "15s",
            "http_directory": "http",
            "iso_checksum_type": "md5",
            "headless": true,
            "iso_urls": [
                "http://releases.ubuntu.com/14.04/ubuntu-14.04.2-server-amd64.iso"
            ],
            "ssh_password": "{{ user `ssh_password` }}",
            "ssh_username": "{{ user `ssh_user` }}",
            "shutdown_command": "echo {{ user `ssh_password` }} | sudo -S shutdown -P now",
            "boot_command": [
                "<esc><esc><enter><wait>",
                "/install/vmlinuz noapic auto ",
                "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg ",
                "debian-installer=en_US auto locale=en_US kbd-chooser/method=us ",
                "hostname={{ .Name }} ",
                "fb=false debconf/frontend=noninteractive ",
                "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA ",
                "keyboard-configuration/variant=USA console-setup/ask_detect=false ",
                "initrd=/install/initrd.gz -- ",
                "<enter>"
            ],
            "ssh_wait_timeout": "30m"
        },
        "chmod +x {{ .Path }}; echo {{ user `ssh_password` }} | {{ .Vars }} sudo -E -S {{ .Path }}"
    ]
}
```

I mainly did this to work around the fact that variables can only be scalars (I may be using the wrong word to refer to concrete values such as strings and numbers) and not collections, such as objects and lists.

This is mainly to convince you of choosing YAML as the format for Packer templates.

(This also pertains to #2441.)

**Comment by svpace** [comment]
Sorry about resurrecting the deceased here. I understand that accepting a new format is a big thing and all that, but it has been 2 years... even If YAML is not the best format, it does offer some advantages over the current format.

Code-wise, this PR is just a couple dozen lines of code. Wouldn't be possible to just accept this as is (may as an experimental feature) until the definitive format comes along?

**Comment by kidbrax** [comment]
any update on this?

**Comment by mwhooker** [comment]
we're not planning to support any alternate config format at the moment. We do plan to support HCL in the future

**Pull request closed without merging**
