### PR TITLE
Profitbricks builder fixes

### LINKED ISSUE #10548: ssh provisioning not working when using the profitbricks builder
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When trying to create an image using the profitbricks builder, provisioning fails due to ssh errors, even with the correct private key file path provided in the json spec.

#### Reproduction Steps

Run packer with the profitbricks builder and the "file" provisioner.

### Packer version

From `1.6.6`

### Simplified Packer Buildfile

```
{
  "builders": [
    {
      "url": "https://api.ionos.com/cloudapi/v5",
      "image": "ubuntu-20.04",
      "type": "profitbricks",
      "disk_size": "5",
      "snapshot_name": "test",
      "location": "de/fra",
      "ssh_username": "root",
      "ssh_password": "password",
      "communicator": "ssh",
      "ssh_private_key_file": "/Users/myuser/.ssh/id_rsa"
    }
  ],
  "provisioners": [
    {
      "type": "file",
      "source": "./welcome.txt",
      "destination": "/root/welcome.txt"
    }
  ]
}
```

### Operating system and Environment details

Tested on OSX and Linux

### Log Fragments and crash.log files

Logs can be found in this [gist](https://gist.github.com/mflorin/c60226cad3f6383d66f57613f3940d7a) .
The relevant message is 
```
[DEBUG] Detected authentication error. Increasing handshake attempts.
==> profitbricks: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

### PR DESCRIPTION
**Pull request by mflorin**
With this change we're fixing two profitbricks builder issues which prevent it from working properly:

1. An ssh connection cannot be established due to an erroneous handling of the private key file
   To fix this, we're now computing the public key based on the private key  stored in the communicator structure

2. After the ssh connection was fixed we discovered that provisioned file system changes do not end up in final image.
   This was happening because the changes where not flushed to disk before the server snapshot was taken.

Closes #10548

### CODE REVIEW

**Comment by azr** [comment]
Hello @jasmingacic, I see that you are the code owner of the profitbricks parts:

https://github.com/hashicorp/packer/blob/f578b93f7ecbf6d08aae52a932294739abb6157b/CODEOWNERS#L40-L41

Will you have time to review this PR ? Many thanks !

**Review by jasmingacic — APPROVED** [review]

**Comment by jasmingacic** [comment]
I'm no longer maintaining this but the fix you made is looking good. Also I would like to get another set of eyes to take a look at this.

**Comment by SwampDragons** [comment]
@jasmingacic Do you know who is maintaining this now? We should update the codeowners file.

**Comment by jasmingacic** [comment]
Probably check with Terraform provider the same people should be doing it.

**Comment by sylviamoss** [comment]
it seems that the @mflorin, the one who opened this PR, is one of the terraform's provider maintainers by looking at their [commit history](https://github.com/ionos-cloud/terraform-provider-profitbricks/commits/master).

**Comment by LiviusP** [comment]
Hi,

Yes, please add us as codeowners.

**Comment by mflorin** [comment]
> it seems that the @mflorin, the one who opened this PR, is one of the terraform's provider maintainers by looking at their [commit history](https://github.com/ionos-cloud/terraform-provider-profitbricks/commits/master), together with @LiviusP.
> If they confirm we can add them as the new codeowners.

Hello @sylviamoss. Yes, you can add us as code owners. Thank you.

**Comment by sylviamoss** [comment]
Nice! Thanks. I'll open a PR updating the codeowners file!

**Review by sylviamoss — APPROVED** [review]

**Pull request merged**
