### PR TITLE
Added monitoring and updated godo

### PR DESCRIPTION
**Pull request by lfarnell**
This PR mainly adds the ability to enable monitoring for the DigitalOcean builder. 

godo was also updated for monitoring support but due to library changes. In the process, some godo function calls need to be updated to support the new function calls.

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Thanks for the PR. This needs a update of the docs.

**Comment by rickard-von-essen** [comment]
Will the monitoring propagate to droplets created byt the resulting image?

**Comment by lfarnell** [comment]
@rickard-von-essen Yes it will. Anything inside the snapshot will be propagated to the droplets created from the snapshot. Same thing goes for private_networking

**Comment by rickard-von-essen** [comment]
Looks good but I like when `ctx` is inlined.

**Comment by lfarnell** [comment]
I'm new to Go, so do you mean ```a.client.Images.Delete(context.TODO(), a.snapshotId)```?

**Comment by rickard-von-essen** [comment]
Yes, but I'll just fixed it.

**Pull request merged**
