### PR TITLE
[WIP] Split up the VMware builder between its local and remote (esx5) components

### PR DESCRIPTION
**Pull request by arizvisa**
The way the VMware builders have evolved has resulted in two separate distinct driver types being integrated into the same builder. This results in the build steps for VMware being spotted with conditionals that fork the code path between whether to handle the remote (`esx5`) builder or a local builder.

This fork is done in 2 ways. One of them is a type assertion for "RemoteDriver" vs "LocalDriver", and the other is by checking the "RemoteType" for truth and executing a different path if so. The driver for a remote instance is actually implemented with a different interface so they might as well be separate components. This will allow for easier hacking of remote builder and hopefully the eventual stabilization of the local builders.

To accomplish this, this PR is literally shifting all the common code and that fork/split from the if-test/type-assertion within each build step into a completely separate builder. The intention is that none of the builder logic is really changed and everything will work the same except to access a remote driver, a user will use the `vmware-esx-{iso,vmx}` builders.

### CODE REVIEW

**Comment by arizvisa** [comment]
As mention in #6941, currently the following has been done:

- [x] Duplicate the `vmware` builder into a `vmxware-esx` builder
- [x] Remove non-esx conditionals from the `vmware-esx` builder
- [x] Remove esx conditionals from the `vmware-esx` builder
- [ ] Remove steps from `vmware-esx` that don't do anything
- [ ] Remove steps from the `vmware` builder that don't do anything
- [ ] Consolidate any common code from`vmware` that is used by the `vmware-esx` builder.
- [ ] Figure out how to remove options that don't make sense for the vmware-esx builder.
- [ ] Test the shit out of this
- [ ] Documentation, meh.

**Comment by SwampDragons** [comment]
If you run out of steam on this, let me know and I can add it to our roadmap for a couple releases down the road.

**Comment by arizvisa** [comment]
@SwampDragons, thx. Yeah, I'll be able to get back to this once I finish working on some work-related project. Probably will be able to get back to this next week or the week after.

**Comment by SwampDragons** [comment]
Awesome; no rush and no pressure on my end. I was just going through currently open PRs and checking up on status yesterday.

**Comment by arizvisa** [comment]
kk, good deal.

appreciate your patience ;)

**Comment by SwampDragons** [comment]
@arizvisa do you think you could send me an email?  megan at hashicorp.com . I'd like to have Hashicorp send you a little gift in thanks for all your contributions this year but I need some real life contact info from you.

**Comment by arizvisa** [comment]
I didn't forget about this, I'm almost done with what I'm currently working on. Didn't realize how crappy salt-stack's code base is as more than half the things that I had planned to use didn't even work. (Maybe one more week).

**Comment by arizvisa** [comment]
@SwampDragons, kind of a luddite irl and haven't checked my email since jan. I'll get it to you once I can get back to this PR.

**Comment by arizvisa** [comment]
Okay. Sorta back and able to work on this intermittently. I'll update my progress here as I make some.

**Comment by SwampDragons** [comment]
Untargeting this from 1.4.1. If you don't think you'll have time for this untangling (certainly not the most fun work to be done on Packer and at least I get paid to do it) then I can take this over from you.

**Comment by arizvisa** [comment]
Yeah, that's cool. I'm slowly chugging away at it. Sorry that it's been slow goin.

**Comment by arizvisa** [comment]
Just pushed my current progress. A lot of my current time is being spent on the testcases and such.

**Comment by SwampDragons** [comment]
No apologies necessary -- thanks for doing the work! Just keep me posted on what you need from me :)

**Comment by SwampDragons** [comment]
Since this PR has been running for so long, I think it's best to close for now and reopen when you've had more time to work on it. What do you think?

**Comment by arizvisa** [comment]
Yeah, that's probably a good idea. These Remote Desktop Protocol vulns came out in May and I've had to focus exclusively on them and haven't had a chance to deal with my VMs (or Packer) since then.

Also, when I first started this the split seemed straightforward since they're literally just conditionals checking for "esx5", by now there's probably some changes/refactors that'll require going back through the splitting of the testcases.

Sorry if y'all were waiting on this. I just finished wrapping up all of that RDP work that I had mentioned this past week, and will be getting back to devops-related things in the next few weeks as I check to see what my VMs have been doing.

I'll close this until I can get back to where I was when I had to put this down.

**Comment by SwampDragons** [comment]
No worries; it's a nice-to-have improvement, not something that's crippling our ability to run builds. If you find the time to do it, that would be great, but if not we'll rework them sometime later, probably after we figure out the situation with the vSphere builder.

**Pull request closed without merging**
