### PR TITLE
feat: OSC: add x509 certificate support

### LINKED ISSUE #9934: x509 Client certificates support for Outscale
### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Outscale API now supports x509 Client certificate authentication, in addition of traditional AK/SK HMAC based auth.
This adds an additional layer of security, especially desirable on SecNumCloud compliant regions (cloudgouv-eu-west-1).

You can create a policy that allows either certificate validation, source IPv4 validation, or both. If certificate validation is enabled, every call MUST be done using an x509 client certificate signed by the Certificate Authority allowed in the policy. 

#### Use Case(s)

The feature to manage authentication policies is not yet implemented on Outscale API, but certificate authority is already manually configured for some users, meaning they can no longer use Packer in its current state, as it is required to use a client certificate to do so.

Certificate authentication is implemented on Outscale official CLI client, [osc-cli](https://github.com/outscale/osc-cli), where you can set "client_certificate" parameter to a file containing both a base64 encoded pem certificate concatenated with its key.

#### Potential configuration

```
"builders": [
        {
            "type": "osc-bsusurrogate",
            "client_certificate": "/tmp/cert.pem",
            ...
        }
]
```

### PR DESCRIPTION
**Pull request by marinsalinas**
Adding support to x509 certificate authentication.

If your PR resolves any open issue(s), please indicate them like this so they will be closed when your PR is merged:

Closes #9934

### CODE REVIEW

**Comment by SwampDragons** [comment]
Looks like you need to check tests.

**Comment by marinsalinas** [comment]
@SwampDragons looks like it is more like Circle CI error can you rerun the job to see if the error persist?
https://app.circleci.com/pipelines/github/hashicorp/packer/7686/workflows/949ca13e-865a-4455-877e-cecf27bb9ed3/jobs/88433

**Comment by azr** [comment]
That is so weird because everything else works just fine but this just constantly fails. I'm guessing this is probably a deprecated xcode version and a sticky instance issue.

**Comment by marinsalinas** [comment]
> That is so weird because every other darwin build works just fine but this just constantly fails. I'm guessing this is probably a deprecated xcode version and a sticky instance issue.

it is something I can do to get this build running?

**Comment by SwampDragons** [comment]
Try rebasing on the master branch and pushing again?

**Comment by marinsalinas** [comment]
> Try rebasing on the master branch and pushing again?
Done!

**Comment by marinsalinas** [comment]
Hey @SwampDragons all the checks passed now 👍

**Pull request merged**
