### PR TITLE
website: update Netlify redirect syntax

### PR DESCRIPTION
**Pull request by mwickett**
Netlify [is adjusting the way they handle redirects](https://community.netlify.com/t/changed-behavior-in-redirects/10084) to be more explicit. If a path has content (i.e. it's not `404`), then any redirects _without_ the `!` after the status code will be ignored and the content will be served. 

We always want these redirect rules to be honored, even in the unlikely event that we had content at the source path. 

This PR adds the status code with the force directive (`301!`) to all redirects. Future redirects should follow this pattern, unless they are a proxy `200` redirect, or we want to take advantage of Netlify's conditional redirect behavior.

### CODE REVIEW

**Comment by SwampDragons** [comment]
Should I merge this now, or after the website refresh lands?

**Comment by mwickett** [comment]
Netlify is changing their redirect behavior as of April 7, so this will need to be merged before (immediately is fine). Just tagging @jescalan here for visibility.

**Comment by SwampDragons** [comment]
Cool, sounds good to me :)

**Comment by SwampDragons** [comment]
Does this also need a website deploy?

**Comment by mwickett** [comment]
Yes please, and thanks.

**Comment by SwampDragons** [comment]
ok, cherry picked and pushed to our site deploy branch.

**Pull request merged**
