### PR TITLE
Hyperv vmcx builder and allow vhd/vhdx instead of ISO

### PR DESCRIPTION
**Pull request by vijayinvites**
Fix merge conflicts of the PR: https://github.com/hashicorp/packer/pull/4944

### CODE REVIEW

**Comment by mwhooker** [comment]
this is great, thanks!

**Comment by vijayinvites** [comment]
@mwhooker , I want to add some new features to the vmcx builder. This PR has been there for long. How do i send a separate PR with only my new changes. Ofcourse I need the vmcx PR code. i am new to this process flow, so sorry if this is basic question.

**Comment by SwampDragons** [comment]
@pvandervelde any chance you can check this out and test this for us?

**Comment by mwhooker** [comment]
@vijayinvites no problem, happy to help. This can be a bit complicated, so please ask for clarification if you need help.

The best way to do that is to make your new changes off of this branch. Push those new changes to to github, and then make a new PR. Once this PR is merged, we can look at your new PR which will just have your changes.

**Comment by pvandervelde** [comment]
@SwampDragons Yeah can do. Will build a copy either tonight (NZ time) or sometime during the weekend and run some tests.

**Comment by SwampDragons** [comment]
If you can do it tonight, we'd appreciate it.  We're hoping to do a release tomorrow and want to squeeze this in.

**Comment by pvandervelde** [comment]
@SwampDragons I will try but I can't promise anything. Might have to be tomorrow morning NZ time

**Comment by pvandervelde** [comment]
@SwampDragons I managed to merge the change to master on my local machine, build a new version of packer and then run a few tests. I've tested on a Win10 host, building an Ubuntu linux box. I won't be able to test running on Win2016 until monday when I'm back in the office (I don't have a Win2016 box at home). The tests all worked fine so if you're happy with that you can release.

**Comment by vijayinvites** [comment]
I have tested Win7 and Win10 builds on Win10 host. No issues that i know of.

**Pull request merged**
