### PR TITLE
[WIP] builder/amazon: Update logic for session credentials

### LINKED ISSUE #10000: Packer v1.6.3 - Error loading credentials for AWS Provider
Packer v1.6.3 giving error while fetching loading credentials from IAM instance role.

Please find log extract:
packer-builder-amazon-ebs plugin: [INFO] Attempting to use session-derived credentials
Build 'amazon-ebs' errored after 3 seconds 133 milliseconds: Error loading credentials for AWS Provider: %!w(<nil>)
==> Wait completed after 3 seconds 133 milliseconds
==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error loading credentials for AWS Provider: %!w(<nil>)

### PR DESCRIPTION
**Pull request by nywilken**
When falling back to Session credentials the build should not error if creds were returned successfully.

* Switching to %v verb instead of %w in case error is nil - temp change for now. 

Closes #10000

### CODE REVIEW

**Comment by bretmartin** [comment]
This works for me using the same build config I reported as non-working in #10000.

**Comment by nywilken** [comment]
> This works for me using the same build config I reported as non-working in #10000.

Awesome, glad to hear that. Thanks for giving it a test @bretmartin.

**Comment by SwampDragons** [comment]
@bretmartin can you do one more test with the latest build? We redid the logic to make Packer use a Terraform library for this, and while I've tested on a bunch of other settings, and the library itself is well-tested, I want to make sure it works for the broken use case.

**Comment by bretmartin** [comment]
@SwampDragons Sure thing, pulling and building now.

**Comment by SwampDragons** [comment]
Thanks. I was able to build with an attached role, but I'm paranoid now.

**Comment by bretmartin** [comment]
@SwampDragons I hear you 🙂

Tested 4c0ac69 with no problems (assuming role via an IAM user with an access key).

**Comment by SwampDragons** [comment]
Awesome. I'll merge and plan for a mini patch release tomorrow.

**Pull request merged**
