### PR TITLE
docs/azure-arm: Refactor docs to clear up required options

### LINKED ISSUE #8672: Azure Docs "required" section is confusing
the "required" configuration section implies that the user _must_ build from a marketplace image; the ability to build from a managed image source is buried way down in the "optional" section and you kind of have to know it's there to find it. Let's reorganize the Azure docs to break down the "required" section into "if you're using the marketplace" versus "if you're using a managed image" sections.

### PR DESCRIPTION
**Pull request by nywilken**
This changes separates the required configurations options needed when using Azure Marketplace images vs Custom user built Images.

Closes #8672

### CODE REVIEW

**Comment by nywilken** [comment]
@paulmey @azr thanks for the initial review. I plan to make a few little changes to the docs. I'll ping once ready for a second review.

**Comment by nywilken** [comment]
I went ahead and updated the docs a bit. Screenshots attached or you can pull down the branch and run `make website` in the website directory. 

page1


page2

**Comment by azr** [comment]
The website is also auto deployed for a branch: https://deploy-preview-8698--packer-www.netlify.com/

**Comment by SwampDragons** [comment]
I think this looks good; just needs conflicts resolved and then you can merge.

**Pull request merged**
