### PR TITLE
fix regression :(

### LINKED ISSUE #5589: ISO download failed, wrong iso_url variable
- Packer 1.1.2
- Host Windows 7 64 Bit

With Packer 1.1.2 (Dosn't work file://):
```
PS C:\ISOs\packer> .\build-W2k16.ps1
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: file://C:/ISOs/packer/en_windows_server_
2016_x64_dvd_9718492.iso
    vmware-iso: Error downloading: CreateFile ISOs/packer/en_windows_server_2016
_x64_dvd_9718492.iso: The system cannot find the path specified.
==> vmware-iso: ISO download failed.
```

With Packer 1.1.1 (does work file:///):
```
PS C:\ISOs\packer> .\build-W2k16.ps1
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: file:///C:/ISOs/packer/en_windows_server
_2016_x64_dvd_9718492.iso
```

Is it possible to add the third slash back to the path variable?

### PR DESCRIPTION
**Pull request by SwampDragons**
Re-add the workaround code that we thought was no longer needed. cc @mwhooker 

closes #5589

### CODE REVIEW

**Comment by mwhooker** [comment]
><

would like to understand where the gap in our understanding came from. Maybe the comment was wrong to begin with

**Comment by SwampDragons** [comment]
My guess is that we assume all absolute paths begin with "/", which isn't true for windows.

**Comment by SwampDragons** [comment]
but that doesn't seem right to me or else https://github.com/hashicorp/packer/blob/20390ff1ecd222cb7ff9ddd8ecafb0447c416987/common/config.go#L50-L56 would fix it?

**Comment by SwampDragons** [comment]
Looks like my change breaks things on windows... so maybe I'm barking up the wrong tree here.

**Comment by SwampDragons** [comment]
mmm bet this is it: https://github.com/hashicorp/packer/blob/20390ff1ecd222cb7ff9ddd8ecafb0447c416987/common/download.go#L133-L135

**Pull request merged**
