### PR TITLE
Add baiducloud to website/data/plugins-manifest.json

### PR DESCRIPTION
**Pull request by wylzabc**
Registered baiducloud packer plugin documentation to packer website

### CODE REVIEW

**Comment by nywilken** [comment]
Hi @wylzabc I believe you are in communication with @cgriggs01 for this change. So I am going to apply the waiting-reply and thinking label to this PR.

**Comment by wylzabc** [comment]
Hi, Wilken.
I have communicated with Chris about the packer plug-in integration. Now
the plug-in is being released to the official baidu organization.
It's right for you to do this operation.
Best wish
Yongliang

Wilken Rivera ***@***.***> 于2022年10月21日周五 22:28写道：

**Comment by cgriggs01** [comment]
Hi @wylzabc,
Have you gotten a chance to move to plugin repository over to the https://github.com/baidubce organization?

Once that is complete you'll need to update this PR with the correct path.

**Comment by wylzabc** [comment]
Hi Chris,
 It may take at least two weeks of internal audit and review. Before this
plug-in can be open source under the organization of baidubce.

After the project repository has been moved over to baidubce organization,
I will update this PR with the correct path.

Thanks,
Yongliang

Chris Griggs ***@***.***> 于2022年10月24日周一 21:59写道：

**Pull request closed without merging**
