### PR TITLE
Backport of Enable Iron Bank integration into release/1.8.x

### PR DESCRIPTION
**Pull request by hc-github-team-packer**
## Backport

This PR is auto-generated from #12042 to be assessed for backporting due to the inclusion of the label backport/1.8.x.

**WARNING** automatic cherry-pick of commits failed. Commits will require human attention.

The below text is copied from the body of the original PR.

---

This patch enables CRT's Iron Bank integration.

Matching backport labels to https://repo1.dso.mil/dsop/hashicorp/packer except ``1.9.x`` which does not appear in the list of labels.

### CODE REVIEW

**Comment by marianoasselborn** [comment]
@nywilken 👋 

I think we may want to re-open and commit the original change here too. We track Packer 1.8 in Iron Bank https://repo1.dso.mil/dsop/hashicorp/packer/1.8

**Comment by nywilken** [comment]
> @nywilken 👋
> 
> I think we may want to re-open and commit the original change here too. We track Packer 1.8 in Iron Bank https://repo1.dso.mil/dsop/hashicorp/packer/1.8

Hi @marianoasselborn it looks like we might need to cherry pick manually here, as the PR is empty and being added by the backport bot that is not blessed by the CLA bots. I'm not sure why this is happening to be honest. maybe @kylemac can speak to the backport setup. 

In the meantime I will cherry pick onto 1.8.x. Unless there are objections.

**Comment by marianoasselborn** [comment]
@nywilken no objections. I appreciate your help here :)

**Comment by nywilken** [comment]
Thanks for the quick response. The release branch has been updated  and pushed.

**Pull request closed without merging**
