### PR TITLE
Update ugorji/go/codec to v1.1.13

### PR DESCRIPTION
**Pull request by angdraug**
When running Packer built with modern[0] version of ugorji using a plugin built from source and therefore with the 2015 version currently pinned in Packer's go.mod, I hit ugorji/go#269 when my plugin tries to [pipe into a remote "cat > '%s'"](https://github.com/angdraug/packer-builder-nspawn-debootstrap/blob/master/builder/communicator.go#L33):

>  Build 'base-20201021-5f90bdf5-490e-582b-fb1d-b5d4315f5eaa' errored after 25 seconds 772 milliseconds: msgpack decode error [pos 274]: invalid length of bytes for decoding time - expecting 4 or 8 or 12, got 15

[0] As in, newer than ugorji/go@5a66da2 from 2017, e.g. Packer as packaged in Debian.

The same pipe works fine when either running Packer built from source (with the same pin to old ugorji), or forcing the plugin to build with the modern ugorji:

```
replace github.com/hashicorp/packer => github.com/angdraug/packer v1.6.4-ugorji-go-v1.1.13
```

Bringing ugorji in Packer to the current version will leap over this and other incompatibilities that have built up in ugorji over the years, will make custom plugins work out of the box with the Debian build of Packer, and will allow plugin writers to use modules that depend on newer versions of ugorji.

### CODE REVIEW

**Comment by azr** [comment]
Hello there, thank you for opening, have you seen this: https://github.com/hashicorp/packer/pull/9571#issuecomment-659511561 ?

**Comment by angdraug** [comment]
I only saw #9571 after submitting this (I only searched open issues for mentions of ugorji, my bad), I'll try an HCL2 template and report back.

**Comment by angdraug** [comment]
Converted my template to HCL2, build completed successfully:

```
source "nspawn-debootstrap" "base" {
  variant = "minbase"
}

build {
  sources = ["source.nspawn-debootstrap.base"]

  provisioner "apt" {
    packages = ["less", "vim-tiny"]
    sources = ["deb http://security.debian.org/debian-security buster/updates main contrib"]
    keys = ["/etc/apt/trusted.gpg.d/debian-archive-buster-security-automatic.gpg"]
  }

  post-processors {
    post-processor "shell-local" {
      command = "tar --zstd -C /var/lib/machines/base -cf base.tar.zst ."
    }

    post-processor "artifice" {
      files = ["base.tar.zst"]
    }
  }
}
```

**Comment by angdraug** [comment]
Some more references for fix repro:

Build log with HCL2 config: https://builds.sr.ht/~angdraug/job/327983
The config: https://git.sr.ht/~angdraug/packer-builder-nspawn/tree/master/nspawn.pkr.hcl
Build manifest: https://git.sr.ht/~angdraug/packer-builder-nspawn/tree/master/.build.yml

This runs with stock packer deb from Debian/sid that's built against ugorji-go v1.1.7 and packer-builder-nspawn and packer-provisioner-apt built locally against ugorji-go v1.1.13 (so no compatibility issues between these two versions).

**Comment by azr** [comment]
Hey @angdraug thats' really good news, thanks for testing this 🙂  ! Just FYI, because this changes the codec this will break the backwards compatibility for plugins of Packer that are not in this Github so we really want to wait until 1.7.0 before testing/merging this to give the maintainers a clear warning. We are currently working on the next patch release so we will not have time to test until next week.

**Comment by angdraug** [comment]
Waiting until v1.7.0 is the right call, I understand and completely agree. Until then, I have my workaround for my own plugins and it's trivial to replicate for anyone who hits the same problem.

**Comment by azr** [comment]
Hello there ! We're getting close to release 1.7.0; do you have time to fix conflicts for this one ? Cheers !

**Comment by angdraug** [comment]
This code now lives in packer-plugin-sdk, I resubmitted this change as hashicorp/packer-plugin-sdk#31.

**Pull request closed without merging**
