### PR TITLE
WIP: parallels: Fix attaching prl tools

### LINKED ISSUE #7155: parallels-iso: parallels_tools_mode with attach doesn't connect the drive
Packer Version = 1.3.3

When setting the parallels-iso builder's  parallels_tools_mode to attach the tools NEVER get attached to the dvd drive of the virtual machine.  

Is there a known limitation i need to be aware of when attempting to use attach?

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Closes #7155

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
This is currently unverified.

**Comment by TraGicCode** [comment]
Sure thing! Will do this first thing in the morning

**Comment by TraGicCode** [comment]
Hey @rickard-von-essen ,

Running packer with the provided binary now throws the following.  Is this what your expecting?

image

**Comment by rickard-von-essen** [comment]
Oh, not it shouldn't. I'll copy pasted a bit to quickly, need to fix one thing..

**Comment by rickard-von-essen** [comment]
@TraGicCode I've updated the code to just add `--enable --connect`, could you test it? I've updated the linked zip.

**Comment by TraGicCode** [comment]
Hey @rickard-von-essen ,

That is great.  Let me try this now!

**Comment by TraGicCode** [comment]
Hey @rickard-von-essen ,

Worked like a charm.  Looks good thanks!

**Pull request merged**
