### PR TITLE
pin packer to golang 1.16

### PR DESCRIPTION
**Pull request by SwampDragons**
code generation is failing between v1.15 and v1.16 because of some changes to the os and io/fs libs. Move Packer requirement to v1.16.

### CODE REVIEW

**Comment by nywilken** [comment]
This looks good to me. I would like to upgrade and test locally as well. By chance did you test 1.16 against the packer-plugin-sdk? Anything we need to change there?

**Comment by SwampDragons** [comment]
I have 1.16 installed and have been able to build locally and run various Packer builds, and that uses the SDK. I don't think we need to pin the SDK explicitly.

**Review by azr — APPROVED** [review]
nice one, LGTM !

**Review by sylviamoss — APPROVED** [review]
Nice!

The SDK is on go 1.14. I think we should upgrade it as well.

**Review by nywilken — APPROVED** [review]
This looks good to me!


https://github.com/hashicorp/packer/blob/751038cd6df8967ce01edf9ec487fe28bece7c65/command/build_cancellation_test.go#L67


Go vet in 1.16 now flags calling T.Fatal in a non-test go rountine. We should be able to replace the call t.Fatal("...") with 

```go
t.Error("ParseArgs failed.")
return
```

**Pull request merged**
