### PR TITLE
website: remove obselete nav data

### PR DESCRIPTION
**Pull request by zchsh**
🔍  [Preview](https://packer-git-fork-zchsh-zsfixup-docs-nav-data-hashicorp.vercel.app/)

## Background

The `website/data/docs-navigation.js` data file and the `sidebar_title` frontmatter properties in all `.mdx` files are now ignored - they have been replaced by the revised `website/data/docs-nav-data.json` navigation data format, per [RFC MKTG-032](https://docs.google.com/document/d/1FPyWid2NmNI9E_6lH2UIMuEPqjqDCGe3F8wraPRQHQ8/edit#).

## Changes

This PR removes the now obselete `website/data/docs-navigation.js` file.

It also removes all `sidebar_title` frontmatter attributes from all `website/content/**/*.mdx` files.

### CODE REVIEW

**Review by nywilken — APPROVED** [review]
I'm good with this. I just want to call out that once merged we will need to use the nav_title front matter for the plugins we break out. Or we can continue using sidebar_title nav but if not needed we should conform to the new standard.

Not merging as I would like to get @sylviamoss thoughts on this.

**Review by azr — APPROVED** [review]
Nice one LGTM. I got confused last time and changed it in many places !

**Comment by sylviamoss** [comment]
@nywilken, @zchsh confirmed on slack that this won't affect the sidebar_title present on remote plugins. 
I'm removing the same file in https://github.com/hashicorp/packer/pull/10800

**Comment by sylviamoss** [comment]
The link checker is failing because of the following: 
```
FILE: website/content/docs/plugins/creation/index.mdx

ERROR: 1 dead links found!
[✖] https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.github/workflows/generate-docs-artifacts.yml → Status: 404
```
We can ignore it and fix it in another PR.

**Comment by zchsh** [comment]
Ah woops, I had some conflicts with https://github.com/hashicorp/packer/pull/10846 - have pulled in the content from upstream, so should be resolved now 👍

**Review by sylviamoss — APPROVED** [review]

**Review by azr — APPROVED** [review]
👍🏼

**Pull request merged**
