### PR TITLE
Pushing Import-Module Hyper-V

### LINKED ISSUE #4830: Hyperv-iso builder not importing Hyper-V Module
After reviewing my profile and validating that VMWare was removed and Hyper-V was imported. Still had new-vm loading with VMWare PowerCLI. The Builder needs to validate that it is using the Hyper-V module and make sure its imported before it runs. Yes I agree that VMWare should have built PowerCLI with different module names, and MS shouldn't let VMWare stomp on their profile, but it is required that I have PowerCLI installed on my computer, but it is not loaded in my profile so this is squarely on Packer to make sure they are loading Hyper-V prior to their build.

### PR DESCRIPTION
**Pull request by shotah**
Added a check to make sure Module Hyper-V is imported and if not imports the module for each script block used. 

Closes #4830

### CODE REVIEW

**Comment by mwhooker** [comment]
thanks!

**Comment by shotah** [comment]
Probably could have just added a `#Requires -modules Hyper-V` at the top of the scripts. Shorter and neater.

**Comment by taliesins** [comment]
@shotah you want to change the pull request to use the approach you suggested above?

**Comment by mwhooker** [comment]
Will merge with the cleaner change if it's ready for next release

**Comment by taliesins** [comment]
@shotah please update the pull request to use "#Requires -modules Hyper-V" as its cleaner

**Comment by mwhooker** [comment]
feel free to open a new PR with the above changes. Thanks!

**Comment by shotah** [comment]
Hyper-V\Get-VM  would be an even cleaner solution. I can created a new PR. Sorry about that.

**Pull request closed without merging**
