### PR TITLE
add codeowners file

### PR DESCRIPTION
**Pull request by mwhooker**
see https://help.github.com/articles/about-codeowners/

Please let me know if anyone here would like not to be an owner for the paths given. I will wait at least a week before merging unless I get a +1 from the following:

- [x] @boumenot 
- [ ] @taliesins 
- [x] @jen20 
- [x] @sean- 
- [x] @bhcleek 
- [x] @stevendborrelli

### CODE REVIEW

**Comment by BrianHicks** [comment]
The owner for Converge should probably be @stevendborrelli

**Comment by bhcleek** [comment]
+1

**Comment by jen20** [comment]
+1, also happy to look after ebssurrogate and so forth.


James

James

**Comment by boumenot** [comment]
+1

**Comment by stevendborrelli** [comment]
+1

**Comment by sean-** [comment]
+1

**Pull request merged**
