### PR TITLE
Add S3 community provisioner to docs

### PR DESCRIPTION
**Pull request by freggy**
Hey everyone, I created a provisioner supporting file retrival from S3 a while ago, and I thought it would be a good idea to add it to the docs :)

### CODE REVIEW

**Comment by lbajolet-hashicorp** [comment]
Hi @freggy,

Thanks for the PR! Before we can consider merging it, I need to ask you to sign our CLA, otherwise I won't be able to accept the PR for legal reasons, sorry about that.

On another note, we have a process for adding external plugins to our documentation website, you can find instructions on our [docs](https://developer.hashicorp.com/packer/docs/plugins/creation#registering-plugins), if you're interested please feel free to take a look at this and let us know if you have questions on that workflow, we'll be happy to help.

In the meantime, if you're able/willing to sign the CLA, I'll gladly review and merge your PR, thanks!

**Comment by freggy** [comment]
hey @lbajolet-hashicorp, I have already signed the CLA. Just tried it again and all the text fields in the form are prefilled with my information and I cannot re-sign it. For me the GitHub checklist also shows `license/cla` with a green checkmark.

I would be generally interested in adding the required steps to register my plugin as a Packer integration, but I can't tell when I will find time to do it. Is this required in order to have my plugin listed as a community provisioner?

**Comment by lbajolet-hashicorp** [comment]
Oh yeah my bad I missed the green check, the bot sometimes (often I must say, kinda problematic if you ask me) comments twice, and I miss one of the two :/
Sorry about the confusion.

Regarding integrations, it's not required no, it does offer the benefit that the plugin's docs will be accessible through https://developer.hashicorp.com/packer/integrations once the onboarding is finished, but that's up to you if/when you want to do this, no rush :)

I'll merge this today in the meantime, you should be able to see that live in the next few hours!

Thanks again for the update

**Review by lbajolet-hashicorp — APPROVED** [review]
LGTM!

**Comment by freggy** [comment]
no worries :) thanks for the quick response!

**Pull request merged**
