### PR TITLE
Unrevert proxmox merge revert

### PR DESCRIPTION
**Pull request by azr**
This reverts commit 032527ecfe2c5a9fcbe32c63cdf7755f2777df88.

This ~will build but the CI will fail !~ updates the vendor dir to be on par with what's in the go mod dir.

### CODE REVIEW

**Comment by azr** [comment]
Okay sounds like the code is building and up to date ! Time to merge.

**Comment by shantanugadgil** [comment]
Hi, as an avid fan of Proxmox (and all tools HashiCorp :grinning: ) what is the final verdict here?

Is Packer v 1.4.0 (or a future version) landing with the Proxmox builder?

I see that the new builder entry has been removed from the CHANGELOG altogether! :cry:

**Comment by shantanugadgil** [comment]
@azr bump

**Comment by azr** [comment]
Hello @shantanugadgil ! 🙂 


Unfortunately promox vendor was not 100% on par at the time packer 1.4.0 was released and packer 1.4.0 is without proxmox; the next official binary containing it will be 1.4.1. 
That said if you built packer yourself on master right now everything should be fine as not many things were merged since then.

So, here are a bunch of binaries based on the current master:
[darwin_amd64.zip](https://github.com/hashicorp/packer/files/3079378/darwin_amd64.zip)
[linux_amd64.zip](https://github.com/hashicorp/packer/files/3079379/linux_amd64.zip)
[windows_amd64.zip](https://github.com/hashicorp/packer/files/3079380/windows_amd64.zip)

78cf1405a

**Pull request merged**
