### PR TITLE
Gcp wait to add ssh keys 10312

### LINKED ISSUE #10312: googlecompute builder: Add option wait_to_add_ssh_keys
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

We use in-house security hardened GCP machine images to underpin our temporary packer instances. We cannot control the boot sequence of those images. The packer instance boot sequence is clearly interfering with the placement of SSH keys on the packer instance, and hence preventing the subsequent establishment of an SSH session.

The feature we are proposing is to add a switch called `wait_to_add_ssh_keys=20m`. We will separate the packer instance creation into three steps:-

a) Create the packer instance WITHOUT SSH keys
b) sleep for the `wait_to_add_ssh_keys` interval. Configured to be a suitable time interval to allow the GCEGuestAgent to stabilise.
c) Add the SSH keys to the running packer instance

We are prepared to submit a PR, so are gauging interest, and more importantly, likelihood of merging.

Note: The current `pause_before_connecting` option will not give us the functionality we need because it happens AFTER SSH key exchange and SSH connection establishment (should really be called `pause_before_provisioning`, but I digress).

#### Use Case(s)

Guard against disruptive boot sequences on:-

- In-house built GCP machine images used to create packer instances on GCP.
- Standard GCP images (future proofing).

#### Potential configuration

```
wait_to_add_ssh_keys=20m
wait_to_add_ssh_keys=15s
etc
```

#### Potential References

Packer log and cut-down packer instance log:-

https://gist.github.com/seventieskid/bc15a4bb45a8e1ce9b225b18047809ca

### PR DESCRIPTION
**Pull request by seventieskid**
Adds a switch called wait_to_add_ssh_keys=20m. We will separate the packer instance creation into three steps:-

a) Create the packer instance WITHOUT SSH keys
b) sleep for the wait_to_add_ssh_keys interval. Configured to be a suitable time interval to allow the GCEGuestAgent to stabilise.
c) Add the SSH keys to the running packer instance

- https://github.com/seventieskid/packer/blob/master/builder/googlecompute/step_create_instance_test.goL389-475

Closes #10312

### CODE REVIEW

**Comment by seventieskid** [comment]
@SwampDragons - I have agreed to the license terms, but step is still showing as pending. Could you please advise.

**Comment by SwampDragons** [comment]
Normally this happens because the email you used to sign the CLA doesn't match the email you used to make the commits.

**Comment by seventieskid** [comment]
Thanks for coming back to me. I double checked it, and it is the same. I can't re-accept the license because the details (and email) are now greyed out. So I'm stuck. What do you recommend ? I thought about resetting my local git user.email and pushing through a dummy commit, thus ensuring the email is on the latest commit. What do you think ? Or can you overrride it at your end ? You can see I have accepted the agreement.

**Comment by SwampDragons** [comment]
I just checked the commits and it's committed with an email that's "...@Gareths-MacBook-Pro.local" -- you sure that's your normal github email/the one you signed the CLA with?

**Comment by seventieskid** [comment]
OK, that’s my fault. Will rectify. Thanks for checking it.

**Comment by seventieskid** [comment]
@SwampDragons - ok, all good for review. Not sure why I can't see it on the list of open PRs though.

**Review by SwampDragons — APPROVED** [review]

**Pull request merged**
