### PR TITLE
website: update next and nextjs-scripts backport

### PR DESCRIPTION
**Pull request by BRKalow**
Backport of #10570

### CODE REVIEW

**Review by azr — APPROVED** [review]
LGTM

**Comment by nywilken** [comment]
@BRKalow since this was already merged to the master branch we can cherry-pick the commit on to stable-website. That's generally the approach we take. I can cherry-pick the commit and close this PR if that's okay with you.

**Comment by BRKalow** [comment]
@nywilken Works for me! Thanks 🙏

**Comment by nywilken** [comment]
@BRKalow done :+1:

**Pull request closed without merging**
