### PR TITLE
Update to gopsutil v3.21.1 to allow builds to work for darwin arm64

### PR DESCRIPTION
**Pull request by trodemaster**
Updating to the latest version of gopsutil allows packer to build on darwin arm64 platform with go 1.16

### CODE REVIEW

**Comment by trodemaster** [comment]
I'm not able to see why the checks are failing so please let me know if any action is needed on my part.

**Comment by SwampDragons** [comment]
Looks like a code generation bug: `builder/vsphere/common/output_config.hcl2spec.go:6:2: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)`

You can solve for this PR by just checking out those two vsphere files from the master branch and recommitting.

**Comment by trodemaster** [comment]
I'm not clear which two files you mean here? I see these referenced in the output_config.hcl2spec.go file. 

```
github.com/hashicorp/hcl/v2/hcldec
github.com/zclconf/go-cty/cty
```

Apologies as this newer go version and go get are confusing me with how the modules are getting downloaded. That may be part of my issue.

**Comment by SwampDragons** [comment]
Sorry, to clarify: it looks like you ran "make generate" against our codebase. That was good. Unfortunately, our CI server is on golang 1.15 and you're on golang 1.16. The 1.16 release aliased os.FileMode and a few other things to the io/fs lib and it's breaking the compatibility of generated code between the two versions. I'll fix it tomorrow and push a fix to this branch.

**Comment by SwampDragons** [comment]
The above push fixes the autogenerated files that shouldn't have been part of your changes; Once we've merged https://github.com/hashicorp/packer/pull/10702 we should be able to rerun and get tests passing.

**Comment by trodemaster** [comment]
OK sounds good! Reviewing what you changed I now understand what's going on. Go version 1.16 was needed for Apple Silicon build support so it's good you fixed #10702 as well.

**Review by azr — APPROVED** [review]

**Pull request merged**
