### PR TITLE
[azure] Set correct user agent for Azure client set

### PR DESCRIPTION
**Pull request by paulmey**
Set Packer user agent header on all requests to Azure.

### CODE REVIEW

**Comment by paulmey** [comment]
@azr @SwampDragons check-generate failure seems unrelated?

**Comment by SwampDragons** [comment]
Looks like some of the work Adrien's doing to get Packer ready for HCL2 support made make generate grumpy about your struct change. I just regenerated code and pushed to your branch, so hopefully it'll be green in the AM.

**Comment by SwampDragons** [comment]
o.O spoke too soon. I BROKE IT ALL.

**Comment by SwampDragons** [comment]
Sorry Paul -- I gotta log off to pick up the kiddo from school but I'll fix tests and get this across the finish line for you tomorrow.

**Comment by paulmey** [comment]
NP, I don't think I changed a related struct though... The only struct I touched is internal and only exposed through an interface...?

**Comment by paulmey** [comment]
Thanks @SwampDragons !

**Pull request merged**
